### ISSUE TITLE
文字环绕

### ISSUE THREAD

**Issue by stone-zeng** [stone-zeng/fduthesis#1]
## 位置参数

- `absolute_postion`：指定坐标（X,Y）
- `relative_postion`：指定相对文字的位置（行锚点 + 水平位置）

## 环绕方式

（抄 MS word）
- 四周
- 上下
- 浮于文字上
- 衬于文字下
- 环绕顶点？

**Comment by nanmu42** [comment]
L3实现？
太棒了。
期待看到你的成品。:)
