### ISSUE TITLE
方正书宋的“论”字

### ISSUE THREAD

**Issue by Stone-Zeng** [Stone-Zeng/fduthesis#10]
version 5.30，大概是画崩了：
![default](https://user-images.githubusercontent.com/18233088/28715453-a2175e3e-73ca-11e7-8f2b-2c56e5fbb164.PNG)

毕竟免费字体。新书宋就好很多。

**Comment by Man-Ting-Fang** [comment]
网上能见到的方正字体多为 TTF 格式，据闻都是由原始设计版本直接自动转换的，并且字体的 UPM 大多只有 256，所以图中问题应该是转换时造成的，不是设计时画坏的。方正的 TTF 字体中这种问题其实很常见。

对于方正书宋，如果只用到简体字的话，可以考虑使用“方正规范书宋”，这个字体就是方正官方基于方正书宋修改来的，风格完全一致，但有两点重要改进：一是完全符合 2013 年《通用汉字规范表》的字形写法，二是使用 1000 的 UPM，精度比方正书宋高很多，图中这种转换时的失真也几乎没有了。按我个人的看法，这个字体是简体中文宋体中质量最好的那一层次的。唯一的遗憾就是，这个字体的授权只限于个人使用，貌似连商业使用都没有（需要单独跟方正联系）；而方正定义的“个人使用”范围又太狭窄。
“方正规范书宋”链接：http://ifont.foundertype.com/index/generalfonts.html

**Comment by Stone-Zeng** [comment]
能成套使用（宋黑仿楷都齐全）的免费中午字体实在太少了，或者说基本没有。唯一能用的就是李阿玲的 fandol，然而又缺字得厉害。如果是只用宋体黑体，思源倒是很好；不过有时候楷书、仿宋什么的都要有，只好折中一下了。但怎么说方正把这几个字体设成免费还是挺好的。

**Comment by Stone-Zeng** [comment]
问了一下方正：

> 如您需商业发布使用我司字体，仅有“方正书宋、方正黑体、方正楷体、方正仿宋”四款字体可以免费使用。关于您提供的“方正规范书宋”，我司没有该款产品。

也是醉了 :laughing:

**Comment by ShellingFord221** [comment]
想问一下正文如何使用楷体？\kaishu 试了不行

**Comment by note286** [comment]
@ShellingFord221 `{\itshape 测试}`或者`\textit{测试}`。

**Comment by ShellingFord221** [comment]
感谢，不过`\makeatletter`或者`\makeatother`好像还是不行

使用overleaf，在windows上，没有调整过style

**Comment by note286** [comment]
我是在Windows，TeX Live 2022。
```latex
\documentclass{fduthesis}
\begin{document}
测试
\makeatletter{\fdu@kai 测试}\makeatother
\end{document}
```
![image](https://user-images.githubusercontent.com/16207292/201108671-cbfe6c99-93e1-4546-b712-ea94cf126e79.png)

**Comment by stone-zeng** [comment]
用 `\emph`。

另外，请不要在已关闭的 issue 里提不相关的问题，建议开新的 issue 或 discussion。
