### ISSUE TITLE
请教：在 latex-action 里使用 fduthesis 失败

### ISSUE THREAD

**Issue by Jeff-Tian** [stone-zeng/fduthesis#101]
我在尝试使用 xu-cheng 的 latex-action 来编译 fduthesis，碰到错误：

```
Unknown message 'unsupported-engine' for module 'fduthesis'.
```

![image](https://user-images.githubusercontent.com/3367820/65386846-04062580-dd73-11e9-85b3-872750bd345b.png)

可否帮忙排查是哪里的问题，应该怎么解决？

完整错误信息在这里：https://github.com/Jeff-Tian/thesis-paper/commit/88105929197a30dda4a18ccf46b5bc9e95e4c318/checks

配置在这里：

https://github.com/Jeff-Tian/thesis-paper/blob/master/.github/workflows/blank.yml

谢谢！

**Comment by zepinglee** [comment]
你配置了 `args: "-xelatex ..."`，但是实际运行的还是用 pdflatex 编译的

**Comment by Jeff-Tian** [comment]
> 你配置了 `args: "-xelatex ..."`，但是实际运行的还是用 pdflatex 编译的

谢谢，不过详细错误信息是缺少 ctexbook，尝试安装也失败了：

![image](https://user-images.githubusercontent.com/3367820/65387238-dbccf580-dd77-11e9-97c8-e2170a4a0217.png)

**Comment by stone-zeng** [comment]
应该是包没有装全。`latex-action` 那里面装了下面这些：

https://github.com/xu-cheng/latex-action/blob/da7800d374b0cf40cbe6a6b28228a070e0c98321/setup.sh#L20-L27

可以看到有一个 `texliveonfly`，但要用的话可能需要

```sh
texliveonfly.py [options] file.tex
```

或者干脆把依赖都装全了（参考 [install-ubuntu-texlive.sh](https://github.com/stone-zeng/fduthesis/blob/master/.travis/install-ubuntu-texlive.sh)）。

**Comment by Jeff-Tian** [comment]
> 应该是包没有装全。`latex-action` 那里面装了下面这些：
> 
> ```shell
> echo "==> Install Packages"
> tlmgr update --self
> tlmgr install \
>   collection-fontsrecommended \
>   biber \
>   biblatex \
>   latexmk \
>   texliveonfly
> ```
> 
> 可以看到有一个 `texliveonfly`，但要用的话可能需要
> 
> ```shell
> texliveonfly.py [options] file.tex
> ```
> 
> 或者干脆把依赖都装全了（参考 [install-ubuntu-texlive.sh](https://github.com/stone-zeng/fduthesis/blob/master/.travis/install-ubuntu-texlive.sh)）。

谢谢，安装了所有依赖后成功了。
