### ISSUE TITLE
查重网站中上传PDF识别出来均为乱码

### ISSUE THREAD

**Issue by sonnyhcl** [stone-zeng/fduthesis#102]
在查重网站（如paperpass）中上传PDF识别出来均为乱码，目前查重采用手动`Ctrl+A` `Ctrl+C`来复制内容到查重网站中。不禁有点担心最后交PDF给学院上知网查重的时候，发现识别出来全是乱码被手动退回。

这个问题是latex生成的中文pdf固有的毛病么？有没有已经毕业的走过这个流程的出来解释一下

> 乱码样例
```
ਫ਼१๙ྛིੱđิശӚੀ๙ݖ෎؇đՖطิۚ֡ਫ਼ຩ઎֥Ӛਇ๽๳ੱbཌྷܱ࿹࣮ն؟ᆌؓದোࡐ൒ӚਇބགྷႵ֥ࢌ๙ྐࠏݼᇅđࡼ࿹࣮ᇗׄ٢ᄝࢌ๙ྐݼ॥ᇅ֥ҕඔטᆜaࢌ๙ຩ઎֥ຉ௪ܒࢲഈđࡼൈࡗഈཌྷ޺Ԋ๬֥ࢌ๙Ӛੀཌྷۯ޺৖đ൐ఃᄝ҂๝֥ൈࡗோ؎ଽ๙ݖၛЌᆣྛӚνಆđิۚਔਫ਼१๙ݖིੱđطᆌؓሱഒbࢠ࣮࿹੻๙॥ᇅҦࢌ֥Ӛਇ൒ࡐ׮ࡐ׮ᄯሱࡹݖᇏđದૌՖໃ๔ᆸൎ৥֥ࡀ၂۱ൗ࣍చӚၛটđᄝૼ
```

**Comment by stone-zeng** [comment]
按理说 PDF 复制在现在应该没有什么问题，可以的话，提供一下出现乱码的 PDF 文件（或者一部分）。

我当时是用 Acrobat 转成 Word 之后给他们查重的，看起来没有什么问题。

**Comment by sonnyhcl** [comment]
用现在的master代码新build了一个pdf

[fduthesis-template.pdf](https://github.com/stone-zeng/fduthesis/files/3641992/fduthesis-template.pdf)

（顺便修了一个安装脚本的bug[#103](#103) ）

**Comment by stone-zeng** [comment]
抱歉忘记回复了……

我用 [`pdfrw`](https://github.com/pmaupin/pdfrw) 检查了一下上面那个 PDF，字符串都是类似于 `<feff53c280036587732e>` 的 UTF-16 code points，但并没有什么办法能重现出那段乱码。总之并不清楚查重网站到底做了什么，这也超出我的能力范围。

**Comment by sonnyhcl** [comment]
天晓得查重网站的上传pdf到底做了什么..... 

只是提出一个发现的问题 复制到word里再查重作为workaround应该能保证工作

**Comment by TianLin0509** [comment]
我也碰到了这个情况，在paperpass上查重的时候显示全部乱码，所以会影响毕业的查重吗？

**Comment by stone-zeng** [comment]
见 https://www.paperpass.com/faq/1902.html

**Comment by TianLin0509** [comment]
> 见 https://www.paperpass.com/faq/1902.html

谢谢，我后面用了别的查重网站就正常了。 现在就怕知网查重有问题哈哈，毕竟最后提交的是这个pdf，要是知网识别成乱码就糟了。可惜知网试错成本太高得好几百，就想问下以前的同学们有没有查重类似的经历

**Comment by sikouhjw** [comment]
> > 见 https://www.paperpass.com/faq/1902.html
> 
> 谢谢，我后面用了别的查重网站就正常了。 现在就怕知网查重有问题哈哈，毕竟最后提交的是这个pdf，要是知网识别成乱码就糟了。可惜知网试错成本太高得好几百，就想问下以前的同学们有没有查重类似的经历

复制出来不是乱码，查重就不会有问题。

**Comment by TianLin0509** [comment]
> > > 见 https://www.paperpass.com/faq/1902.html
> > 
> > 
> > 谢谢，我后面用了别的查重网站就正常了。 现在就怕知网查重有问题哈哈，毕竟最后提交的是这个pdf，要是知网识别成乱码就糟了。可惜知网试错成本太高得好几百，就想问下以前的同学们有没有查重类似的经历
> 
> 复制出来不是乱码，查重就不会有问题。

谢谢，现在就是我按 https://www.paperpass.com/faq/1902.html 上说的 复制到txt，全都不是乱码（除了公式），但是上传到paperpass就全是乱码。 

然后我试了下免费的paperyy， 也是上传了相同的PDF， 就没有乱码。
所以综上所述我觉得这就是paperpass的锅 0.0
