### ISSUE TITLE
listings 这个package用起来不对

### ISSUE THREAD

**Issue by zzzxxxlll** [stone-zeng/fduthesis#104]
```tex
\begin{lstlisting}
    a=1
    b=2
\end{lstlisting}
```

这段代码编译出来后，变成了
aa=a=1
bb=b=2

这个有办法解决么
或者有没有其他可用的列出部分源码的方法

谢谢

**Comment by stone-zeng** [comment]
直接从 master 分支 checkout 出来的模板（ef37abfac4f29f3102b7806c80f638c0ca4be874），没有复现问题：

```tex
\documentclass{fduthesis}
\usepackage{listings}
\fdusetup{style/auto-make-cover=false}
\begin{document}
\begin{lstlisting}
    a=1
    b=2
\end{lstlisting}
\end{document}
```

![image](https://user-images.githubusercontent.com/18233088/65484079-ee0e7700-ded0-11e9-8010-63f20d091d51.png)

麻烦提供一下你的编译信息（模板的版本、TeX Live/MiKTeX 版本、有关各红包的版本、系统信息等）

**Comment by zzzxxxlll** [comment]
![image](https://user-images.githubusercontent.com/23472228/65505799-a998d080-defc-11e9-8ade-fce7869129ea.png)
用的overleaf上的fduthesis模板直接编译的

**Comment by zzzxxxlll** [comment]
那我在本地重新搭建环境吧，谢啦

**Comment by stone-zeng** [comment]
最近 overleaf 切到了 TeX Live 2018，所以从头新建一个 project（不要用 readme 里面那个链接），直接写就可以了：

![image](https://user-images.githubusercontent.com/18233088/65534291-b552ba00-df31-11e9-88fd-9c7c7ac47a2d.png)

过几天有空我要整理一下。
