### ISSUE TITLE
封面的指导小组成员一页可否删掉？

### ISSUE THREAD

**Issue by kalubin-awym** [stone-zeng/fduthesis#105]
导师说不要这一页 想问下怎么删除 谢谢

**Comment by stone-zeng** [comment]
加上选项 `style/auto-make-cover=false` 之后手动添加封面：

```tex
\documentclass{fduthesis}
\fdusetup{style/auto-make-cover=false}

\begin{document}

\begin{titlepage}
  \makecoveri
\end{titlepage}

\frontmatter

\tableofcontents

\mainmatter

\chapter{Test}

Hello

\backmatter

% 不需要也可以删掉
\makecoveriii

\end{document}
```

**Comment by kalubin-awym** [comment]
> 加上选项 `style/auto-make-cover=false` 之后手动添加封面：
> 
> ```
> \documentclass{fduthesis}
> \fdusetup{style/auto-make-cover=false}
> 
> \begin{document}
> 
> \begin{titlepage}
>   \makecoveri
> \end{titlepage}
> 
> \frontmatter
> 
> \tableofcontents
> 
> \mainmatter
> 
> \chapter{Test}
> 
> Hello
> 
> \backmatter
> 
> % 不需要也可以删掉
> \makecoveriii
> 
> \end{document}
> ```

搞定了 谢谢！！
