### ISSUE TITLE
Win10下扁平化安装遇到Qt: Untested Windows version 6.2 detected!

### ISSUE THREAD

**Issue by sliang11** [stone-zeng/fduthesis#108]
在执行install-Windows.bat时卡在xetex "fduthesis.dtx" > NUL这一步，提示Qt: Untested Windows version 6.2 detected!
请问如何解决？谢谢！

**Comment by stone-zeng** [comment]
装的是什么发行版？版本号是多少？系统版本号是多少？

**Comment by sliang11** [comment]
fduthesis是10月21号下午下载的，应该是最新版。操作系统是Win10家庭中文版64位（10.0，版本17763）

**Comment by sliang11** [comment]
> 装的是什么发行版？版本号是多少？系统版本号是多少？

fduthesis是10月21号下午下载的，应该是最新版。操作系统是Win10家庭中文版64位（10.0，版本17763）

**Comment by stone-zeng** [comment]
发行版？TeX Live 还是 MiKTeX？什么版本？

**Comment by sliang11** [comment]
> 发行版？TeX Live 还是 MiKTeX？什么版本？

MiKTeX-TeX 2.9.3759 (3.1415926) (MiKTeX 2.9)

**Comment by stone-zeng** [comment]
Qt 这一行警告应该是不影响的。有问题的应该是后面。

可以的话，麻烦你删去生成的文件，把 `install-win.bat` 里面的 `xetex "fduthesis.dtx" > NUL` 改为 `xetex "fduthesis.dtx"`，然后看一下到底卡在了哪里。可以把屏幕显示贴过来。

（猜测应该是宏包没有更新的缘故）

**Comment by sliang11** [comment]
> Qt 这一行警告应该是不影响的。有问题的应该是后面。
> 
> 可以的话，麻烦你删去生成的文件，把 `install-win.bat` 里面的 `xetex "fduthesis.dtx" > NUL` 改为 `xetex "fduthesis.dtx"`，然后看一下到底卡在了哪里。可以把屏幕显示贴过来。
> 
> （猜测应该是宏包没有更新的缘故）

E:\Academic\Lab\Dissertation\Dissertation\thesis>xetex "fduthesis.dtx"
Qt: Untested Windows version 6.2 detected!
This is XeTeX, Version 3.1415926-2.3-0.9997.5 (MiKTeX 2.9)
entering extended mode
(E:\Academic\Lab\Dissertation\Dissertation\thesis\fduthesis.dtx
! I can't find file `l3docstrip.tex'.
l.139 \input l3docstrip.tex

Please type another input file name:

这个是修改以后的输出

**Comment by stone-zeng** [comment]
那把缺的宏包装一下吧……

原则上 MiKTeX 应该会自动安装缺的包，但不知道为什么这边没有触发。参考 <https://miktex.org/howto/miktex-console>。

**Comment by sliang11** [comment]
> 那把缺的宏包装一下吧……
> 
> 原则上 MiKTeX 应该会自动安装缺的包，但不知道为什么这边没有触发。参考 https://miktex.org/howto/miktex-console。

问题解决，非常感谢！
