### ISSUE TITLE
生成pdf不显示参考文献

### ISSUE THREAD

**Issue by sliang11** [stone-zeng/fduthesis#110]
MiKTeX 2.9，在64位Win10下，用XeLaTeX和LuaLaTeX编译都不显示参考文献（其中用XeLaTeX编译，文中会有大量的字符和图片缺失），文中引用的部分都显示“[??]”，请问如何解决？

**Comment by zepinglee** [comment]
用 `latexmk -xelatex` 编译可以自动调用 `bibtex` 或 `biber`

**Comment by stone-zeng** [comment]
参考文献需要多次编译，至少是

```sh
xelatex 文件名
bibtex  文件名  # 或者 biber 文件名
xelatex 文件名
xelatex 文件名
```

当然我也推荐用 latexmk。

**Comment by stone-zeng** [comment]
> 文中会有大量的字符和图片缺失

另外，这是什么情况？可以截图说明一下吗？

**Comment by zepinglee** [comment]
关于编译方式，文档中写得太简略了，总会有新鸟不知道 bibtex 和 biber 的

**Comment by sliang11** [comment]
> 参考文献需要多次编译，至少是
> 
> ```shell
> xelatex 文件名
> bibtex  文件名  # 或者 biber 文件名
> xelatex 文件名
> xelatex 文件名
> ```
> 
> 当然我也推荐用 latexmk。

使用bibtex报错，错误信息如下：
Command Line:   bibtex.exe "fduthesis-template"
Startup Folder: E:\Academic\Lab\Dissertation\Dissertation\thesis

This is BibTeX, Version 0.99d (MiKTeX 2.9.7200)
The top-level auxiliary file: fduthesis-template.aux
The style file: gbt7714-unsrt.bst
I couldn't open database file fduthesis-template.bib.bib
---line 71 of file fduthesis-template.aux
 : \bibdata{fduthesis-template.bib
 :                                }
I'm skipping whatever remains of this command
I found no database files---while reading file fduthesis-template.aux
Warning--I didn't find a database entry for "曾谨言2013量子力学"
Warning--I didn't find a database entry for "feynman2011feynman"
Warning--I didn't find a database entry for "zurek2014quantum"
Warning--I didn't find a database entry for "cohen2013claude"
Warning--I didn't find a database entry for "zettili2003quantum"
Warning--I didn't find a database entry for "wikimedia:stern-gerlach-experiment"
(There were 2 error messages)

**Comment by stone-zeng** [comment]
> `! LaTeX Error: Something's wrong--perhaps a missing \item.`

这个大概是哪里写得不对，漏了逗号还是多了空行之类，你再检查一下。MiKTeX 和 TeX Live 在处理文件方面会略有不同，我这边暂时也不能确定是不是要带后缀名。另外，重新编译（完整的四次编译）前把辅助文件删一下。

**Comment by zepinglee** [comment]
按照 bibtex 的标准用法是不加 `.bib`，可能最新的 texlive 实现也允许加 `.bib`

**Comment by sliang11** [comment]
> > `! LaTeX Error: Something's wrong--perhaps a missing \item.`
> 
> 这个大概是哪里写得不对，漏了逗号还是多了空行之类，你再检查一下。MiKTeX 和 TeX Live 在处理文件方面会略有不同，我这边暂时也不能确定是不是要带后缀名。另外，重新编译（完整的四次编译）前把辅助文件删一下。

我把整个文件夹删了，重新用install-win.bat生成了一下，并手动把bib-source那里的.bib去掉，四次编译结果是对的。之前报那个错，我可以肯定不是我自己写错的原因，因为我只是把.bib去掉然后又加了回来，但是还是会出错，我个人推测应该是之前编译中生成的辅助文件的问题。

烦请您修改一下自动生成的.tex中的bib-source，把里边的.bib去掉。另外复议zepinglee，建议在文档中详细说明编译流程，目前只是说需要编译两次，没有提及四次编译的问题。
