### ISSUE TITLE
引用显示多余无用字符问题

### ISSUE THREAD

**Issue by keyianpai** [stone-zeng/fduthesis#113]
bibfile 中条目：
`@inproceedings{Fredrikson2014,
	title={Privacy in pharmacogenetics: An end-to-end case study of personalized warfarin dosing},
	author={Fredrikson, Matthew and Lantz, Eric and Jha, Somesh and Lin, Simon and Page, David and Ristenpart, Thomas},
	booktitle={23rd $\{$USENIX$\}$ Security Symposium ($\{$USENIX$\}$ Security 14)},
	pages={17--32},
	year={2014}
}`

编译显示多余无用信息：
![image](https://user-images.githubusercontent.com/20626421/71062320-2ad2cd00-21a5-11ea-8c66-ee619f6d8756.png)

**Comment by keyianpai** [comment]
将要上传图书馆定稿，希望学长百忙之中抽空解答，有机会请您喝咖啡，十分感谢！而且网址引用misc也不能显示网址

**Comment by keyianpai** [comment]
`@book{willenborg2012elements,
  title={Elements of statistical disclosure control},
  author={Willenborg, Leon and De Waal, Ton},
  volume={155},
  year={2012},
  publisher={Springer Science \& Business Media}
}`

![image](https://user-images.githubusercontent.com/20626421/71063952-d9c4d800-21a8-11ea-9464-622185fefb2b.png)

**Comment by keyianpai** [comment]
`@Misc{web,
	howpublished = {\url{http://timmurphy.org/2009/07/22/line-spacing-in-latex-documents/}},
	note = {Accessed April 4, 2010},
	title = {Line Spacing in LaTeX documents},
	author = {Murphy, Timothy I}
}`
![image](https://user-images.githubusercontent.com/20626421/71064206-830bce00-21a9-11ea-9560-15c559aea252.png)

**Comment by stone-zeng** [comment]
这个是国标 GB/T 7714-2015 的要求，表示出版地、出版者不详：

<img width="951" alt="Screen Shot 2019-12-18 at 16 14 13" src="https://user-images.githubusercontent.com/18233088/71068324-712e2900-21b1-11ea-8a14-332a4f1e9531.png">
<img width="941" alt="Screen Shot 2019-12-18 at 16 14 23" src="https://user-images.githubusercontent.com/18233088/71068336-75f2dd00-21b1-11ea-8af6-569d3bdd9b5a.png">

没有特殊需求，不建议修改；最好是找到有关信息并且补全。

实在想改，请看 [`gbt7714` 文档](http://mirrors.ctan.org/biblio/bibtex/contrib/gbt7714/gbt7714.pdf) 第 6 节。

参考：<https://github.com/xueruini/thuthesis/issues/292>, <https://github.com/xueruini/thuthesis/issues/421>, <https://github.com/CTeX-org/gbt7714-bibtex-style/issues/45>

**Comment by keyianpai** [comment]
谢谢学长！您的微信或支付宝可以通过邮箱（jianggentle@foxmail.com）发给我吗？我请您喝杯咖啡吧~~
另外下面引用网址，添加url的做法规范吗？（自动不会出现url，也即howpublished字段不管用）
`@Misc{web,
	howpublished = {\url{http://timmurphy.org/2009/07/22/line-spacing-in-latex-documents/}},
	note = {Accessed April 4, 2010},
	title = {Line Spacing in LaTeX documents},
	author = {Murphy, Timothy I},
	url={http://www.genome.gov/sequencingcosts/}
}`
![image](https://user-images.githubusercontent.com/20626421/71085300-21ac2500-21d2-11ea-825a-305674c21962.png)

**Comment by stone-zeng** [comment]
直接填 `url={...}` 就好，不需要用 `howpublished`。

**Comment by keyianpai** [comment]
谢谢学长~

**Comment by zepinglee** [comment]
最新版的 `gbt7714` 允许 `howpublished = {\url{http://timmurphy.org/2009/07/22/line-spacing-in-latex-documents/}}` 作为 url 录入方法的一种，毕竟这个是传统 BibTeX 的方法

**Comment by keyianpai** [comment]
@zepinglee  但是现在这个模板不可以，可能不是最新标准？

**Comment by zepinglee** [comment]
> @zepinglee 但是现在这个模板不可以，可能不是最新标准？

你用的是 bibtex 还是 biblatex？

**Comment by keyianpai** [comment]
bibtex吧，需要单独bibfile的

**Comment by keyianpai** [comment]
@zepinglee  `bib-backend = bibtex`

**Comment by zepinglee** [comment]
> @zepinglee `bib-backend = bibtex`

看来你用的 TeX Live 不是最新版的

**Comment by keyianpai** [comment]
> > @zepinglee `bib-backend = bibtex`
> 
> 看来你用的 TeX Live 不是最新版的

是2018版的

**Comment by zepinglee** [comment]
> > > @zepinglee `bib-backend = bibtex`
> > 
> > 
> > 看来你用的 TeX Live 不是最新版的
> 
> 是2018版的

<img width="287" alt="Screen Shot 2019-12-18 at 8 57 49 PM" src="https://user-images.githubusercontent.com/12290822/71088336-20322b00-21d9-11ea-8fcd-6b6f99a87a83.png">

你可以考虑把 https://github.com/CTeX-org/gbt7714-bibtex-style 最新的两个 bst 文件跟 fduthesis.cls 放到一起，就可以使用了

**Comment by keyianpai** [comment]
> > > > @zepinglee `bib-backend = bibtex`
> > > 
> > > 
> > > 看来你用的 TeX Live 不是最新版的
> > 
> > 
> > 是2018版的
> 
> <img alt="Screen Shot 2019-12-18 at 8 57 49 PM" width="287" src="https://user-images.githubusercontent.com/12290822/71088336-20322b00-21d9-11ea-8fcd-6b6f99a87a83.png">
> 
> 你可以考虑把 https://github.com/CTeX-org/gbt7714-bibtex-style 最新的两个 `bst` 文件跟 `fduthesis.cls` 放到一起，就可以使用了

谢谢~目前满足于之前学长提供的方案。。
