### ISSUE TITLE
【图书馆审核】研究生专业学位的封面中“专业”应为“学位类别（领域）”

### ISSUE THREAD

**Issue by sonnyhcl** [stone-zeng/fduthesis#114]
复旦大学研究生学位论文封面标准样本
要求见 http://www.gs.fudan.edu.cn/c3/02/c2881a115458/page.htm

![image](https://user-images.githubusercontent.com/10840522/71342901-0f970180-2599-11ea-8482-529c3e71eab3.png)

**Comment by ZZCer** [comment]
貌似专硕是这样，学硕还是“专业”，模板可以按照这个判断一下。

**Comment by sonnyhcl** [comment]
在另一个复旦大学博士、硕士学位论文规范（2017.03修订版）
http://www.gs.fudan.edu.cn/6b/9f/c2806a27551/page.htm 中的封面规范又有细微不同。。这里"专业“两个字是”专业学位类别（领域）"

![image](https://user-images.githubusercontent.com/10840522/71343423-be880d00-259a-11ea-9e9c-48c5d493c687.png)

...给学校的规定跪了

**Comment by stone-zeng** [comment]
导言区加上

```tex
\ExplSyntaxOn
\tl_set:Nn \c__fdu_name_major_tl { 学位类别（领域） }
\__fdu_patch_cmd:Nnn \__fdu_cover_info: { 6em } { 7.5em }  % 7.5em 视情况而定
% 或者
% \tl_set:Nn \c__fdu_name_major_tl { 专业学位类别（领域） }
% \__fdu_patch_cmd:Nnn \__fdu_cover_info: { 6em } { 9em }
\ExplSyntaxOff
```

但是因为还有标点挤压，会比较丑：

![image](https://user-images.githubusercontent.com/18233088/71346478-f72be480-25a2-11ea-8664-f1ad1bae687f.png)

这个地方现在看来用表格实现可能会更好一点，以后有空再重构了。

**Comment by pushlover** [comment]
请问第二列的姓名那些如何设置成左对齐呀，居中对齐看着好别扭

**Comment by XuanjieXiao** [comment]
请问这个导言区在哪个文件里面打开设置呀？然后还有一个问题想要请教，就是封面硕士学位论文时候，我想将这几个字给改一下，然后我平时的实验论文也想用这个格式去做，请问一下在哪个源文件修改？

**Comment by stone-zeng** [comment]
> 请问这个导言区在哪个文件里面打开设置呀？

导言区就是 `\documentclass` 到 `\begin{document}` 之间的地方。

> 然后还有一个问题想要请教，就是封面硕士学位论文时候，我想将这几个字给改一下，然后我平时的实验论文也想用这个格式去做，请问一下在哪个源文件修改？

不建议用本模板来写实验论文，修改格式的工作量比较大，没有必要。

**Comment by XuanjieXiao** [comment]
您好，师兄，我们老师让我们就用毕业论文模板写，所以其实格式就一样要求，就只是需要修改一下封面硕士学位论文这几个字改为实验报告，但是我实在在您的源文件找了好久都没找到对应的代码，想要请教一下，麻烦您嘞。

**Comment by stone-zeng** [comment]
> 我们老师让我们就用毕业论文模板写，所以其实格式就一样要求，就只是需要修改一下封面硕士学位论文这几个字改为实验报告

建议用下面的方法修改：

```tex
\documentclass{fduthesis}
\ExplSyntaxOn
\cs_set_protected:Npn \__fdu_cover_type:
  { \__fdu_spread_box:nn { 0.3 \textwidth } { 实验论文 } }
\ExplSyntaxOff
\begin{document}
\end{document}
```

> 但是我实在在您的源文件找了好久都没找到对应的代码

一定要看的话，是在这里定义的：

https://github.com/stone-zeng/fduthesis/blob/6c32f74f79618157c5f071d1773ef29f46f6daef/source/fduthesis.dtx#L6072-L6073
