### ISSUE TITLE
小白问一哈怎么加一章致谢啊？

### ISSUE THREAD

**Issue by shaonvxyz** [stone-zeng/fduthesis#116]
求大佬指教！（顺便致谢一下大佬，手动星星眼）

**Comment by stone-zeng** [comment]
写在 `\backmatter` 之后：

```tex
\documentclass{fduthesis}
\begin{document}
\mainmatter
\chapter{测试}
\chapter{测试}
\backmatter
\chapter{致谢}
\end{document}
```

**Comment by note286** [comment]
@striverwheat `\chapter{致\quad{}谢}`。

**Comment by ZhouWenjun2019** [comment]
现在 致谢环境 已经移除了吗？

**Comment by sikouhjw** [comment]
> 现在 致谢环境 已经移除了吗？

没有，请你更新模板
https://github.com/stone-zeng/fduthesis/blob/c4dc227f7c61ea31e9a4af615fa10e3f85618618/docs/main.tex#L393-L395
