### ISSUE TITLE
目录里插入目录的页码

### ISSUE THREAD

**Issue by Bae984** [stone-zeng/fduthesis#117]
现在是这样子的
<img width="356" alt="1" src="https://user-images.githubusercontent.com/19869716/71758688-0897b980-2ede-11ea-84a7-64e29430919f.png">
我想这样
<img width="714" alt="2" src="https://user-images.githubusercontent.com/19869716/71758845-c96a6800-2edf-11ea-9743-8925ffdbf7c0.png">

**Comment by zepinglee** [comment]
把目录加到 pdf 书签还比较正常，但是把目录加进目录会很奇怪

**Comment by Bae984** [comment]
我看师兄师姐的论文都是这样的 如果我想这样做 有什么办法吗？

**Comment by stone-zeng** [comment]
其实如 @zepinglee 所说，是故意没把目录放进目录的。

修改的话，在导言区加上：

```tex
\ExplSyntaxOn
\cs_set_eq:NN \__fdu_chapter_no_toc:V \__fdu_chapter:V
\ExplSyntaxOff
```

**Comment by Bae984** [comment]
好了 谢谢！
