### ISSUE TITLE
章节标题修改

### ISSUE THREAD

**Issue by stone-zeng** [stone-zeng/fduthesis#118]
> 我有两个fduthesis不懂的地方想请教一下哈。我是直接用模板fduthesis-template.tex的编译。
>
> 1. 英文Abstract的格式设置是哪个文件？比如我如果想实现“Abstract”改成“ABSTRACT”，或者让abstract不出现在目录中，该怎么做？【纯粹个人好奇】
> 2. 我发现如果在 `\printbibliography` 前面加入 `\chapter{A}`，会自动变成，“第x章 A”，如果在`\printbibliography` 之后加入 `\chapter{B}`，会变成“B”，不会出现“第x章 B”。这个情况是latex自己的默认设定吗？另外，如果我想在参考文献前，加入一个章节，但又不想自动被编号成“第x章 ”，要怎么实现吗？

**Comment by yiminz** [comment]
你说的应该添加个附录。不出现标号用\chapter*{附录}
然后目录上也不会出现这个章节了。。
然后在该章节处加个\addcontentsline{toc}{chapter}{附录}
就可以；
