### ISSUE TITLE
段落间距与行间距应该相等么？

### ISSUE THREAD

**Issue by HubertSun7** [stone-zeng/fduthesis#119]
请教个问题，论文规范中：“字体：宋体、字号：小四号、字符间距：标准、行距：20磅。” 这里段落间距是否应该和字符间距相等？看起来好像段后的间隔和行间隔是不等的。

现在暂时用 
`
\setlength{\parskip}{0pt}
`
解决了一下

**Comment by stone-zeng** [comment]
中文的话，因为已经有段首缩进，所以段落间距（作为区分的手段）并不是必须的。

至于你的做法，也确实是可以，具体用不用就自行取舍吧。

参考：[行和段的区别是什么？在排版软件中如何分段？- 知乎](https://www.zhihu.com/question/27376099)

**Comment by HubertSun7** [comment]
OK，了解，多谢了
