### ISSUE TITLE
生成参考文献中有[S.l.: s.n]乱码

### ISSUE THREAD

**Issue by sliang11** [stone-zeng/fduthesis#121]
MiKTeX 2.9，在64位Win10下，LuaLatex -> Bibtex -> LuaLatex -> LuaLatex编译，生成的参考文献中所有会议论文的条目中在会议名称后面都有[S.l.: s.n]乱码，请问如何解决？谢谢！

**Comment by YuanshengZhao** [comment]
参见 https://github.com/stone-zeng/fduthesis/issues/113
