### ISSUE TITLE
如何避免标点符号处换行？

### ISSUE THREAD

**Issue by sliang11** [stone-zeng/fduthesis#122]
Miktex 2.9，编译后有在句尾的标点符号处换行的现象，请问如何解决？

**Comment by stone-zeng** [comment]
给个例子？麻烦给一下**完整的**代码和截图。

**Comment by sliang11** [comment]
> 给个例子？麻烦给一下**完整的**代码和截图。

请问有私有的联系方式吗？毕业论文不方便公开代码和截图。

**Comment by stone-zeng** [comment]
<xdzeng96@gmail.com>

当然，建议你用其他文本代替实际内容，只需要展示出问题就行了。

**Comment by sliang11** [comment]
> [xdzeng96@gmail.com](mailto:xdzeng96@gmail.com)
> 
> 当然，建议你用其他文本代替实际内容，只需要展示出问题就行了。

您好，已经私信您了，因为出现问题的地方比较多，而且担心只是复刻了的话不一定适用于原文，所以还是冒昧把原始的文件发给您了，麻烦您指教。

**Comment by sliang11** [comment]
已经和版主私信解决了，非常感谢！在这里贴一下解决方案，供有类似问题的朋友参考。我的运行环境是Win10，Miktex 2.9，WinEdt 10. 编译方式是LuaLatex -> Bibtex -> LuaLatex -> LuaLatex，经版主指教把LuaLatex换成了XeLatex，问题解决！
