### ISSUE TITLE
参考文献显示异常符号

### ISSUE THREAD

**Issue by QiXi9409** [stone-zeng/fduthesis#123]
MiKTeX 2.9，在64位Win10下，引用下面这个：

```bibtex
@article{陈伟伟2015中国心血管病报告,
	title={中国心血管病报告 2014},
	author={陈伟伟 and 高润霖 and 刘力生 and 朱曼璐 and 王文 and 王拥军 and 吴兆苏 and 李惠君 and 郑哲 and 蒋立新 and others},
	journal={中国循环杂志},
	volume={30},
	number={007},
	pages={617--622},
	year={2015}
}
```

![image](https://user-images.githubusercontent.com/32640472/75625944-da90d600-5bfd-11ea-996b-2d6fa4905288.png)

请问如何解决？

**Comment by zepinglee** [comment]
用 utf-8 编码？

**Comment by QiXi9409** [comment]
> 用 utf-8 编码？

查了一遍，编码都是utf-8

**Comment by zepinglee** [comment]
> > 用 utf-8 编码？
> 
> 查了一遍，编码都是utf-8

你是用的哪个 bib 的后端？bibtex 还是 biblatex？

**Comment by QiXi9409** [comment]
> > > 用 utf-8 编码？
> > 
> > 
> > 查了一遍，编码都是utf-8
> 
> 你是用的哪个 bib 的后端？bibtex 还是 biblatex？

xelatex + bibtex

**Comment by zepinglee** [comment]
> > > > 用 utf-8 编码？
> > > 
> > > 
> > > 查了一遍，编码都是utf-8
> > 
> > 
> > 你是用的哪个 bib 的后端？bibtex 还是 biblatex？
> 
> xelatex + bibtex

不可能呀，这个 bst 是经过很多测试的，看一下你生成的 bbl 文件相应的部分？

**Comment by stone-zeng** [comment]
可能的话，整个文件夹打包一下（可以复制一下删掉无关内容，但要包括 `.tex`、`.bib`、`.bbl`、`.log` 等这些文件）上传这边或者发我邮箱 <xdzeng96@gmail.com>。
