### ISSUE TITLE
论文格式设置

### ISSUE THREAD

**Issue by Bae984** [stone-zeng/fduthesis#124]
毕业论文的格式要求字体：宋体、字号：小四号、字符间距：标准、行距：20磅
宋体是不是每个字体都有呢？使用默认即可？
再确认下font-size=-4是不是指小四 而=5是指5号是吗？
最后就是模板默认的行距是不是20磅 如果不是的话 怎么设置行距呢 
期待回复 再爆肝一波就可以提交论文啦\(^o^)/~

**Comment by stone-zeng** [comment]
默认就是配置好的，所有东西都调好了，不需要再手动干预。

**Comment by Bae984** [comment]
我导就说我的字体偏小 我看了下默认是font-size=5 就有点迷 font-size要咋设置

**Comment by stone-zeng** [comment]
那就设 `font-size=-4`。

**Comment by Bae984** [comment]
行
