### ISSUE TITLE
fudantheis.cls文件缺失

### ISSUE THREAD

**Issue by SHUSHENGQIGUI** [stone-zeng/fduthesis#125]
作者您好，fudantheis.cls文件缺失，请问在何处下载？

**Comment by stone-zeng** [comment]
如果是从 github 打包下载 / git clone 的话，请根据系统运行 `install-unix.sh` 或者 `install-win.bat` 脚本，所需文件都会在生成的 `thesis` 文件夹中；如果是在 overleaf 或者直接用 texlive 自带的 `fduthesis`，则按照文档说明直接写即可。

另外，相应的 cls 文件是 `fduthesis(-en).cls` 而不是 `fudantheis.cls`。
