### ISSUE TITLE
去除独创性声明和学位论文使用授权声明

### ISSUE THREAD

**Issue by Bae984** [stone-zeng/fduthesis#126]
我刚刚淘宝查了下重，发现这玩意把我单篇查重率直接拉到了8.7%，我决定上传到系统的时候把这个部分暂时删除，有什么办法吗

**Comment by stone-zeng** [comment]
```tex
\documentclass{fduthesis}
\fdusetup{style/auto-make-cover=false}

\begin{document}

% 保留封面、指导小组
\begin{titlepage}
  \makecoveri
  \makecoverii
\end{titlepage}

\frontmatter

\tableofcontents

\mainmatter

\chapter{Test}

Hello

\backmatter

% 注释掉声明页
% \makecoveriii

\end{document}
```

**Comment by zepinglee** [comment]
我建议把“独创性声明”从 `\maketitle` 里拆出来

**Comment by stone-zeng** [comment]
@zepinglee 这些东西默认是直接 hook 进 `\begin(end){document}` 的，而且事实上模板也没提供 `\maketitle` 这个命令。

**Comment by Bae984** [comment]
改了之后 格式出现了一丢丢问题 如图
<img width="301" alt="微信图片_20200307173044" src="https://user-images.githubusercontent.com/19869716/76140846-735da080-6099-11ea-8a5c-ca074eceb527.png">

**Comment by stone-zeng** [comment]
抱歉，漏了一个 `\newpage`：

```tex
\begin{titlepage}
  \makecoveri
  \newpage
  \makecoverii
\end{titlepage}
```

**Comment by Bae984** [comment]
好啦，谢谢！！！
