### ISSUE TITLE
如何删掉页眉？

### ISSUE THREAD

**Issue by XinshuZheng** [stone-zeng/fduthesis#128]
在小四字体的情况下， 为了符合图书馆没有空白页的要求，我不得不采用oneside模式，
oneside模式下，每一页的页眉形式为 章名+节名
当章名与节名过于长的时候，会出现重合....
有没有可能把页眉统统删了？

**Comment by stone-zeng** [comment]
去掉页眉可以在导言区加上 `\pagestyle{plain}`。但实际上更好的办法是用可选参数作为章节的短名字：

```tex
\chapter[章短名]{一个很长很长很长很长很长很长很长很长很长很长很长很长的章}
\section[节短名]{一个很长很长很长很长很长很长很长很长很长很长很长很长很长的节}
```

**Comment by yiminz** [comment]
曾哥
oneside 模式可以不可以页眉是~章的名称~然后居中。
然后twoside模式。很完美。。。
