### ISSUE TITLE
改变目录章节的编号为中文（文科）

### ISSUE THREAD

**Issue by yiminz** [stone-zeng/fduthesis#129]
在写学位论文的时候，文科专业的章节排序编号与理工科专业的要求不一样，一般是这样的要求：
各层次标题一律用汉字., 一、二、三、

老哥，求教如何修改章节的序号为中文。。。。

网上百度结果：
[ctex 宏包]1为该问题提供了解决方案。可参照下面代码进行修改：

%\CTEXsetup[name={第,章},number={\chinese{chapter}}]{chapter}
\CTEXsetup[name={第,节},number={\chinese{section}}]{section}
\CTEXsetup[number={\chinese{subsection}}]{subsection}
\CTEXsetup[name={（,）},number={\chinese{subsubsection}}]{subsubsection}

但是您的这个模板没有基于Ctex的。。。

求教如何修改章节的序号为中文。。。。

**Comment by stone-zeng** [comment]
你百度到的东西比较陈旧了，`ctex` 宏集已经弃用了这种语法……

给的这一堆代码等价于：

```tex
\ctexset{
  section    = {name={第,节}, number=\chinese{section}},
  subsection = {number=\chinese{subsection}},
  subsubsection = {name={（,）}, number=\chinese{subsubsection}}
}
```

完整示例：

```tex
\documentclass{fduthesis}

% 默认 \subsubsection 不编号
\setcounter{secnumdepth}{3}

% \ctexset 里面缩进、空格基本随意，唯不可以空行
\ctexset{
  section = {
    name   = {第,节},
    number = \chinese{section}
  },
  subsection = {
    number = \chinese{subsection}
  },
  subsubsection = {
    name      = {（,）},
    number    = \chinese{subsubsection},
    aftername = {}  % （一）后面空格太多，不好看
  }
}

\begin{document}
\tableofcontents
\chapter{测试章}
\section{测试节}
\subsection{测试小节}
\subsubsection{测试小小节}
\end{document}
```
