### ISSUE TITLE
关于增加致谢，学术发表成果的问题

### ISSUE THREAD

**Issue by jason117041** [stone-zeng/fduthesis#131]
我是其他大学的，想把论文原创声明移动到封面下一页，并且把指导小组成员移动到扉页，然后编译错误，不知怎么修改，另外还想增加致谢还有学术发表成果到最后部分，烦请大佬指点一下。

**Comment by shaonvxyz** [comment]
没有页码的页面在pdf编辑器里拖动一下页面就行了。致谢什么的在\backmatter后面加\chapter，不过学术成果列表的格式（行间距啥的，总不能按照正文来）得自己折腾了

**Comment by jason117041** [comment]
> 没有页码的页面在pdf编辑软件（mac的预览就行吧）里拖动一下页面就行了。致谢什么的在\backmatter后面加\chapter，不过学术成果列表的格式（行间距啥的，总不能按照正文来）得自己折腾了

谢谢大佬抽空回复，那请问论文原创声明怎么移动到扉页的下一页呢，还有可以把指导小组删了吗

**Comment by shaonvxyz** [comment]
> > 没有页码的页面在pdf编辑软件（mac的预览就行吧）里拖动一下页面就行了。致谢什么的在\backmatter后面加\chapter，不过学术成果列表的格式（行间距啥的，总不能按照正文来）得自己折腾了
> 
> 谢谢大佬抽空回复，那请问论文原创声明怎么移动到扉页的下一页呢，还有可以把指导小组删了吗

我不是模板作者啦（作者是我直系学弟嘿嘿），逃~页面删除、移动我是通过wps 的pdf编辑功能搞定的，反正目录里没有这些东西，直接删掉或者移动就行了。

**Comment by jason117041** [comment]
> > > 没有页码的页面在pdf编辑软件（mac的预览就行吧）里拖动一下页面就行了。致谢什么的在\backmatter后面加\chapter，不过学术成果列表的格式（行间距啥的，总不能按照正文来）得自己折腾了
> > 
> > 
> > 谢谢大佬抽空回复，那请问论文原创声明怎么移动到扉页的下一页呢，还有可以把指导小组删了吗
> 
> 我不是模板作者啦（作者是我直系学弟嘿嘿），逃~页面删除、移动我是通过wps 的pdf编辑功能搞定的，反正目录里没有这些东西，直接删掉或者移动就行了。

哈哈谢谢大佬及大佬学弟哈哈，那我用pdf编辑器试试

**Comment by shaonvxyz** [comment]
> > 没有页码的页面在pdf编辑软件（mac的预览就行吧）里拖动一下页面就行了。致谢什么的在\backmatter后面加\chapter，不过学术成果列表的格式（行间距啥的，总不能按照正文来）得自己折腾了
> 
> 谢谢大佬抽空回复，那请问论文原创声明怎么移动到扉页的下一页呢，还有可以把指导小组删了吗

既然你是其他高校的，可是在导言区里改一下auto-make-cover = false，这样封面、指导小组、声明页都不生成，然后你再把自己学校的封面啥的通过添加页面加回来

**Comment by jason117041** [comment]
> > > 没有页码的页面在pdf编辑软件（mac的预览就行吧）里拖动一下页面就行了。致谢什么的在\backmatter后面加\chapter，不过学术成果列表的格式（行间距啥的，总不能按照正文来）得自己折腾了
> > 
> > 
> > 谢谢大佬抽空回复，那请问论文原创声明怎么移动到扉页的下一页呢，还有可以把指导小组删了吗
> 
> 既然你是其他高校的，可是在导言区里改一下auto-make-cover = false，这样封面、指导小组、声明页都不生成，然后你再把自己学校的封面啥的通过添加页面加回来

添加页面是pdf编辑器里添加么

**Comment by stone-zeng** [comment]
（抱歉回复有点晚）

封面设计、布局的灵活性实际上很高，只是可能略有繁琐；致谢、学术发表成果在 #116 中已经提到过：

```tex
\documentclass{fduthesis}
\fdusetup{style/auto-make-cover=false}

\RenewDocumentCommand\makecoveriii{}{
  % 移除 \cleardoublepage
  \thispagestyle{empty}
  \UseInstance{fdu/cover}{cover-iii-default}
}

\AtBeginDocument{
  \begin{titlepage}
    \makecoveri    % 封面
    \newpage
    \makecoveriii  % 声明页
    \newpage
    \makecoverii   % 指导小组
  \end{titlepage}
}

\begin{document}

\frontmatter
\tableofcontents

\mainmatter
\chapter{测试}
\chapter{测试}

\backmatter
\chapter{学术发表成果}
\chapter{致谢}

\end{document}
```
