### ISSUE TITLE
几个问题亟待解决，望指点，谢谢！

### ISSUE THREAD

**Issue by hualitlc** [stone-zeng/fduthesis#132]
1. 参考文献中出现的“[S.l. : s.n.]”及“[出版地不详]”，如何去除？

2. 目录中的罗马字母如何更改成大写？

3. 如何不显示前面的论文封面、指导小组以及最后的原创声明，并且需要添加盲审封面、发表成果清单以及致谢。

谢谢各位！感谢！

**Comment by stone-zeng** [comment]
1. 国标要求，不需要删除，见 #113 
2. 在 `\frontmatter` 之后加上 `\pagenumbering{Roman}`
3. 见 #99、#105、#109、#126
