### ISSUE TITLE
关于封面有两个导师该怎么写

### ISSUE THREAD

**Issue by jason117041** [stone-zeng/fduthesis#134]
我想请教一下，封面我想写两个导师，请问是怎么添加呢？另外我想删了摘要的中图分类号，因为我们学校没有要求，我担心写错了。

**Comment by stone-zeng** [comment]
> 封面我想写两个导师

具体想要排版成什么样？直接写 `某某某\quad 教授\quad 某某某\quad 教授` 这样能不能满足要求？

> 另外我想删了摘要的中图分类号

#133（麻烦看一下回复好吗……

**Comment by jason117041** [comment]
> > 封面我想写两个导师
> 
> 具体想要排版成什么样？直接写 `某某某\quad 教授\quad 某某某\quad 教授` 这样能不能满足要求？
> 
> > 另外我想删了摘要的中图分类号
> 
> #133（麻烦看一下回复好吗……

不好意思，我才看到邮箱的回复，就那样写看看，等导师决定了，谢谢啦
