### ISSUE TITLE
请问如果选择 bib-backend = biblatex, 那应该修改对应的哪个.bst文件

### ISSUE THREAD

**Issue by hualitlc** [stone-zeng/fduthesis#135]

**Comment by stone-zeng** [comment]
使用 `biblatex` 之后就会用 [`biblatex-gb7714-2015` 包](https://ctan.org/pkg/biblatex-gb7714-2015)，同时不再使用 bibtex，也不再需要 .bst 文件。需要定制的话可以参考 [该宏包文档](http://mirrors.ctan.org/macros/latex/contrib/biblatex-contrib/biblatex-gb7714-2015/biblatex-gb7714-2015.pdf)，有问题也欢迎继续讨论。

**Comment by hualitlc** [comment]
> 使用 `biblatex` 之后就会用 [`biblatex-gb7714-2015` 包](https://ctan.org/pkg/biblatex-gb7714-2015)，同时不再使用 bibtex，也不再需要 .bst 文件。需要定制的话可以参考 [该宏包文档](http://mirrors.ctan.org/macros/latex/contrib/biblatex-contrib/biblatex-gb7714-2015/biblatex-gb7714-2015.pdf)，有问题也欢迎继续讨论。

感谢回复！目前使用下来，当我采用bibtex+numerical的方式时，发现文章并不是完全按照引用的先后顺序排序的。第一次出现引用三篇文献的位置处的编码是[3,8,11]，后面大部分又是按照引用的先后顺序排序的，不知道是什么原因，希望能够帮忙分析一下。

**Comment by zepinglee** [comment]
> 当我采用bibtex+numerical的方式时，发现文章并不是完全按照引用的先后顺序排序的。第一次出现引用三篇文献的位置处的编码是[3,8,11]，后面大部分又是按照引用的先后顺序排序的，不知道是什么原因，希望能够帮忙分析一下。

是不是在前面的 table of contents 或者 list of figures 里有引用？
