### ISSUE TITLE
脚注连续编号

### ISSUE THREAD

**Issue by georgejjj** [stone-zeng/fduthesis#139]
现在的脚注每页开始重新编号，是否能连续编号，或者按chapter重新编号？

**Comment by stone-zeng** [comment]
现在模板使用 `footmisc` 宏包 + `perpage` 选项来实现脚注每页重新编号，所以没有直接的办法修改。

迂回的办法是复制一下 `fduthesis.cls`（*nix 系统在 `/usr/local/texlive/2020/texmf-dist/tex/latex/fduthesis/` 目录中，Windows 类似）到你的工作目录，然后找到

```tex
\clist_map_inline:nn
  {
    { no-math           } { fontspec },
    { perpage           } { footmisc },
    { amsmath, thmmarks } { ntheorem }
  }
  { \PassOptionsToPackage #1 }
```

这样一段代码，删去或注释掉 `{ perpage           } { footmisc },` 这一行，可实现按章重新编号。如果需要全篇连续编号，要再在导言区加上

```tex
\counterwithout*{footnote}{chapter}
```
