### ISSUE TITLE
目录如果不想显示三级标题怎么弄呢

### ISSUE THREAD

**Issue by jason117041** [stone-zeng/fduthesis#144]
我用pdf编辑，然后发现删了第一页目录的三级标题后，排在第二页的目录不会自动跟着跑到前面来，如果修改latex模板会很麻烦么

**Comment by stone-zeng** [comment]
导言区添加：

```tex
\setcounter{tocdepth}{1}
```

![image](https://user-images.githubusercontent.com/18233088/83590169-b55a8d80-a587-11ea-815b-b9dd5ef3fe9a.png)
