### ISSUE TITLE
目录风格如何调整？

### ISSUE THREAD

**Issue by Jeff-Tian** [stone-zeng/fduthesis#148]
请问有没有比较方便的方式实现如下效果：

1. 第一行为“目录”本身，页码为I；
2. 罗马字大写；
3. 标题到页码的空白用……填充。

## 预期

![image](https://user-images.githubusercontent.com/3367820/88454702-e8444200-cea3-11ea-806d-05e1b7e41a16.png)

## 实际
![image](https://user-images.githubusercontent.com/3367820/88454770-5557d780-cea4-11ea-9f05-5bf3993de494.png)

谢谢！

**Comment by Jeff-Tian** [comment]
另外，目录生成后的颜色可以是黑色吗？

**Comment by Jeff-Tian** [comment]
又，\subsection 的内容可以沿用 section 和 chapter 的字体吗？不要变成楷体。

**Comment by stone-zeng** [comment]
在导言区（`\begin{document}` 之前）加入下列内容：

```tex
\makeatletter
\ExplSyntaxOn

% 将「目录」添加进目录
% https://github.com/stone-zeng/fduthesis/issues/117
\cs_set_eq:NN \__fdu_chapter_no_toc:V \__fdu_chapter:V

% 页码使用大写罗马数字
\ctex_patch_cmd:Nnn \frontmatter { roman } { Roman }

% 标题到页码的空白用……填充
% https://tex.stackexchange.com/a/101709
\ctex_patch_cmd:Nnn \l@chapter
  { \hfil }
  { \leaders\hbox{\normalfont$\m@th\mkern \@dotsep mu\hbox{.}\mkern \@dotsep mu$}\hfill }

% 关闭目录中的超链接（用黑色显示）
\hypersetup { linktoc=none }

% \subsection 不用楷体
\ctexset { subsection / tocline = { \CTEXnumberline {#1} #2 } }

\ExplSyntaxOff
\makeatother
```

**Comment by Aphroditefang** [comment]
![image](https://user-images.githubusercontent.com/34327524/175257696-3e4e833a-48a3-413b-8357-28ae38d51550.png)
您好，如果想要这样的目录呢？也就是目录和插图目录都不编号且不包含在目录当中

**Comment by Aphroditefang** [comment]
另外，单独去掉目录的页眉应该怎么做呢？感谢

**Comment by stone-zeng** [comment]
> ![image](https://user-images.githubusercontent.com/34327524/175257696-3e4e833a-48a3-413b-8357-28ae38d51550.png) 您好，如果想要这样的目录呢？也就是目录和插图目录都不编号且不包含在目录当中

请避免在已关闭的 issue 再提新的问题。
