### ISSUE TITLE
请教如何加入非 bibtex 类型的引用文献？

### ISSUE THREAD

**Issue by Jeff-Tian** [stone-zeng/fduthesis#149]
中国知网里的引用文献格式里，没有bibtex类型的导出。

![image](https://user-images.githubusercontent.com/3367820/88473596-b7224b00-cf51-11ea-8d91-dd3dde339cfe.png)

请教一下大神们是怎么转成bibtex的（非手动）？我看到有一个 issue https://github.com/stone-zeng/fduthesis/issues/127#issuecomment-648305163 给了一个临时解决方案，但是在导言区加好后，然后怎么操作呢？

请指点，谢谢了！

**Comment by Jeff-Tian** [comment]
目前也可通过谷歌学术搜索论文转换，但还是偏手动了，希望有更好的方案。

![image](https://user-images.githubusercontent.com/3367820/88473673-80990000-cf52-11ea-87e2-77e3b3bb8a35.png)

**Comment by stone-zeng** [comment]
并没有什么好办法从引文变成 bib 条目，自动的工具总是有的但效果可能不一定好。用 google scholar 应该已经是最简单的。实际上建议引用的时候检查一下相应的参考文献，即使是 google scholar 也经常会出现各种格式问题，包括但不限于人名写错、标点不当等。

**Comment by zepinglee** [comment]
可以用用 endnote 的格式导入 Zotero，再导出 bibtex
