### ISSUE TITLE
请问为什么我更新fduthesis后编译时总是报错：! Package fduthesis Error: Package "xunicode-addon" is too old.

### ISSUE THREAD

**Issue by Jeff-Tian** [stone-zeng/fduthesis#150]
现象如题，看了源代码有这个检测，但是我不明白为什么即使我 `tlmgr install xunicode-addon` 也不能解决问题，还请指点……

## 最小可重现tex: 

```
% !TeX encoding = UTF-8
\documentclass{fduthesis}

\begin{document}
\chapter{欢迎}
\section{Welcome to fduthesis!}
你好，\LaTeX{}！
\end{document}
```

## 重现步骤：

```
docker run --rm -it -v $(pwd):/work -w /work -e LC_ALL=C.UTF-8 jefftian/texlive-full:latest latexmk -lualatex --shell-escape -synctex=1 -interaction=nonstopmode -enable-write18 fduthesis.tex
```

不胜感激！

**Comment by stone-zeng** [comment]
docker 我不是很熟悉，你有更详细的信息吗？比如 TeX Live 版本之类的。

另外 dockerfile 有吗？在 <https://hub.docker.com/u/jefftian/> 似乎没看到。

**Comment by Jeff-Tian** [comment]
Docker可以忽略，就是方便重现。
我本地安装的最新版TexLive也是这样，版本是2020。
之前是好的，执行了tlmgr update ... 之后就报这个错了。

**Comment by Jeff-Tian** [comment]
我发现即使报了这个错误，PDF 还是正常生成了。目前优先级不高，如果能够消除这个错误那是更好了。

**Comment by stone-zeng** [comment]
这里看起来是和 `xunicode` 有关的一系列宏包有兼容性问题，先暂时不要用 `lualatex` 编译，换成 `xelatex` 应该可以。

**Comment by Jeff-Tian** [comment]
了解了，我用到了 plantuml 包，目前必须用 `lualatex` 编译。
