### ISSUE TITLE
请问如何让 Abstract 全部大写： ABSTRACT？

### ISSUE THREAD

**Issue by Jeff-Tian** [stone-zeng/fduthesis#152]
查到这个链接：https://www.ee.iitb.ac.in/~trivedi/LatexHelp/latexchangename.htm    ，   但是没用……

**Comment by stone-zeng** [comment]
导言区：

```tex
\ExplSyntaxOn
\tl_set:Nn \c__fdu_name_abstract_tl { ABSTRACT }
\ExplSyntaxOff
```

**Comment by Jeff-Tian** [comment]
这个让中文的“摘要”变成了"ABSTRACT"，但是英文的"Abstract" 没变，需求是只把英文的"Abstract" 变成"ABSTRACT"，还请大佬指点……

**Comment by stone-zeng** [comment]
呃我糊涂了……应该是修改 `\c__fdu_name_abstract_en_tl`。

**Comment by Jeff-Tian** [comment]
这个可以！感谢大神！！

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
