### ISSUE TITLE
mac引用会出现问题

### ISSUE THREAD

**Issue by gongel** [stone-zeng/fduthesis#154]
`    bib-backend = biblatex,
    bib-resource = {refs.bib},`

会出现[?]

提示：Package natbib Warning: Citation `*******' on page i undefined on input line *.

版本：TeX Live 2020 mac版

**Comment by gongel** [comment]
参考 #127 
over.

**Comment by stone-zeng** [comment]
- 现在 v0.7e 已经做了修改，但那个  issue 暂时还没关
- 看到你写了 `bib-backend = biblatex`，这样并不会调用 `natbib` 和 `gbt7714`，要不再检查一下？

**Comment by gongel** [comment]
bib-backend = bibtex也试过，是不行的。我的模板安装方式是 tlmgr install fduthesis
