### ISSUE TITLE
多行标题左对齐的方法

### ISSUE THREAD

**Issue by zqcawzs** [stone-zeng/fduthesis#157]
你好! 现在每章标题如果字数过多自动会将第二行居中对齐，请问下能否设置成为跟标题内容左对齐？
以前形式：第四章      一二三四五六
                             七八九
能否改成：第四章      一二三四五六
                                   七八九
谢谢！

**Comment by stone-zeng** [comment]
导言区加上

```tex
\ctexset{
  chapter = {
    hang         = true,
    titleformat += \raggedright
  }
}
```

<img width="780" alt="Screen Shot 2020-09-26 at 14 26 51" src="https://user-images.githubusercontent.com/18233088/94332063-558b6500-0004-11eb-9eea-28ed9a744a23.png">

**Comment by zqcawzs** [comment]
谢谢！
