### ISSUE TITLE
打不开gbt7717-unsrt

### ISSUE THREAD

**Issue by mkyos** [stone-zeng/fduthesis#160]
似乎没有这个文件。
<img width="616" alt="截屏2020-10-04 01 13 37" src="https://user-images.githubusercontent.com/72077265/94997604-e0f58f00-05de-11eb-99dd-457befb9cc22.png">

**Comment by stone-zeng** [comment]
请把模板更新到 v0.7e，或者参考 #127 修改。

**Comment by mkyos** [comment]
感谢！
