### ISSUE TITLE
请教以及具体的章节标题设置

### ISSUE THREAD

**Issue by Jeff-Tian** [stone-zeng/fduthesis#161]
尝试自己用 `ctexset{chpater/xxx}` 结果破坏了其他比如居中等样式，还求给个正确的（不影响其他样式）设置方式：

- 章chapter标题字体设置为小二号黑体字居中
- 节section标题字体大小设置为小三号

背景：通过设置正文字体为小四(`\fdusetup{
    style = {
        font-size = -4`)之后，chapter 和 section 过大不符合学院要求……

不胜感激！

**Comment by stone-zeng** [comment]
用 `+=` 覆盖原有的设置（其实只是定义了 `chapter/format+` 这样的选项而并非统一的语法，仅限 `ctex` 等包）：

```tex
\fdusetup{
  style/font-size=-4
}

\ctexset{
  chapter/format += \zihao{-2},
  section/format += \zihao{3}
}
```

**Comment by Jeff-Tian** [comment]
原来可以用+=，感谢大神！！！

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
