### ISSUE TITLE
参考文献的引文位置

### ISSUE THREAD

**Issue by Cakepoke** [stone-zeng/fduthesis#163]
你好，在咱们现有的模板中，我使用的参考文献是
bib-backend = bibtex
现在默认引文显示样式是上标形式，如
![20190627100524841](https://user-images.githubusercontent.com/55835028/97840369-d08c1d80-1d1e-11eb-8a36-5e9bf50ce897.png)
但是学科一般使用的是平齐格式（如上图），请问有办法修改吗？
@stone-zeng

**Comment by zepinglee** [comment]
`gbt7714` https://github.com/CTeX-org/gbt7714-bibtex-style/blob/b7848f3cc2280878a024d8dfaa9428ef654034f1/gbt7714.dtx#L477-L480 定义了 `\bibstyle@numbers`，然后就可以用 `\citestyle{numbers}` 将 citation 切换为 inline 的样式。

目前 `fduthesis` 似乎只调用了 `natbib`，没有 `gbt7714.sty`，所以还不能直接这么用。临时方案是使用 `\bibpunct{[}{]}{,}{n}{,}{,}` （其实就是 `\bibstyle@numbers` 的内容）设置。

建议将 `gbt7714.sty` 的代码整合到模板中，因为其中在 `natbib` 的基础上修正了 citation 中页码的位置，还修正了连续编号的引用（如「[2-3]」）的样式。

**Comment by Cakepoke** [comment]
好的。那么我暂时将
\bibpunct{[}{]}{,}{n}{,}{,}
放在正文.tex的
\begin{document}
后面，这样就可以了吧？

**Comment by zepinglee** [comment]
> 好的。那么我暂时将
> \bibpunct{[}{]}{,}{n}{,}{,}
> 放在正文.tex的
> \begin{document}
> 后面，这样就可以了吧？

对

**Comment by Cakepoke** [comment]
谢谢！

**Comment by stone-zeng** [comment]
后续考虑按照 @zepinglee 的评论修改，所以 reopen 了。
