### ISSUE TITLE
自定义类似“定理”的环境

### ISSUE THREAD

**Issue by Cakepoke** [stone-zeng/fduthesis#164]
在论文写作过程中涉及了大量“定理”“引理”等环境，其中涉及到“假设”环境，我注意到是模板里没有的。
想要自己定义一个新的环境变量assumption，它的字体、间距等样式跟theorem环境一模一样，只是计数、抬头不同。
我尝试在.cls里最后一段加上一句
![image](https://user-images.githubusercontent.com/55835028/98547950-e1ff9780-22d3-11eb-89b0-398aa80e33bc.png)
结果自然是报错了hh，但是pdf显示好像也显示出来了，格式对的，但没抬头。请问怎么能解决一下吗？ @stone-zeng

**Comment by stone-zeng** [comment]
请先阅读文档：

![image](https://user-images.githubusercontent.com/18233088/98569383-34997d80-22ed-11eb-86e0-57b30cf8684a.png)

直接在导言区加就行，不需要修改 `.cls`。

**Comment by Cakepoke** [comment]
实测有效！感谢！
