### ISSUE TITLE
附录标题与其在目录中的内容如何统一

### ISSUE THREAD

**Issue by zhuodashi** [stone-zeng/fduthesis#165]
您好，使用您的模板为我带来了很大方便，但有个小问题困扰了我很久。

我在写目录的时候，为了让附录按照A/B/C..  编号，使用代码：

\begin{appendices}
\titleformat{\chapter}[block]{\normalfont\Huge\bfseries}{附录~\Alph{chapter}}{1em}{\Huge}
\renewcommand\thefigure{\Alph{chapter}\arabic{figure}} 
\input{chaps/Appendix_V1.tex}
\end{appendices}

正文中的效果为：
![image](https://user-images.githubusercontent.com/46375229/103219979-113c9780-495a-11eb-9f9d-cc4c8deffacc.png)

但是在目录中，直接用\tableofcontents是这个效果：

![image](https://user-images.githubusercontent.com/46375229/103220301-eacb2c00-495a-11eb-9c92-cf34095666c8.png)

请问如何将目录中的“第一章”改成和正文内容一致的“附录A”呢？ 我本来想用\chapter*取消显示再用\addcontentsline手动添加，但是这样一来正文中的字母编号就没有了。请问有什么简便的解决办法吗？

如蒙相助，不胜感激！

**Comment by stone-zeng** [comment]
```tex
...

\appendix

\chapter{附录}

\backmatter

\chapter{此部分不编号}

...
```
