### ISSUE TITLE
附录部分的图表编号

### ISSUE THREAD

**Issue by stone-zeng** [stone-zeng/fduthesis#166]
https://github.com/stone-zeng/fduthesis/blob/6c32f74f79618157c5f071d1773ef29f46f6daef/source/fduthesis.dtx#L4403-L4412

这导致附录中的图表编号有误，不是 `A-1` 而是 `1-1`。

**Comment by stone-zeng** [comment]
临时的 work around 是：

```tex
\appendix

\renewcommand{\thefigure}{\Alph{chapter}-\arabic{figure}}
\renewcommand{\thetable}{\Alph{chapter}-\arabic{table}}

\chapter{附录}

...

% \appendix 要在 \backmatter 之前
\backmatter
```

**Comment by zepinglee** [comment]
咋不用 `\thechapter`？

**Comment by stone-zeng** [comment]
> 咋不用 `\thechapter`？

我好像又智障了……
