### ISSUE TITLE
每页的行数与字号问题

### ISSUE THREAD

**Issue by Cakepoke** [stone-zeng/fduthesis#168]
你好，我们模板提供了font-size = -4/5两种选项，一般来说是够用了。
我采用-4（是小四字号对吧），不算公式、标题等占行的，一页满满是35行，每行35个字（当然如果是5号字体那一行40个字就更多了）。但是我参考了一下学院过往两年的论文，绝大多数人的一页是29行。这样35×80 = 29×97，也就是同样的内容咱们的模板只有80页，他们的模板97页……
所以请问，我们的模板有没有什么办法，可以更改一下每页的行数呢？暂未在setup选项中找到。

**Comment by tanukihee** [comment]
https://github.com/stone-zeng/fduthesis/blob/6c32f74f79618157c5f071d1773ef29f46f6daef/source/fduthesis.dtx#L3012-L3025

**Comment by stone-zeng** [comment]
导言区加上

```tex
% 调节行距
\linespread{1.56}\selectfont
% 调节上下页边距
\geometry{vmargin=3.5cm}
```

具体数字可根据情况调整。
