### ISSUE TITLE
在本地用TexStudio无法编译出参考文献

### ISSUE THREAD

**Issue by plong511** [stone-zeng/fduthesis#169]
如题，我在本地用TexStudio怎么都无法正常编译出参考文献（全部显示？？？），下载的文件包里似乎不包含bst或bbl文件。请问该如何解决这一问题？

**Comment by zepinglee** [comment]
TeX Live 版本？
fduthesis 版本？
bibtex 还是 biblatex？

**Comment by tanukihee** [comment]
编译命令？
`\printbibliography`？

**Comment by plong511** [comment]
> TeX Live 版本？
> fduthesis 版本？
> bibtex 还是 biblatex？

TexLive 2019, fduthesis是2020/08/30 v0.7e，bibtex和biblatex都试过了。是不是少了什么文件？

**Comment by plong511** [comment]
> 编译命令？
> `\printbibliography`？

没错，就是直接从这里下载的文件包，直接编译示例也是显示不了参考文献的

**Comment by tanukihee** [comment]
请用 TeXLive2020
>**从 v2.0 版本开始（2020-03-04），用户必须在文档中使用 `\biblilographystyle` 命令选择参考文献样式， 如 gbt7714-numerical 或 gbt7714-author-year。 在早期的版本中，选择文献样式的方法是将 numbers 或 super 等参数传递给 gbt7714， 而不能使用 `\bibliographystyle`。 这跟标准的 LaTeX 接口不一致，所以将被弃用。**

摘自 [gbt7714](https://github.com/CTeX-org/gbt7714-bibtex-style)

**Comment by tanukihee** [comment]
overleaf 2019 无法复现

**Comment by zepinglee** [comment]
> > 编译命令？
> > `\printbibliography`？
> 
> 没错，就是直接从这里下载的文件包，直接编译示例也是显示不了参考文献的

报了什么错误或警告？

**Comment by stone-zeng** [comment]
提问请给出完整的信息，包括编译方式、日志文件、截图等。

**Comment by plong511** [comment]
> 提问请给出完整的信息，包括编译方式、日志文件、截图等。

就是原封不动地直接编译下载到的文件包，也没办法显示参考文献。Xelatex、Bibtex
![截图](https://user-images.githubusercontent.com/65933059/107848516-f69d7f80-6e2e-11eb-99ce-bb59e588a419.jpg)

**Comment by plong511** [comment]
> 提问请给出完整的信息，包括编译方式、日志文件、截图等。

花了一下午升级成了Texlive 2020也还是不行。不知道上面那样的截图行不行，如果还需要别的信息请说。

**Comment by stone-zeng** [comment]
用 IDE 的话请描述清楚具体用来什么方法（或者说点了哪些按钮）来编译。我这里先用「工具 > 命令 > XeLaTeX」编译一遍，再用「工具 > 命令 > BibTeX」编译一遍，再用「工具 > 命令 > XeLaTeX」编译两遍，可以得到需要的结果，也可以配置之后用 latexmk 或者 TeXStudio 提供的构建功能来编译。

**Comment by plong511** [comment]
> 用 IDE 的话请描述清楚具体用来什么方法（或者说点了哪些按钮）来编译。我这里先用「工具 > 命令 > XeLaTeX」编译一遍，再用「工具 > 命令 > BibTeX」编译一遍，再用「工具 > 命令 > XeLaTeX」编译两遍，可以得到需要的结果，也可以配置之后用 latexmk 或者 TeXStudio 提供的构建功能来编译。

现在终于出来了，谢谢
