### ISSUE TITLE
aux文件自动清除从而导致Bibtex无法编译

### ISSUE THREAD

**Issue by YYShi12** [stone-zeng/fduthesis#170]
在本地使用Tex Live编译：先是使用XeLatex编译，产生了相关的aux文件，然后用Bibtex编译，此时出现aux文件自动清除的现象，导致Bibtex无法打开aux文件。

这应该怎么解决？

**Comment by zepinglee** [comment]
建议给出报错信息

**Comment by YYShi12** [comment]
我首先用xelatex编译，会产生aux文件，但当我继续用bibtex编译时，aux文件都被自动清除了，然后出现提示信息“I couldn't open file name `fduthesis-template.aux' ”。

请问这是什么问题？

**Comment by tanukihee** [comment]
不用 IDE，用命令行

**Comment by YYShi12** [comment]
谢谢，问题已解决：
      用命令行可以实现参考文献的编译。
      依次执行一下命令：

xelatex fduthesis-template.tex
biblatex fduthesis-template
xelatex fduthesis-template
xelatex fduthesis-template
