### ISSUE TITLE
关键词分隔符修改

### ISSUE THREAD

**Issue by Lunaticf** [stone-zeng/fduthesis#171]
关键词分隔符默认用逗号分隔显示分号，请问如何用逗号分隔

**Comment by tanukihee** [comment]
https://github.com/stone-zeng/fduthesis/blob/6c32f74f79618157c5f071d1773ef29f46f6daef/source/fduthesis.dtx#L5348-L5372

修改 `\@@_keywords:nNn` 的第三个参数

**Comment by Lunaticf** [comment]
> https://github.com/stone-zeng/fduthesis/blob/6c32f74f79618157c5f071d1773ef29f46f6daef/source/fduthesis.dtx#L5348-L5372
> 
> 修改 `\@@_keywords:nNn` 的第三个参数

`\@@_keywords:nNn
      { \sffamily \c_@@_name_keywords_tl \c_@@_fwid_colon_tl }
      \l_@@_info_keywords_clist { \c_@@_fwid_comma_tl }`

改完好像没起效果....

**Comment by tanukihee** [comment]
修改 dtx 后有无重新生成 cls？

**Comment by Lunaticf** [comment]
> > 改完好像没起效果....
> 
> 修改 .dtx 后需要重新执行 install 脚本生成 .cls

抱歉可以了！我使用的TexLive，因为之前修改dtx编译会即时生效，以为TexLive会自动重新编译。自己手动命令行生成cls就行了，谢谢~

**Comment by stone-zeng** [comment]
其实在导言区用 `\cs_renew_protected:Npn` 直接修改原命令会更方便一点的。

**Comment by Iam5B** [comment]
我总结一下修改源文件直接本地编译的流程吧（请确保你能从命令行执行xetex命令）

首先找到fduthesis/source/fduthesis.dtx这个文件，打开以后找到 Lunaticf 指出的那段代码，中文的分隔符号是靠5356行的semicolon单词控制的，改成comma就可以换成逗号，改完保存。

随后按照上面说的执行install脚本，生成出来的thesis文件夹里的除了.bib、.tex、.pdf以外的文件一股脑拷贝到你的论文目录下，然后重新开始编译即可（当然我每次重新编译论文前还会把.aux文件删了）

巨佬请无视

**Comment by sikouhjw** [comment]
还是建议不要修改源文件，而是在导言区修改 https://github.com/stone-zeng/fduthesis/issues/216
