### ISSUE TITLE
参考文献的条目之间的间距能缩小吗？

### ISSUE THREAD

**Issue by Miles-Ma** [stone-zeng/fduthesis#173]
谢谢大佬的工作。目前的间距有点大，想改紧凑点。

**Comment by tanukihee** [comment]
调整 `\bibsep`

**Comment by Miles-Ma** [comment]
谢谢你，解决了。

**Comment by lonven** [comment]
> \bibsep
您好，请问这个命令具体是在哪个文件使用，以及怎么用呀？谢谢！

**Comment by lonven** [comment]
> 调整 `\bibsep`

我试着在 \begin{document}之前加入了 \setlength{\bibsep}{20pt}，但是没有起作用。审核老师要求参考文献和正文行距相同。。

**Comment by lonven** [comment]
> > 调整 `\bibsep`
> 
> 我试着在 \begin{document}之前加入了 \setlength{\bibsep}{20pt}，但是没有起作用。审核老师要求参考文献和正文行距相同。。

已解决

**Comment by chengyj97** [comment]
> > > 调整 `\bibsep`
> > 
> > 
> > 我试着在 \begin{document}之前加入了 \setlength{\bibsep}{20pt}，但是没有起作用。审核老师要求参考文献和正文行距相同。。
> 
> 已解决

你好 请问是怎么解决的呀？谢谢！

**Comment by lonven** [comment]
> > > > 调整 `\bibsep`
> > > 
> > > 
> > > 我试着在 \begin{document}之前加入了 \setlength{\bibsep}{20pt}，但是没有起作用。审核老师要求参考文献和正文行距相同。。
> > 
> > 
> > 已解决
> 
> 你好 请问是怎么解决的呀？谢谢！

 \begin{document}之后 加入\setlength{\bibsep}{0.5ex} 但是不保证和正文行距一致..只是看起来一致

**Comment by chengyj97** [comment]
> > > > > 调整 `\bibsep`
> > > > 
> > > > 
> > > > 我试着在 \begin{document}之前加入了 \setlength{\bibsep}{20pt}，但是没有起作用。审核老师要求参考文献和正文行距相同。。
> > > 
> > > 
> > > 已解决
> > 
> > 
> > 你好 请问是怎么解决的呀？谢谢！
> 
> \begin{document}之后 加入\setlength{\bibsep}{0.5ex} 但是不保证和正文行距一致..只是看起来一致

感谢！！

**Comment by zepinglee** [comment]
> \begin{document}之后 加入\setlength{\bibsep}{0.5ex} 但是不保证和正文行距一致..只是看起来一致

`\bibsep` 控制的是两条文献之间额外加的空隙，不是每条文献内部相邻两行文字之间的行距。

在 `\printbibliography` 前 `\setlength{\bibsep}{0pt}` 就是严格跟正文一致了。
