### ISSUE TITLE
关键字 更改为关键词

### ISSUE THREAD

**Issue by lonven** [stone-zeng/fduthesis#175]
您好，打扰了。学院最近给了个论文格式要点文件，在摘要模块，文件里面是一直用的是“关键词”，而模板里用的是“关键字”。请问这个可以修改吗？

**Comment by tanukihee** [comment]
在 cls 里搜索`关键字`，改成`关键词`

**Comment by xnuohz** [comment]
就这三个字加粗还是所有的关键词都需要？

**Comment by zhenghaoz** [comment]
> 在 cls 里搜索`关键字`，改成`关键词`

感谢解答哈，但是`关键字`似乎在`fduthesis.def`

**Comment by lonven** [comment]
> 就这三个字加粗还是所有的关键词都需要？

不太清楚，感觉有歧义，我已经发邮件给教学办了，如果有消息再告诉你

**Comment by lonven** [comment]
> 在 cls 里搜索`关键字`，改成`关键词`

万分感谢

**Comment by tanukihee** [comment]
> 感谢解答哈，但是`关键字`似乎在`fduthesis.def`

😂😂，感谢指正

**Comment by xnuohz** [comment]
> > 就这三个字加粗还是所有的关键词都需要？
> 
> 不太清楚，感觉有歧义，我已经发邮件给教学办了，如果有消息再告诉你

谢谢

**Comment by lonven** [comment]
![image](https://user-images.githubusercontent.com/26090889/108817537-fea9ac00-75f2-11eb-9f19-9c80382793d7.png)
老师回复了邮件，大家可看上图～

**Comment by lonven** [comment]
> > > 就这三个字加粗还是所有的关键词都需要？
> > 
> > 
> > 不太清楚，感觉有歧义，我已经发邮件给教学办了，如果有消息再告诉你
> 
> 谢谢

老师回复了邮件，参考我上一条的回复奥

**Comment by stone-zeng** [comment]
> 学院最近给了个论文格式要点文件

方便的话，可以上传一下这个文件吗？或者发邮件给我也行。我只有学校统一的论文格式，有其他院系的说明的话也可以完善模板。

**Comment by lonven** [comment]
> > 学院最近给了个论文格式要点文件
> 
> 方便的话，可以上传一下这个文件吗？或者发邮件给我也行。我只有学校统一的论文格式，有其他院系的说明的话也可以完善模板。
[复旦大学计算机科学技术学院研究生学位论文格式评审要点.pdf](https://github.com/stone-zeng/fduthesis/files/6029286/default.pdf)
这里，请查收～（谢谢你的模板）
