### ISSUE TITLE
模板默认行距的问题

### ISSUE THREAD

**Issue by lonven** [stone-zeng/fduthesis#177]
打扰了～请问，模板默认的行距是多大呀，学院要求的是20磅，如果要改成20磅应该怎么修改呢？

**Comment by stone-zeng** [comment]
目前设置的值就是 20pt（「磅」是 pt 的微软式翻译）：

https://github.com/stone-zeng/fduthesis/blob/6c32f74f79618157c5f071d1773ef29f46f6daef/source/fduthesis.dtx#L6014-L6025

**Comment by lonven** [comment]
> 目前设置的值就是 20pt（「磅」是 pt 的微软式翻译）：
> 
> https://github.com/stone-zeng/fduthesis/blob/6c32f74f79618157c5f071d1773ef29f46f6daef/source/fduthesis.dtx#L6014-L6025

谢谢！
