### ISSUE TITLE
封面学位类型字体加粗

### ISSUE THREAD

**Issue by SirCats** [stone-zeng/fduthesis#179]
请问如何把封面学位类型字体加粗，比如(专业学位)四个字？

**Comment by stone-zeng** [comment]
导言区加上

```tex
\EditInstance{fdu/cover}{cover-i-default}{degree/format=\bfseries\zihao{4}}
```

封面绝大多数部件都允许调节，参考：

https://github.com/stone-zeng/fduthesis/blob/6c32f74f79618157c5f071d1773ef29f46f6daef/source/fduthesis.dtx#L5127-L5159

**Comment by SirCats** [comment]
好滴，谢谢~
