### ISSUE TITLE
图表和段落的间距怎么调整~

### ISSUE THREAD

**Issue by Lunaticf** [stone-zeng/fduthesis#182]
图表的标题和图表的间距也过大，图表和下方文字的间距也有点大，谢谢

**Comment by stone-zeng** [comment]
浮动体（即 `figure`、`table` 环境包围的图表）标题和浮动体的间距由

- `\abovecaptionskip`
- `\belowcaptionskip`

控制，浮动体和文字、浮动体之间的间距由

- `\textfloatsep`
- `\floatsep`
- `\intextsep`

控制，具体参考：<https://tex.stackexchange.com/q/26521>。
