### ISSUE TITLE
页眉的问题

### ISSUE THREAD

**Issue by plong511** [stone-zeng/fduthesis#187]
[《复旦大学经济学院博士、硕士研究生学位论文撰写规范》（2018年6月修订终版）(1).docx](https://github.com/stone-zeng/fduthesis/files/6097187/2018.6.1.docx)

如经院的要求所示，页眉要求左端为论文题目，右端为章题目。而现在的模板，左端为章题目，右端为小节题目。请问该如何修改？

另外，目录部分的页码应该是I II III IV，而现在的模板是i ii iii iv，请问该如何修改？

**Comment by stone-zeng** [comment]
见 #172。
