### ISSUE TITLE
mac下英文字体问题 - 乱码

### ISSUE THREAD

**Issue by ruizewang** [stone-zeng/fduthesis#190]
mac下用模板默认字体（times）导出pdf，复制出的英文字符为乱码（用acrobat转成word会好些，但是有的字也会出现乱码），复制出的中文字符正常（字体选的fandol）。

复制英文字符有如下乱码：
􀁉􀁒􀁕 􀁗􀁈􀁖􀁗 􀁉􀁒􀁕 􀁗􀁈􀁖􀁗 􀁉􀁒􀁕 􀁗􀁈􀁖􀁗􀁉􀁒􀁕 􀁗􀁈􀁖􀁗 􀁉􀁒􀁕 􀁗􀁈􀁖􀁗 􀁉􀁒􀁕 􀁗􀁈􀁖􀁗 􀁉􀁒􀁕 􀁗􀁈􀁖􀁗􀁉􀁒􀁕 􀁗􀁈􀁖􀁗 􀁉􀁒􀁕 􀁗􀁈􀁖􀁗 􀁉􀁒􀁕 􀁗􀁈􀁖􀁗􀁉􀁒􀁕
􀁗􀁈􀁖􀁗 􀁉􀁒􀁕 􀁗􀁈􀁖􀁗 􀁉􀁒􀁕 􀁗􀁈􀁖􀁗􀁉􀁒􀁕 􀁗􀁈􀁖􀁗 􀁉􀁒􀁕 􀁗􀁈􀁖􀁗􀀑 􀁉􀁒􀁕 􀁗􀁈􀁖􀁗􀁉􀁒􀁕 􀁗􀁈􀁖􀁗􀁉􀁒􀁕 􀁗􀁈􀁖􀁗􀁉􀁒􀁕 􀁗􀁈􀁖􀁗􀁉􀁒􀁕 􀁗􀁈􀁖􀁗􀁉􀁒􀁕 􀁗􀁈􀁖􀁗􀁉􀁒􀁕 􀁗􀁈􀁖􀁗􀁉􀁒􀁕

转成word后效果如下：
<img width="1158" alt="lm2" src="https://user-images.githubusercontent.com/8149167/110725750-0ef89280-8253-11eb-85d6-a1dfdb598222.png">

使用 `times` 和 `times*` 进行了测试，复制英文字符均会乱码。但是用 `times*` 的时候，pdf转成word后好像基本不会出现乱码。我担心之后查重上交pdf版本时，会造成查重系统识别英文时也是乱码。不知道如何较好解决。

使用 `times*` 字体导出的pdf
[times*.pdf](https://github.com/stone-zeng/fduthesis/files/6120010/times.pdf)

使用 `times` 字体导出的pdf
[times.pdf](https://github.com/stone-zeng/fduthesis/files/6120009/times.pdf)

**Comment by stone-zeng** [comment]
复制乱码的问题在模板层面没办法解决，但根据反馈并没有多少同学遇到了查重的问题，所以请暂时放心。

**Comment by ruizewang** [comment]
> 复制乱码的问题在模板层面没办法解决，但根据反馈并没有多少同学遇到了查重的问题，所以请暂时放心。

实验了一下其他同学 用overleaf或者在windows下导出的pdf均无此问题。所以感觉是mac下的字体有什么问题，和模板或许存在兼容性问题。

**Comment by ruizewang** [comment]
问题已解决，用`\setmonofont{}`试了一遍，发现mac上没有安装XITS字体，安装后即可，可从[这里](https://github.com/alif-type/xits/downloads)下载字体。
