### ISSUE TITLE
页眉的论文短标题设置

### ISSUE THREAD

**Issue by plong511** [stone-zeng/fduthesis#191]
是否有办法设置，在页眉的显示的是论文的短标题（running title）？
格式要求的是左侧页眉显示论文题目，右侧页眉显示章标题。左侧的论文题目最好是短标题，与封面上的标题不一样。

**Comment by stone-zeng** [comment]
导言区加上：

```tex
\makeatletter
\let\ps@plain\ps@fancy
\fancyhead[L]{\fdu@kai\zihao{-5}论文短标题}
\fancyhead[R]{\fdu@kai\zihao{-5}\leftmark}
\makeatother
```

不想用楷体的话就把 `\fdu@kai` 删掉。

**Comment by plong511** [comment]
> 导言区加上：
> 
> ```
> \makeatletter
> \let\ps@plain\ps@fancy
> \fancyhead[L]{\fdu@kai\zihao{-5}论文短标题}
> \fancyhead[R]{\fdu@kai\zihao{-5}\leftmark}
> \makeatother
> ```
> 
> 不想用楷体的话就把 `\fdu@kai` 删掉。

搞定，多谢！
