### ISSUE TITLE
页眉设置的问题

### ISSUE THREAD

**Issue by plong511** [stone-zeng/fduthesis#193]
发现一件很神奇的事情。
在overleaf编译时，页眉显示的章标题是 第X章 XXX， 而在本地的texstudio编译时，页眉显示的是Chapter X. XXX。
这可能是什么原因？有办法调成中文的吗？

**Comment by stone-zeng** [comment]
#174

**Comment by plong511** [comment]
> #174

这个问题有没有比较浅显易懂的解决方法。。。我实在是看不懂这些贴子说的

**Comment by tanukihee** [comment]
简单易懂解决方法：等

今明两天 ctex 2.5.6 就应该会推送了
