### ISSUE TITLE
参考文献文中引用问题

### ISSUE THREAD

**Issue by plong511** [stone-zeng/fduthesis#194]
我使用的是gb7714-2015，biblatex。
现在发现一个诡异的问题，部分作者在文中的引用会带上名的缩写，正确的应该是只有姓的。
![问题](https://user-images.githubusercontent.com/65933059/111142891-253e7f80-85c0-11eb-899e-20c4159a19ab.jpg)
比如这个，正确的写法应该是Bartel et al., 1999就可以的，前面的A. P. 不应该出现。类似的问题还有不少，但又不是所有地方都出现，目前我也没找到规律，什么时候会出现这个bug。
请问作者，是否见过这个问题？

**Comment by zepinglee** [comment]
这个应该是为了消歧义，你的文献列表中是不是还有另外一个 Bartel？

**Comment by hushidong** [comment]
是的，加上选项 uniquelist=false,uniquename=false就好了。

**Comment by hushidong** [comment]
不想改cls的话，在文档类命令前加上：
```
\PassOptionsToPackage{uniquelist=false,uniquename=false}{biblatex}
```
即可。

当然也可以改cls，在调用biblatex的位置加上。

**Comment by plong511** [comment]
问题已解决，就是楼上的原因

**Comment by zepinglee** [comment]
严格的写作还是应该区分开姓名的，比如 Chicago 就规定了很详细的消歧义方案。

国标规定得不够详细，但是有一条
<img width="710" alt="Screen Shot 2021-03-15 at 21 52 35" src="https://user-images.githubusercontent.com/12290822/111164181-c802f800-85d8-11eb-8770-372aa1b0b865.png">
表达的思想还是要区分开的。
