### ISSUE TITLE
参考文献引用的又一奇怪的要求

### ISSUE THREAD

**Issue by plong511** [stone-zeng/fduthesis#195]
各位不好意思我又有问题了，刚发现经院还有一个奇怪的格式要求没满足……
就是文中的引用，如果是两个作者的，应该是张三和李四（2020）或Zhang and Li (2020)这种格式的，而gb7714-2015是两个以上一律等或et al.
如果我改成chinese-erj的引用格式，两个作者倒是可以显示了，但变成了 张三，李四（2020）或 Zhang, Li (2020)这样，还是不对。
是否有办法调整一下？

**Comment by hushidong** [comment]
见：
```


\documentclass[twoside]{article}
\usepackage{ctex}
\usepackage[backend=biber,citestyle=gb7714-2015ay,bibstyle=gb7714-2015,mincitenames=1,maxcitenames=2]{biblatex}
\DefineBibliographyStrings{english}{
        andincite         = {and},
        andincitecn       = {和},
}

\usepackage[colorlinks]{hyperref}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@Article{duhamel,
Author = {Umarov, S. R. and Sa\u{\i}damatov, E. M.},
Title = {A generalization of Duhamel’s principle for differential equations of fractional order},
Journal = {Doklady Mathematics},
Volume = {75},
Number = {1},
Pages = {94-96},
DOI = {10.1134/S1064562407010267},
Year = {2007},
}

@ARTICLE{DUBAR2013--,
  author       = {DUBAR, K L.  AND MITCHELL, D A.},
  title        = {Revealing nature's synthetic potential through the study of ribosomal natural product biosynthesis},
  Journaltitle = {ACS chemical biology},
  DATE         = {2013},
  VOLUME       = {8},
  pages        = {473-487},
  url          = {http://pubs.acs.org/doi/pdfplus/10.1021/cb3005325},
  urldate      = {2013-10-16}
}

@ARTICLE{DUBAR2008--,
  author       = {DUBAR, K L.  AND MITCHELL, D A.},
  title        = {A study on online pharmaceutical operating situation and supervision mechanism},
  Journaltitle = {Shanghai food and drug information research},
  DATE         = {2008},
  number       = {1},
  pages        = {8-11},
}

@ARTICLE{关立哲2014--,
  author       = {关立哲 and 韩纪富 and 张晨延},
  title        = {科技期刊编辑审读中要注重比较思维的科学运用},
  Journaltitle = {编辑学报},
  DATE         = {2014},
  VOLUME       = {26},
  number       = {2},
  pages        = {144-146}
}

@ARTICLE{关立哲2005--,
  author       = {韩纪富 and 张晨延},
  title        = {从交易费用的角度谈如何构建药品流通的良性机制},
  Journaltitle = {中国物价},
  DATE         = {2005},
  number       = {8},
  pages        = {42-45},
}

\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}

正文\cite{关立哲2005--,关立哲2014--}\cite{DUBAR2008--,DUBAR2013--}\cite{duhamel}正文

%\printbibliography[env=numerical]
\printbibliography
    \end{document} 
```

结果为：
![图片](https://user-images.githubusercontent.com/20421795/111235866-856b0b00-862c-11eb-9d98-b12fbc581d87.png)

**Comment by plong511** [comment]
> 见：
> 
> ```
> 
> 
> \documentclass[twoside]{article}
> \usepackage{ctex}
> \usepackage[backend=biber,citestyle=gb7714-2015ay,bibstyle=gb7714-2015,mincitenames=1,maxcitenames=2]{biblatex}
> \DefineBibliographyStrings{english}{
>         andincite         = {and},
>         andincitecn       = {和},
> }
> 
> \usepackage[colorlinks]{hyperref}
> \usepackage{filecontents}
> \begin{filecontents}{\jobname.bib}
> @Article{duhamel,
> Author = {Umarov, S. R. and Sa\u{\i}damatov, E. M.},
> Title = {A generalization of Duhamel’s principle for differential equations of fractional order},
> Journal = {Doklady Mathematics},
> Volume = {75},
> Number = {1},
> Pages = {94-96},
> DOI = {10.1134/S1064562407010267},
> Year = {2007},
> }
> 
> @ARTICLE{DUBAR2013--,
>   author       = {DUBAR, K L.  AND MITCHELL, D A.},
>   title        = {Revealing nature's synthetic potential through the study of ribosomal natural product biosynthesis},
>   Journaltitle = {ACS chemical biology},
>   DATE         = {2013},
>   VOLUME       = {8},
>   pages        = {473-487},
>   url          = {http://pubs.acs.org/doi/pdfplus/10.1021/cb3005325},
>   urldate      = {2013-10-16}
> }
> 
> @ARTICLE{DUBAR2008--,
>   author       = {DUBAR, K L.  AND MITCHELL, D A.},
>   title        = {A study on online pharmaceutical operating situation and supervision mechanism},
>   Journaltitle = {Shanghai food and drug information research},
>   DATE         = {2008},
>   number       = {1},
>   pages        = {8-11},
> }
> 
> @ARTICLE{关立哲2014--,
>   author       = {关立哲 and 韩纪富 and 张晨延},
>   title        = {科技期刊编辑审读中要注重比较思维的科学运用},
>   Journaltitle = {编辑学报},
>   DATE         = {2014},
>   VOLUME       = {26},
>   number       = {2},
>   pages        = {144-146}
> }
> 
> @ARTICLE{关立哲2005--,
>   author       = {韩纪富 and 张晨延},
>   title        = {从交易费用的角度谈如何构建药品流通的良性机制},
>   Journaltitle = {中国物价},
>   DATE         = {2005},
>   number       = {8},
>   pages        = {42-45},
> }
> 
> \end{filecontents}
> 
> \addbibresource{\jobname.bib}
> 
> \begin{document}
> 
> 正文\cite{关立哲2005--,关立哲2014--}\cite{DUBAR2008--,DUBAR2013--}\cite{duhamel}正文
> 
> %\printbibliography[env=numerical]
> \printbibliography
>     \end{document} 
> ```
> 
> 结果为：
> ![图片](https://user-images.githubusercontent.com/20421795/111235933-a92e5100-862c-11eb-8d74-069d34c817cd.png)

能否告诉我需要输入哪些命令直接加在模板上吗？
我加了
\DefineBibliographyStrings{english}{
        andincite         = {and},
        andincitecn       = {和},
}
这一段在导言区，似乎不认

**Comment by hushidong** [comment]
放导言区，biblatex调用之后。我没细研究模板，不知道biblatex是什么时候调用的。

那么就这样处理：

```
\AtBeginDocument{
\DefineBibliographyStrings{english}{
andincite = {and},
andincitecn = {和},
}
}
```

**Comment by hushidong** [comment]
mincitenames=1,maxcitenames=2  这两个选项，也别忘了，也要传给biblatex

**Comment by plong511** [comment]
> mincitenames=1,maxcitenames=2 这两个选项，也别忘了，也要传给biblatex

这两个选项倒是顺利地加上去了，但现在变成了Zhang, Li (2020)这种形式，and怎么也加不上去

**Comment by stone-zeng** [comment]
```tex
\PassOptionsToPackage{mincitenames=1, maxcitenames=2}{biblatex}
\documentclass{fduthesis}

\fdusetup{
  style = {
    bib-backend = biblatex,
    bib-style = gb7714-2015,
    cite-style = gb7714-2015ay,
  }
}

\AtEndPreamble{
  \DefineBibliographyStrings{english}{
    andincite   = {and},
    andincitecn = {和},
  }
}

\begin{document}
...
\end{document}
```

**Comment by plong511** [comment]
> ```
> \PassOptionsToPackage{mincitenames=1, maxcitenames=2}{biblatex}
> \documentclass{fduthesis}
> 
> \fdusetup{
>   style = {
>     bib-backend = biblatex,
>     bib-style = gb7714-2015,
>     cite-style = gb7714-2015ay,
>   }
> }
> 
> \AtEndPreamble{
>   \DefineBibliographyStrings{english}{
>     andincite   = {and},
>     andincitecn = {和},
>   }
> }
> 
> \begin{document}
> ...
> \end{document}
> ```

\AtEndPreamble{
  \DefineBibliographyStrings{english}{
    andincite   = {and},
    andincitecn = {和},
  }
}
这一段还是没有效果。请问我有没有办法直接修改cls文件？

**Comment by plong511** [comment]
> ```
> \PassOptionsToPackage{mincitenames=1, maxcitenames=2}{biblatex}
> \documentclass{fduthesis}
> 
> \fdusetup{
>   style = {
>     bib-backend = biblatex,
>     bib-style = gb7714-2015,
>     cite-style = gb7714-2015ay,
>   }
> }
> 
> \AtEndPreamble{
>   \DefineBibliographyStrings{english}{
>     andincite   = {and},
>     andincitecn = {和},
>   }
> }
> 
> \begin{document}
> ...
> \end{document}
> ```

这一段加上去后什么效果都没有，甚至还不会报错

**Comment by stone-zeng** [comment]
……我这里都是测试好了的，你看看是不是按照这个格式写的（没让直接复制啊喂），以及辅助文件删掉之后再编译试试。

**Comment by plong511** [comment]
> ……我这里都是测试好了的，你看看是不是按照这个格式写的（没让直接复制啊喂），以及辅助文件删掉之后再编译试试。

我没有直接复制呀...我百思不得其解的是
\AtEndPreamble{
\DefineBibliographyStrings{english}{
andincite = {and},
andincitecn = {和},
}
}
这一段加上去后什么变化都没有，甚至不会报错

**Comment by stone-zeng** [comment]
加：

![image](https://user-images.githubusercontent.com/18233088/111278701-d30b6600-8674-11eb-9d22-f8fd335eb5b0.png)

不加：

![image](https://user-images.githubusercontent.com/18233088/111278751-e0c0eb80-8674-11eb-9672-120020ceab0a.png)

**Comment by plong511** [comment]
> 加：
> 
> ![image](https://user-images.githubusercontent.com/18233088/111278701-d30b6600-8674-11eb-9d22-f8fd335eb5b0.png)
> 
> 不加：
> 
> ![image](https://user-images.githubusercontent.com/18233088/111278751-e0c0eb80-8674-11eb-9672-120020ceab0a.png)

我已经放弃这个方式了。。。我发现原来的chinese-erj格式是可以实现这样的。但有两个问题，一是我没法只设置cite-style是chinese-erj的而bib-style保持gb7714-2015。二是，chinese-erj的文中引文格式，英文名之间是&而不是and，这个有办法解决吗？

**Comment by hushidong** [comment]
用chinese-erj，同样用这句：

```
\AtEndPreamble{
\DefineBibliographyStrings{english}{
andincite = {and},
andincitecn = {和},
}
}
```

就是把&换成了and

**Comment by hushidong** [comment]
不加的话，你就在系统里面搜索chinese-erj.BBX,找到：
```
%==================================================
%为标注和文献表中标点格式，重设and本地化字符串
%==================================================
\DefineBibliographyStrings{english}{
    and         = { and},%and后面的空格在finalnamedelim已经加过了，所以这里去掉20191009
    andcn       = {、},
    andincitecn = {和},%将标注中的分开，便于与文献表中的区分
    andincite   = {\&},
    %andotherscn={等},
    %mathesiscn={[硕士学位论文]},
    %phdthesiscn={[博士学位论文]},
}
```
把\&改成and

**Comment by stone-zeng** [comment]
不要直接改 TeX 发行版自带的所有文件，如果要改，就复制到编译所在的当前目录下，会覆盖系统同名文件的。

**Comment by plong511** [comment]
> 不要直接改 TeX 发行版自带的所有文件，如果要改，就复制到编译所在的当前目录下，会覆盖系统同名文件的。

我发现在本地用TexStudio编译是可以实现的，但在overleaf上就没有效果，这会是什么原因呢？
不行的话也可以的，只要能编译出来就好
