### ISSUE TITLE
页眉格式的调整

### ISSUE THREAD

**Issue by plong511** [stone-zeng/fduthesis#196]
请问该如何将页眉的 第X章 去掉，仅保留章标题的部分？
现在在本地编辑还是会有bug，出现Chapter X.的问题，所以我想索性把这部分删掉吧。

**Comment by stone-zeng** [comment]
导言区：

```tex

\makeatletter

\let\ps@plain\ps@fancy
\fancyhead[L]{\fdu@kai\zihao{-5}论文短标题}
\fancyhead[R]{\fdu@kai\zihao{-5}\rightmark}

\renewcommand{\chaptermark}[1]{\markboth{}{#1}}
% 如果想要「第 1 章 介绍」这样的效果，就换下面一行的定义
% \renewcommand{\chaptermark}[1]{\markboth{}{\CTEXifname{\CTEXthechapter\quad}{}#1}}

\renewcommand{\sectionmark}[1]{}

\makeatother
```

**Comment by plong511** [comment]
现在要求的是同一页的页眉左边是论文短标题，右边是章标题，我用的是
\lhead{\footnotesize \nouppercase { 
		\fdu@kai 论文短标题}}
\rhead{\footnotesize \nouppercase { 
\fdu@kai \leftmark}}
在底下加上
\renewcommand{\chaptermark}[1]{\markboth{}{#1}}
之后，右边的章标题整个没了，是什么问题呢？

**Comment by stone-zeng** [comment]
请按照上面的那个代码写，注意 left、right 和之前 issue 里面的不一样。

因为 LaTeX 默认 `\leftmark` 是章标题，`\rightmark` 是节标题，所以之前 issue 就按你的意思在 `\fancyhead[R]` 里面填了 `\leftmark`。但现在既然你需要修改格式，那就干脆直接重新定义 `\chaptermark` 和 `\sectionmark` 使其修改相应的 `\leftmark` 和 `\rightmark` 以符合要求。（反正比较绕，希望能理解😅）

**Comment by plong511** [comment]
> 请按照上面的那个代码写，注意 left、right 和之前 issue 里面的不一样。
> 
> 因为 LaTeX 默认 `\leftmark` 是章标题，`\rightmark` 是节标题，所以之前 issue 就按你的意思在 `\fancyhead[R]` 里面填了 `\leftmark`。但现在既然你需要修改格式，那就干脆直接重新定义 `\chaptermark` 和 `\sectionmark` 使其修改相应的 `\leftmark` 和 `\rightmark` 以符合要求。（反正比较绕，希望能理解😅）

可以了，多谢多谢！
