### ISSUE TITLE
biblatex 调用错误

### ISSUE THREAD

**Issue by tanukihee** [stone-zeng/fduthesis#197]
源于 `\ctex_at_end_preamble:n` 的钩子改动，见 https://github.com/CTeX-org/ctex-kit/commit/a12c13380406a4cabef970d9d9aeac08bbcef45b 与 https://github.com/CTeX-org/forum/issues/190

**Comment by stone-zeng** [comment]
Fixed in 513f7e904150a3642ccba5e908904879d1a55cf0.
