### ISSUE TITLE
学院要求GB 7714-87格式参考文献

### ISSUE THREAD

**Issue by MengAaron** [stone-zeng/fduthesis#199]
希望尽快支持！

**Comment by sikouhjw** [comment]
参考文献的支持没这么简单的，gbt7714-2015 的 bibtex 支持是 `texdoc gbt7714`，biblatex 支持是 `texdoc biblatex-gbt7714-2015`，都是做了专门的宏包去支持的。

况且 `GB 7714-87` 实在太久远了，没现成的需求大概率也没人有动力去做/维护。

**Comment by hushidong** [comment]
哪个学校好像也是87的，好像是西北农林，不知道记错没，可以把代码拿过来直接用。

**Comment by sikouhjw** [comment]
> 
> 
> 哪个学校好像也是87的，好像是西北农林，不知道记错没，可以把代码拿过来直接用。

https://gitee.com/nwafu_nan/nwafuthesis 西北农林科技大学用的是 `texdoc biblatex-gbt7714-2015`

**Comment by zepinglee** [comment]
管理学院的？

我可以改一份 1987 的 bst，不过需要帮我把 GB/T 7714—1987 的参考文献样例整理成 .bib 格式用于测试比对。

**Comment by hushidong** [comment]
西北农林还是有点像的，是基于2015改的，可能也有点他们自定的内容。

87最大的特征是没有文献标志类型。

我想你如果真的要87的还是要仔细对比一下，你们学院的要求是真的87，而不是自定义的。前面有个issue，是不是经管的有点忘了，就有一些反复，好像又回到2015了。

**Comment by MengAaron** [comment]
学院要求是87，不过据说去年交15版也都过了
