### ISSUE TITLE
关于 硕/博士论文 参考文献 “出版地不详”

### ISSUE THREAD

**Issue by leewi9** [stone-zeng/fduthesis#203]
```
@phdthesis{曹蕾2009肺结节图像的分析与识别,
  title  = {肺结节图像的分析与识别},
  author = {曹蕾},
  year   = {2009},
  school = {南方医科大学}
}
```

显示为
```
曹蕾.肺结节图像的分析与识别[D]. [出版地不详]:南方医科大学, 2009.
```

查了下gbt7714规范，显示成 出版地不详，是符合规定的，但就是觉得有点不对劲，这个不改的话，交图书馆或毕业后会出问题吗？

如果要查到出版地，要按照什么格式补上去呢，先谢谢各位大佬了~~

**Comment by sikouhjw** [comment]
`address = {<出版地>},`

**Comment by sikouhjw** [comment]
A phdthesis is like a mastersthesis.
Required: author, title, school, year
Optional: type, address, month, note
```
@phdthesis{曹蕾2009肺结节图像的分析与识别,
  title   = {肺结节图像的分析与识别},
  author  = {曹蕾},
  year    = {2009},
  school  = {南方医科大学},
  address = {广东},
  doi     = {10.7666/d.y1554072},
}
```

**Comment by leewi9** [comment]
哦哦，我把address都补上了，那个doi没有写上去，应该也可以吧

现在是这样了

```
曹蕾.肺结节图像的分析与识别[D].广州:南方医科大学, 2009.
```

**Comment by zepinglee** [comment]
> 那个doi没有写上去，应该也可以吧

默认情况下如果有 `doi` 就会输出到参考文献表。你的 TeX Live 和 `gbt7714` 的版本是啥？

**Comment by sikouhjw** [comment]
> > 那个doi没有写上去，应该也可以吧
> 
> 默认情况下如果有 `doi` 就会输出到参考文献表。你的 TeX Live 和 `gbt7714` 的版本是啥？

他的意思是没在 bib 文件中写

**Comment by zepinglee** [comment]
> > > 那个doi没有写上去，应该也可以吧
> > 
> > 
> > 默认情况下如果有 `doi` 就会输出到参考文献表。你的 TeX Live 和 `gbt7714` 的版本是啥？
> 
> 他的意思是没在 bib 文件中写

DOI 可有可无，另外学位轮文一般也没有 DOI。
