### ISSUE TITLE
选项 oneside 改为 twoside 之后，摘要部分第一页的段落间行距发生了变化

### ISSUE THREAD

**Issue by leewi9** [stone-zeng/fduthesis#204]
经过我的测试，确实是因为选项 oneside 改为 twoside 之后发生的，具体情况就是中文摘要的第一页的几个段落，段落间行距在改成 twoside 之后变大了，第二页的段落间行距没有变，是正常的；英文摘要段落间行距也没发现有变化，请问大概是什么原因，要怎么修改呢，谢谢！

**Comment by leewi9** [comment]
https://www.pastenow.me/search/3d5f7ee1-ed87-41d6-a55d-0593d66b051b

摘要内容贴在这里

**Comment by sikouhjw** [comment]
我试了一下，是 `\raggedbottom`/`\flushbottom` 的问题，似乎是 `twoside` 下默认为 `\flushbottom`，而 `oneside` 下默认为 `\raggedbottom`。
所以想解决的话，在导言区加 `\raggedbottom` 就可以了。

**Comment by sikouhjw** [comment]
模板层面没有改这个，是 `book.cls` 层面做的设置，`book.cls` 的第 736-739 行：
```tex
\if@twoside
\else
  \raggedbottom
\fi
```
总之，算是一种风格倾向吧，`oneside` 选择顶部对齐，`twoside` 选择分散对齐。

总结：这不是 bug。

**Comment by leewi9** [comment]
加上 \raggedbottom 之后ok了，谢谢！

**Comment by stone-zeng** [comment]
其实模板里面有说明的：

https://github.com/stone-zeng/fduthesis/blob/1a6be5b35e2d9db40e9292fe44276d8359825fa6/docs/fduthesis-template.tex#L241-L242
