### ISSUE TITLE
关于目录页颜色不能调整为黑色的问题

### ISSUE THREAD

**Issue by kewellyoung** [stone-zeng/fduthesis#205]
电子稿上传到图书馆系统时，可能因“目录与表格页格式不标准，字体颜色要用黑色，详情请参照复旦大学博士、硕士学位论文规范（2017.03修订版）”问题而未通过审核。

建议在作者在./source/fduthesis.dtx加入黑色选项：

- L1331, L1339 = "%       XXXXXX\mbox{}~~~~~~~~~~~~~~~~~~business|science|black|summer|autumn|graylevel|prl>*) " 
- L1384 add "%   \opt{black}\tnote{e}   & \linkcolorexam{000000}{000000}{000000} \\"
- L5775 add "{ black,     000000, 000000, 000000 }," 

已编译过的使用者可以在./thesis文件夹下打开fduthesis.cls（或fduthesis-en.cls），在L1690（或L1610）处追加一行：

- "{ black,     000000, 000000, 000000 },"

并在主tex文件约L104处将"**%** hyperlink-color = default,"  改为  ”hyperlink-color = black“.

**Comment by sikouhjw** [comment]
您看了说明手册吗？

您是不是需要
```tex
hyperlink = none,
```
