### ISSUE TITLE
参考文献编译问题

### ISSUE THREAD

**Issue by macheng6** [stone-zeng/fduthesis#206]
参考文献编译后都变成了问号，还有引用插入的图片，也会变成问号。请问这是怎么回事，环境是用voerleaf，编译器是XeLatex

**Comment by sikouhjw** [comment]
用 Overleaf 上的版本不就没事了？
https://www.overleaf.com/latex/templates/fduthesis-latex-thesis-template-for-fudan-university/svtdhhstkmkt

**Comment by macheng6** [comment]
好的，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月5日(周六) 下午3:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [stone-zeng/fduthesis] 参考文献编译问题 (#206)




 
用 Overleaf 上的版本不就没事了？
 https://www.overleaf.com/latex/templates/fduthesis-latex-thesis-template-for-fudan-university/svtdhhstkmkt
