### ISSUE TITLE
figure中插入subfigure的问题

### ISSUE THREAD

**Issue by macheng6** [stone-zeng/fduthesis#207]
比如一个figure中有三个subfigure，我想让这个三个subfigure排列在同一行，分别有自己的编号和描述。编译之后子编号与描述没有和子图对齐。

环境是overleaf，模版是overleaf中的模版。

**Comment by sikouhjw** [comment]
用这个 https://www.ctan.org/pkg/subcaption
自己读手册

**Comment by stone-zeng** [comment]
```tex
\begin{figure}[htbp]
  \centering
  \begin{subfigure}{0.25\textwidth}
    \centering
    \includegraphics[width=\textwidth]{example-image-a.pdf}
    \caption{示例图片 A}
  \end{subfigure}
  \qquad
  \begin{subfigure}{0.25\textwidth}
    \centering
    \includegraphics[width=\textwidth]{example-image-b.pdf}
    \caption{示例图片 B}
  \end{subfigure}
  \qquad
  \begin{subfigure}{0.25\textwidth}
    \centering
    \includegraphics[width=\textwidth]{example-image-c.pdf}
    \caption{示例图片 C}
  \end{subfigure}
  \caption{来自 \texttt{mwe} 宏包的示例图片}
\end{figure}
```

![Screen Shot 2021-06-05 at 17 18 38](https://user-images.githubusercontent.com/18233088/120886746-1648f580-c622-11eb-8eef-6a171c006ac7.png)

会有一些 warning，但并不影响结果。

**Comment by macheng6** [comment]
好的，谢谢



---原始邮件---
发件人: "Xiangdong ***@***.***&gt;
发送时间: 2021年6月5日(周六) 下午5:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [stone-zeng/fduthesis] figure中插入subfigure的问题 (#207)




 \begin{figure}[htbp]   \centering   \begin{subfigure}{0.25\textwidth}     \centering     \includegraphics[width=\textwidth]{example-image-a.pdf}     \caption{示例图片 A}   \end{subfigure}   \qquad   \begin{subfigure}{0.25\textwidth}     \centering     \includegraphics[width=\textwidth]{example-image-b.pdf}     \caption{示例图片 B}   \end{subfigure}   \qquad   \begin{subfigure}{0.25\textwidth}     \centering     \includegraphics[width=\textwidth]{example-image-c.pdf}     \caption{示例图片 C}   \end{subfigure}   \caption{来自 \texttt{mwe} 宏包的示例图片} \end{figure}
 

 
会有一些 warning，但并不影响结果。
