### ISSUE TITLE
请问怎么把目录的字体颜色变为黑色

### ISSUE THREAD

**Issue by dx629** [stone-zeng/fduthesis#209]
我目前用的是overleaf的版本，生成的pdf的目录字体为红色，不知道怎么把它改成黑色的

**Comment by sikouhjw** [comment]
> 在您使用 `fduthesis` 之前，请务必仔细阅读模板文档 [fduthesis.pdf](http://mirrors.ctan.org/macros/latex/contrib/fduthesis/fduthesis.pdf)。

**Comment by stone-zeng** [comment]
```tex
% 关闭目录中的超链接（用黑色显示）
\hypersetup{linktoc=none}
```

或者看 #115, #205
