### ISSUE TITLE
模板欧拉字体问题

### ISSUE THREAD

**Issue by yuangen** [stone-zeng/fduthesis#211]
使用overleaf编译模板时\mathcal和\mathscr字体相同，而且都是\mathscr字体，怎么解决？

**Comment by sikouhjw** [comment]
《[在 LaTeX 中使用 OpenType 字体（三）/#字母表](https://stone-zeng.github.io/2020-05-02-use-opentype-fonts-iii/#%E5%AD%97%E6%AF%8D%E8%A1%A8)》

**Comment by yuangen** [comment]
我这个问题还是没有解决，
![image](https://user-images.githubusercontent.com/24764051/124439624-364c1000-ddac-11eb-8dcc-bd2807140018.png)
\mathcal命令的效果应该是这样
![image](https://user-images.githubusercontent.com/24764051/124440102-d4d87100-ddac-11eb-9462-aeceae7468f6.png)
现在两个命令都是mathrsfs包的字体效果。我对原文档没有任何操作，请问是否模板在哪里做了改动？

**Comment by sikouhjw** [comment]
> 
> 
> 我这个问题还是没有解决，
> ![image](https://user-images.githubusercontent.com/24764051/124439624-364c1000-ddac-11eb-8dcc-bd2807140018.png)
> \mathcal命令的效果应该是这样
> ![image](https://user-images.githubusercontent.com/24764051/124440102-d4d87100-ddac-11eb-9462-aeceae7468f6.png)
> 现在两个命令都是mathrsfs包的字体效果。我对原文档没有任何操作，请问是否模板在哪里做了改动？

你看了链接吗？`unicode-math` 没有设置 `\mathcal`，只有手写体（script）。

**Comment by yuangen** [comment]
替换全局拉丁字体后解决了，能局部设定字体吗？有些字体拉丁不好看

**Comment by sikouhjw** [comment]
> 替换全局拉丁字体后解决了，能局部设定字体吗？有些字体拉丁不好看

是这样的，「非模板提供的、自己魔改的」，原则上不关模板的事。

**Comment by stone-zeng** [comment]
截图里面是 Latin Modern 的样式，如果需要的话，可以设置 `font=lm`，同时全部的西文字体也会换掉。

**Comment by TianLin0509** [comment]
发现在导言区分别加入以下代码可以正常使用 \mathbb 和 \mathcal

```
% mathcal 的正常使用
\DeclareMathAlphabet{\mathcal}{OMS}{cmsy}{m}{n}
% mathbb 的正常使用
\setmathfont{LatinModernMath-Regular}
\setmathfont[range=\mathbb]{TeXGyrePagellaMath-Regular}
```
