### ISSUE TITLE
计算机菜狗写个伪代码算法流程可太难了\usepackage{algorithm} 

### ISSUE THREAD

**Issue by Stevenhork** [stone-zeng/fduthesis#213]
\renewcommand{\algorithmicrequire}{ \textbf{Input:}} %Use Input in the format of Algorithm
\renewcommand{\algorithmicensure}{ \textbf{Output:}} %Use Output in the format of Algorithm
![image](https://user-images.githubusercontent.com/40121268/125185750-207d9580-e259-11eb-8d18-38b0f13673e0.png)

**Comment by sikouhjw** [comment]
抄代码要抄全，不要只抄一半
```tex
\usepackage{algorithm,algorithmic}
```

**Comment by Stevenhork** [comment]
![image](https://user-images.githubusercontent.com/40121268/125186578-a4d21780-e25d-11eb-819a-617f2e7eed87.png)
作为一个资深的面向ctr+c编程的菜狗，怎会犯如此错误呢。不是这个原因

**Comment by Stevenhork** [comment]
> 抄代码要抄全，不要只抄一半
> 
> ```
> \usepackage{algorithm,algorithmic}
> ```
![image](https://user-images.githubusercontent.com/40121268/125186609-e662c280-e25d-11eb-8ea1-5d70cd253620.png)
作为一个资深面向Ctr+c编程的菜狗，怎么犯如此错误。不是这个原因

**Comment by sikouhjw** [comment]
提供发行版版本、模板版本、编译方式信息。
```tex
\documentclass{fduthesis}
\usepackage{algorithm,algorithmic}
\begin{document}
\begin{algorithm}
  \renewcommand{\algorithmicrequire}{\textbf{Input:}}
  \renewcommand{\algorithmicensure}{\textbf{Output:}}
  \begin{algorithmic}[1]
    \STATE Initialization:$\left\{ {s_{k,t}^1} \right\},\left\{ {\omega _{k,t}^1} \right\},\lambda _t^1,n \leftarrow 0$
    \ENSURE  decomposed modes $ \left\{ {{s_k}\left( t \right)} \right\}$, $\left\{ {{\omega _k}\left( t \right)} \right\}$
  \end{algorithmic}  
\end{algorithm}
\end{document}
```
![图片](https://user-images.githubusercontent.com/49770925/125186747-bf58c080-e25e-11eb-8a94-705c028bdb73.png)

**Comment by sikouhjw** [comment]
在 Overleaf 上的测试也没有问题，版本为 texlive 2020。

`fduthesis` 没有对算法进行处理，大概率是你的问题。
