### ISSUE TITLE
文档里的demo编译不过去

### ISSUE THREAD

**Issue by Almph** [stone-zeng/fduthesis#214]
```tex
\documentclass{fduthesis} 
\begin{document}
\chapter{欢迎} 
\section{Welcome to fduthesis!} 
你好，\LaTeX{}!
\end{document}
```
然后在**biblatex.sty**文件里报错，

行 503: Undefined control sequence. \let\do\noexpand}
行 503: Missing number, treated as zero. \let\do\noexpand}
行 503: Undefined control sequence. \let\do\noexpand}
行 503: Missing number, treated as zero. \let\do\noexpand}
行 503: Undefined control sequence. \let\do\noexpand}
行 503: Package etoolbox Error: Toggle 'blx@tempa' undefined. \let\do\noexpand}
行 503: Package etoolbox Error: Toggle 'blx@tempa' undefined. \let\do\noexpand}
行 503: Package etoolbox Error: Toggle 'blx@tempa' undefined. \let\do\noexpand}
行 503: Package etoolbox Error: Toggle 'blx@tempa' undefined. \let\do\noexpand}
行 503: Package etoolbox Error: Toggle 'blx@tempa' undefined. \let\do\noexpand}
行 503: Package etoolbox Error: Toggle 'blx@tempa' undefined. \let\do\noexpand}
行 503: Package etoolbox Error: Toggle 'blx@tempa' undefined. \let\do\noexpand}
行 503: Package etoolbox Error: Toggle 'blx@trackfloats' undefined. \let\do\noexpand}
行 503: Package etoolbox Error: Toggle 'blx@backreffloats' undefined. \let\do\noexpand}
行 619: Undefined control sequence. {\blx@err@patch{\string\addtocontents}}}
行 619: Missing \begin{document}. {\blx@err@patch{\string\addtocontents}}}
行 14397: Undefined control sequence. ...blx@refcontexts\blx@refcontext@context}
行 14397: Undefined control sequence. ...blx@refcontexts\blx@refcontext@context}
行 14397: Package biblatex Error: Option 'sorting=' invalid. ...blx@refcontexts\blx@refcontext@context}
行 15331: Undefined control sequence. ...@refsecreset@level}{\newrefsection}{}{}
行 15331: Missing number, treated as zero. ...@refsecreset@level}{\newrefsection}{}{}
行 15358: Undefined control sequence. {}
行 15358: Missing number, treated as zero. {}
行 15358: Undefined control sequence. {}
行 15358: Missing number, treated as zero. {}
行 15373: Undefined control sequence. ...t@level}{\citereset\blx@inf@creset}{}{}
行 15373: Missing number, treated as zero. ...t@level}{\citereset\blx@inf@creset}{}{}
: It seems that you have not declare a CJKfamily.
: Redefining '\citet'.
: Redefining '\citep'.
: Font "FandolSong-Regular" does not contain requested(fontspec) Script "CJK".
: Font "FandolKai-Regular" does not contain requested(fontspec) Script "CJK".
: Font "FandolHei-Regular" does not contain requested(fontspec) Script "CJK".
: No file demo.bbl.
: File `demo.out' has changed.

**Comment by Almph** [comment]
overleaf用texlive2020可以编译通过，本地mac上texlive2021编译不通过，诶。。。

**Comment by stone-zeng** [comment]
TeX Live 自带的 `fduthesis` 还没更新，暂时先要用从 GitHub 上面下载的。

**Comment by Almph** [comment]
> TeX Live 自带的 `fduthesis` 还没更新，暂时先要用从 GitHub 上面下载的。

嗯，用脚本安装覆盖了原来的fduthesis文件夹下的内容。现在可以编译通过，但所有的中文字符都消失了。。。

**Comment by Almph** [comment]
重装了2020版本，已解决。

**Comment by sikouhjw** [comment]
> 
> 
> > TeX Live 自带的 `fduthesis` 还没更新，暂时先要用从 GitHub 上面下载的。
> 
> 嗯，用脚本安装覆盖了原来的fduthesis文件夹下的内容。现在可以编译通过，但所有的中文字符都消失了。。。

单独打开 pdf 文件也看不见吗？

**Comment by Almph** [comment]
> > > TeX Live 自带的 `fduthesis` 还没更新，暂时先要用从 GitHub 上面下载的。
> > 
> > 
> > 嗯，用脚本安装覆盖了原来的fduthesis文件夹下的内容。现在可以编译通过，但所有的中文字符都消失了。。。
> 
> 单独打开 pdf 文件也看不见吗？

嗯，应该是texstudio自带的pdfviewer的问题。暂时先用texlive2020了😂。
