### ISSUE TITLE
请问和 overleaf 上的是最新的版本吗？

### ISSUE THREAD

**Issue by tristone13th** [stone-zeng/fduthesis#215]

**Comment by sikouhjw** [comment]
1. 你只问了一个问题，为什么要加「和」？
2. 不是最新版。最新版在 Overleaf 用不了。

**Comment by stone-zeng** [comment]
不是，最新版就是从这边下载或者 git clone 到的：

<img width="855" alt="Screen Shot 2021-08-08 at 00 02 05" src="https://user-images.githubusercontent.com/18233088/128606292-07d7712c-5a93-438f-a0bf-9830eca8eb7e.png">
