### ISSUE TITLE
关键词分隔符改为逗号，怎么在导言区更改

### ISSUE THREAD

**Issue by dx629** [stone-zeng/fduthesis#216]
\cs_renew_protected:Npn
上一个问题大佬说可以在导言区更改，但我改了很多次都是错的，正确的改发应该是怎么样的呀？谢谢大佬们

**Comment by sikouhjw** [comment]
哪一个「上个问题」？
您能不能完整描述您的问题和需求。

**Comment by dx629** [comment]
> 哪一个「上个问题」？
> 您能不能完整描述您的问题和需求。
https://github.com/stone-zeng/fduthesis/issues/171 不好意思

**Comment by sikouhjw** [comment]
第一种替换成中文逗号，第二种替换为西文逗号，自行选择，再看不懂就没辙了。
```tex
\documentclass{fduthesis}

\ExplSyntaxOn
\cs_set_protected:Npn \__fdu_abstract_end:
  {
    \__fdu_keywords:nNn
      { \sffamily \c__fdu_name_keywords_tl \c__fdu_fwid_colon_tl }
      \l__fdu_info_keywords_clist { \c__fdu_fwid_comma_tl }
    \__fdu_clc:nn
      { \sffamily \c__fdu_name_clc_tl \c__fdu_fwid_colon_tl }
      { \l__fdu_info_clc_tl }
  }
% \cs_set_protected:Npn \__fdu_abstract_end:
%   {
%     \__fdu_keywords:nNn
%       { \sffamily \c__fdu_name_keywords_tl \c__fdu_fwid_colon_tl }
%       \l__fdu_info_keywords_clist { ,~ }
%     \__fdu_clc:nn
%       { \sffamily \c__fdu_name_clc_tl \c__fdu_fwid_colon_tl }
%       { \l__fdu_info_clc_tl }
%   }
\ExplSyntaxOff

\fdusetup{
  info/keywords = {测试,再测试}
}

\begin{document}
  \begin{abstract}
    中文摘要
  \end{abstract}
\end{document}
```

**Comment by dx629** [comment]
> 第一种替换成中文逗号，第二种替换为西文逗号，自行选择，再看不懂就没辙了。
> 
> ```
> \documentclass{fduthesis}
> 
> \ExplSyntaxOn
> \cs_set_protected:Npn \__fdu_abstract_end:
>   {
>     \__fdu_keywords:nNn
>       { \sffamily \c__fdu_name_keywords_tl \c__fdu_fwid_colon_tl }
>       \l__fdu_info_keywords_clist { \c__fdu_fwid_comma_tl }
>     \__fdu_clc:nn
>       { \sffamily \c__fdu_name_clc_tl \c__fdu_fwid_colon_tl }
>       { \l__fdu_info_clc_tl }
>   }
> % \cs_set_protected:Npn \__fdu_abstract_end:
> %   {
> %     \__fdu_keywords:nNn
> %       { \sffamily \c__fdu_name_keywords_tl \c__fdu_fwid_colon_tl }
> %       \l__fdu_info_keywords_clist { ,~ }
> %     \__fdu_clc:nn
> %       { \sffamily \c__fdu_name_clc_tl \c__fdu_fwid_colon_tl }
> %       { \l__fdu_info_clc_tl }
> %   }
> \ExplSyntaxOff
> 
> \fdusetup{
>   info/keywords = {测试,再测试}
> }
> 
> \begin{document}
>   \begin{abstract}
>     中文摘要
>   \end{abstract}
> \end{document}
> ```

谢谢！替换好了
