### ISSUE TITLE
如何设置表格标题居于表格上方

### ISSUE THREAD

**Issue by ROGERDJQ** [stone-zeng/fduthesis#217]
目前不管怎么移动caption的位置，标题都在表格下方，我使用的版本是0.7d。想问怎么操作可以移动到上方呢？

**Comment by sikouhjw** [comment]
> 目前不管怎么移动caption的位置，标题都在表格下方，我使用的版本是0.7d。想问怎么操作可以移动到上方呢？

给 MWE，你描述的是「不应当」的情况。

**Comment by stone-zeng** [comment]
直接把 `\caption` 放在前面：

```tex
\begin{table}[htp]
  \caption{这是放在前面的表格标题}
  \centering
  \begin{tabular}{ccc}
    \hline
    A & B & C \\
    \hline
  \end{tabular}
\end{table}
```

<img width="461" alt="Screen Shot 2021-09-08 at 12 02 32" src="https://user-images.githubusercontent.com/18233088/132444555-8c6849f7-e8ec-4533-8861-dc0a88a5fdb2.png">

**Comment by ROGERDJQ** [comment]
![image](https://user-images.githubusercontent.com/25008973/132481765-9e408375-ff95-4a55-96f8-b73c1fceebea.png)
谢谢回复，但是我尝试了这个代码，得到的标题仍然是在下面

**Comment by sikouhjw** [comment]
编译从 github clone 的源文件会不会这样？你加了什么宏包？

**Comment by ROGERDJQ** [comment]
是用的学长给的旧的模板 不是新的  
版本号是：% fduthesis: 复旦大学论文模板
% 2019/04/03 v0.7d

使用环境是：windows10
使用软件是： vscode
tex为： texlive2021

**Comment by sikouhjw** [comment]
请使用最新版。

**Comment by ROGERDJQ** [comment]
好的 谢谢回复 我试一下最新版

**Comment by ROGERDJQ** [comment]
感谢回复 最后问题找到了 是floatrow包的问题。我在网上找到可以这样修改：
\usepackage{floatrow}
\floatsetup[table]{capposition=top}
\floatsetup[figure]{capposition=bottom}
\newfloatcommand{capbtabbox}{table}[][\FBwidth]

**Comment by sikouhjw** [comment]
> 
> 
> 感谢回复 最后问题找到了 是floatrow包的问题。我在网上找到可以这样修改：
> \usepackage{floatrow}
> \floatsetup[table]{capposition=top}
> \floatsetup[figure]{capposition=bottom}
> \newfloatcommand{capbtabbox}{table}[][\FBwidth]

为什么要加这个包？

**Comment by ROGERDJQ** [comment]
作图的时候六张图要做成一个3*2的大图，要求每个子图有caption和label，大图有caption和label，同时每个子图的长和高也不一样，最后还要达到同一行的两个子图的底在一条线上。最后用了floatrow

**Comment by sikouhjw** [comment]
`subfig`/`subcaption` 都能达到你说的效果。

**Comment by ROGERDJQ** [comment]
谢谢 有时间我试一下
