### ISSUE TITLE
[EB/OL] 类型参考文献格式问题

### ISSUE THREAD

**Issue by Wen-He** [stone-zeng/fduthesis#218]
[EB/OL] 类型参考文献如何改成这个格式？
![image](https://user-images.githubusercontent.com/18651139/132725021-8587b133-750e-467d-b888-2dcad42d80ad.png)

我的 `.bib` 内容如下:
```
@misc{xxhash,
  author       = {Collet, Yann},
  title        = {{xxHash}: Extremely fast hash algorithm},
  howpublished = {\url{https://github.com/Cyan4973/xxHash}},
  urldate      = {2021-09},
  date         = {2020-07}
}
```

编译结果如下:
![image](https://user-images.githubusercontent.com/18651139/132725767-2c9fc9b9-3430-4138-b3c3-398ca2375309.png)

如何显示 urldate？

**Comment by zepinglee** [comment]
应该是用的 BibTeX 吧？

把 `howpublished` 改写成 `url = {https://github.com/Cyan4973/xxHash}` 就没问题了，应该是 `bst` 根据有无 `url` 判断电子文献时没考虑到 `howpublished`。

另外还可以把 `@misc` 换成 `@dataset`，这样文献类型标识会换成”DS“更符号要求。

```bib
```

**Comment by veliang1478** [comment]
编译出来文献显示没有OL，只有[EB]，请问是什么问题

**Comment by sikouhjw** [comment]
> 编译出来文献显示没有OL，只有[EB]，请问是什么问题

请提供参考文献 bib 代码

**Comment by fgfxf** [comment]
@Misc{OmdiaTraffic2024,
  author = {{Omdia Co.}},
  month  = apr,
  title  = {Cellular IoT Data Traffic: From Cloud to Edge - 2024 Analysis},
  year   = {2024},
  groups = {Omdia Co.},
  owner  = {Omdia Co.},
  url    = {https://omdia.tech.informa.com},
}
[1]	Omdia Co. Cellular IoT Data Traffic: From Cloud to Edge - 2024 Analysis[EB/OL]. 2024. https://omdia.tech.informa.com.

**Comment by note286** [comment]
@fgfxf 你使用的是bibtex还是biblatex。

**Comment by fgfxf** [comment]
> [@fgfxf](https://github.com/fgfxf) 你使用的是bibtex还是biblatex。

bibtex

**Comment by note286** [comment]
@fgfxf 你可以在 https://github.com/zepinglee/gbt7714-bibtex-style/blob/master/test/testbst/support/standard.bib 中搜索`@online`，里面有很多示例。
