### ISSUE TITLE
每一章的第一页缺页眉

### ISSUE THREAD

**Issue by tristone13th** [stone-zeng/fduthesis#219]
在 oneside 设置下，正文其他地方的页眉显示正常，但是每一章的第一页无页眉，同时目录部分多出了页眉，有什么办法嘛，谢谢~

**Comment by sikouhjw** [comment]
> 
> 
> 在 oneside 设置下，正文其他地方的页眉显示正常，但是每一章的第一页无页眉，同时目录部分多出了页眉，有什么办法嘛，谢谢~

1. 为什么每一张第一页要页眉？你在哪里看到的？
2. 目录部分为什么会多页眉？你的发行版版本、模板版本是什么？

**Comment by tristone13th** [comment]
> > 在 oneside 设置下，正文其他地方的页眉显示正常，但是每一章的第一页无页眉，同时目录部分多出了页眉，有什么办法嘛，谢谢~
> 
> 1. 为什么每一张第一页要页眉？你在哪里看到的？
> 2. 目录部分为什么会多页眉？你的发行版版本、模板版本是什么？

1. 查了下往年的论文，好像的确不需要，感谢；
2. 我用 docker 和 overleaf community 版本自己搭的一个系统，发行版是 TeX Live 2021，模板是上个月从这里下载的最新的模板（暂时不知道怎么看版本），编译器用的 XeLaTeX。
    
![1631954763(1)](https://user-images.githubusercontent.com/17382962/133882876-dc2abcae-eeec-4e5d-aba2-524a64bddfd9.png)

**Comment by sikouhjw** [comment]
> 
> 
> > > 在 oneside 设置下，正文其他地方的页眉显示正常，但是每一章的第一页无页眉，同时目录部分多出了页眉，有什么办法嘛，谢谢~
> > 
> > 
> > 
> > 1. 为什么每一张第一页要页眉？你在哪里看到的？
> > 2. 目录部分为什么会多页眉？你的发行版版本、模板版本是什么？
> 
>     1. 查了下往年的论文，好像的确不需要，感谢；
> 
>     2. 我用 docker 和 overleaf community 版本自己搭的一个系统，发行版是 TeX Live 2021，模板是上个月从这里下载的最新的模板（暂时不知道怎么看版本），编译器用的 XeLaTeX。
> 
> 
> ![1631954763(1)](https://user-images.githubusercontent.com/17382962/133882876-dc2abcae-eeec-4e5d-aba2-524a64bddfd9.png)

我知道为什么了，因为目录超过了一页，而目录用了 `\chapter*`，从而将 `\pagestyle` 覆盖为 `plain`，到下一页时，恢复为正常的页眉。

也就是说，这是正常的。

**Comment by stone-zeng** [comment]
每章的第一页按照通常惯例都不加页眉。目录作为形式上的一章也遵循同样做法，超过一页之后则会显示页眉。
