### ISSUE TITLE
oneside模式下的页眉问题

### ISSUE THREAD

**Issue by ROGERDJQ** [stone-zeng/fduthesis#220]
你好，之前的论文格式，学院提出意见要去掉空白页，于是我把twoside改成了oneside。
但是还是有两个紧急的问题，不知道怎么解决：

1. 修改为oneside之后，正文之前的部分，页眉部分都有问题。因为正文的页眉设置是左论文标题，右章节标题，中间是空的。而修改为为oneside之后，正文之前的部分，也即目录，插图目录，表格目录，中文摘要，英文摘要，这些部分的第一页页眉除了左右两个标题之外，中间还出现了章节标题。例如：
![image](https://user-images.githubusercontent.com/25008973/133954066-7d01f43a-73ff-465c-a706-8a0a7e9462e9.png)
，而后续页（比如摘要的第二页）则是只有左边和中间的页眉。而希望达到的效果是去掉中间的章节标题，只有左边和右边的页眉。

2. 英文摘要后的‘’关键字‘’这三个字怎么修改成‘Key Words’。这个没有找到修改的地方。

**Comment by stone-zeng** [comment]
> 这些部分的第一页页眉除了左右两个标题之外，中间还出现了章节标题

对于 `oneside` 模式下的前置部分（正文之前的部分），模板默认只显示中间页眉，内容是该部分对应的标题。不知道您做了什么修改？

用下面的代码可以修改成需要的效果：

```tex
% 导言区
\ExplSyntaxOn
\cs_set_protected:Npn \__fdu_chapter_header:n #1
  { \markboth { 论文标题 } {#1} }
\ExplSyntaxOff
```

> 英文摘要后的‘’关键字‘’这三个字怎么修改成‘Key Words’。这个没有找到修改的地方。

模板默认显示的就是 `Key Words`。
