### ISSUE TITLE
overleaf上的使用

### ISSUE THREAD

**Issue by TianLin0509** [stone-zeng/fduthesis#224]
首先感谢作者无私奉献的模板 

因为已经很久不用本地 Tex 编译器了， 都是用的overleaf 来写。

今天看到 overleaf上能搜到复旦大学的毕业论文模板，猜测可能是作者提交的， 再次表示感谢！

美中不足的是， overleaf上打开时， 只有 fduthesis-template.tex 这个问题， 而无法对 模板进行一些自定义， 可能限制了使用， 想问下有没有什么好的解决办法？

比如 模板中自带的 “中图分类号” 一项， 似乎不太能直接删除。 

再次感谢作者

**Comment by sikouhjw** [comment]
1. Overleaf 模板在这：https://www.overleaf.com/latex/templates/fduthesis-latex-thesis-template-for-fudan-university/svtdhhstkmkt
2. 如果你要对模板进行修改，请自行上传 cls 文件
3. 提问之前请查阅 issue，https://github.com/stone-zeng/fduthesis/issues?q=%E4%B8%AD%E5%9B%BE%E5%88%86%E7%B1%BB%E5%8F%B7

**Comment by TianLin0509** [comment]
> 1. Overleaf 模板在这：https://www.overleaf.com/latex/templates/fduthesis-latex-thesis-template-for-fudan-university/svtdhhstkmkt
> 2. 如果你要对模板进行修改，请自行上传 cls 文件
> 3. 提问之前请查阅 issue，https://github.com/stone-zeng/fduthesis/issues?q=%E4%B8%AD%E5%9B%BE%E5%88%86%E7%B1%BB%E5%8F%B7

* 可能是我没有表达清楚我的意思， 我已经在overleaf上搜到了这个模板， 但还是谢谢你的提供
* 对我现在就是想知道去哪里找到 模板所对应的 cls文件。 比如我想把 “关键字”改为“关键词”， 我相信在 cls文件中应该只是简单的修改，但 overleaf上无法找到这个文件， 不知能提供吗？
* 谢谢， 我确实在提问前把所有的issue全部浏览了一遍，很有收获

**Comment by sikouhjw** [comment]
> > 1. Overleaf 模板在这：https://www.overleaf.com/latex/templates/fduthesis-latex-thesis-template-for-fudan-university/svtdhhstkmkt
> > 2. 如果你要对模板进行修改，请自行上传 cls 文件
> > 3. 提问之前请查阅 issue，https://github.com/stone-zeng/fduthesis/issues?q=%E4%B8%AD%E5%9B%BE%E5%88%86%E7%B1%BB%E5%8F%B7
> 
>     * 可能是我没有表达清楚我的意思， 我已经在overleaf上搜到了这个模板， 但还是谢谢你的提供
> 
>     * 对我现在就是想知道去哪里找到 模板所对应的 cls文件。 比如我想把 “关键字”改为“关键词”， 我相信在 cls文件中应该只是简单的修改，但 overleaf上无法找到这个文件， 不知能提供吗？
> 
>     * 谢谢， 我确实在提问前把所有的issue全部浏览了一遍，很有收获

Overleaf 模板打开后，默认发行版是 tevlive 2019；封面是 2020 年 5 月 7 日。你需要去 [releases](https://github.com/stone-zeng/fduthesis/releases) 里面找到相应时期的模板，然后上传上去。

猜测是 fduthesis v0.7d。

**Comment by sikouhjw** [comment]
不需要猜测，我没看到主文件里写了。
```tex
%*********************************************************************
% fduthesis: 复旦大学论文模板
% 2019/04/03 v0.7d
%
% 重要提示：
%   1. 请确保使用 UTF-8 编码保存
%   2. 请使用 XeLaTeX 或 LuaLaTeX 编译
%   3. 请仔细阅读用户文档
%   4. 修改、使用、发布本文档请务必遵循 LaTeX Project Public License
%   5. 不需要的注释可以尽情删除
%*********************************************************************
```

**Comment by TianLin0509** [comment]
> 不需要猜测，我没看到主文件里写了。
> 
> ```
> %*********************************************************************
> % fduthesis: 复旦大学论文模板
> % 2019/04/03 v0.7d
> %
> % 重要提示：
> %   1. 请确保使用 UTF-8 编码保存
> %   2. 请使用 XeLaTeX 或 LuaLaTeX 编译
> %   3. 请仔细阅读用户文档
> %   4. 修改、使用、发布本文档请务必遵循 LaTeX Project Public License
> %   5. 不需要的注释可以尽情删除
> %*********************************************************************
> ```

感谢回复，已上传cls，探索中

**Comment by stone-zeng** [comment]
<img width="856" alt="Screen Shot 2021-12-21 at 18 27 50" src="https://user-images.githubusercontent.com/18233088/146914633-153b2ee3-be8e-40e9-9e98-e3fb799de02a.png">

目前 overleaf 上面的模板比较旧，建议按此方案生成 `thesis` 目录然后上传。

**Comment by TianLin0509** [comment]
> <img alt="Screen Shot 2021-12-21 at 18 27 50" width="856" src="https://user-images.githubusercontent.com/18233088/146914633-153b2ee3-be8e-40e9-9e98-e3fb799de02a.png">
> 
> 目前 overleaf 上面的模板比较旧，建议按此方案生成 `thesis` 目录然后上传。

谢谢， 按您的建议尝试了， 但报错： ```Package fduthesis Error: Package "ctex" is too old.``` 

直接使用 0.7d 似乎是正常的。

**Comment by sikouhjw** [comment]
> > <img alt="Screen Shot 2021-12-21 at 18 27 50" width="856" src="https://user-images.githubusercontent.com/18233088/146914633-153b2ee3-be8e-40e9-9e98-e3fb799de02a.png">
> > 目前 overleaf 上面的模板比较旧，建议按此方案生成 `thesis` 目录然后上传。
> 
> 谢谢， 按您的建议尝试了， 但报错： `Package fduthesis Error: Package "ctex" is too old.`
> 
> 直接使用 0.7d 似乎是正常的。

模板版本一定是跟发行版版本绑定的，请换到 texlive 2021。

**Comment by TianLin0509** [comment]
> > > <img alt="Screen Shot 2021-12-21 at 18 27 50" width="856" src="https://user-images.githubusercontent.com/18233088/146914633-153b2ee3-be8e-40e9-9e98-e3fb799de02a.png">
> > > 目前 overleaf 上面的模板比较旧，建议按此方案生成 `thesis` 目录然后上传。
> > 
> > 
> > 谢谢， 按您的建议尝试了， 但报错： `Package fduthesis Error: Package "ctex" is too old.`
> > 直接使用 0.7d 似乎是正常的。
> 
> 模板版本一定是跟发行版版本绑定的，请换到 texlive 2021。

谢谢帮助和回复， 但我应该已经使用了 2021， 见下图

![image](https://user-images.githubusercontent.com/34390943/146917948-755fd9eb-06f6-48a6-a91d-a4fe735516cf.png)

**Comment by sikouhjw** [comment]
> > > > <img alt="Screen Shot 2021-12-21 at 18 27 50" width="856" src="https://user-images.githubusercontent.com/18233088/146914633-153b2ee3-be8e-40e9-9e98-e3fb799de02a.png">
> > > > 目前 overleaf 上面的模板比较旧，建议按此方案生成 `thesis` 目录然后上传。
> > > 
> > > 
> > > 谢谢， 按您的建议尝试了， 但报错： `Package fduthesis Error: Package "ctex" is too old.`
> > > 直接使用 0.7d 似乎是正常的。
> > 
> > 
> > 模板版本一定是跟发行版版本绑定的，请换到 texlive 2021。
> 
> 谢谢帮助和回复， 但我应该已经使用了 2021， 见下图
> 
> ![image](https://user-images.githubusercontent.com/34390943/146917948-755fd9eb-06f6-48a6-a91d-a4fe735516cf.png)

很可惜模板最新版已经修复了这个问题
https://github.com/stone-zeng/fduthesis/blob/6e98af11bd8a3125da5702c40a947f59508b65f9/source/fduthesis.dtx#L3122
你用的不是『最新版』，你用的是发行版的最新版吧？

**Comment by TianLin0509** [comment]
> > > > > <img alt="Screen Shot 2021-12-21 at 18 27 50" width="856" src="https://user-images.githubusercontent.com/18233088/146914633-153b2ee3-be8e-40e9-9e98-e3fb799de02a.png">
> > > > > 目前 overleaf 上面的模板比较旧，建议按此方案生成 `thesis` 目录然后上传。
> > > > 
> > > > 
> > > > 谢谢， 按您的建议尝试了， 但报错： `Package fduthesis Error: Package "ctex" is too old.`
> > > > 直接使用 0.7d 似乎是正常的。
> > > 
> > > 
> > > 模板版本一定是跟发行版版本绑定的，请换到 texlive 2021。
> > 
> > 
> > 谢谢帮助和回复， 但我应该已经使用了 2021， 见下图
> > ![image](https://user-images.githubusercontent.com/34390943/146917948-755fd9eb-06f6-48a6-a91d-a4fe735516cf.png)
> 
> 很可惜模板最新版已经修复了这个问题
> 
> https://github.com/stone-zeng/fduthesis/blob/6e98af11bd8a3125da5702c40a947f59508b65f9/source/fduthesis.dtx#L3122
> 
> 
> 你用的不是『最新版』，你用的是发行版的最新版吧？

谢谢回复。 我是follow了 stone-zeng 的建议做的， 即直接从github主页下载 .zip 文件后 本地运行 install-win.bat， 然后将生成的 thesis 文件夹上传。 我确认了下， 你刚提到的这句代码在我下载的 fduthesis.dtx 中是有的， 因此我想我下载的应该是 最新版？

**Comment by sikouhjw** [comment]
> > > > > > <img alt="Screen Shot 2021-12-21 at 18 27 50" width="856" src="https://user-images.githubusercontent.com/18233088/146914633-153b2ee3-be8e-40e9-9e98-e3fb799de02a.png">
> > > > > > 目前 overleaf 上面的模板比较旧，建议按此方案生成 `thesis` 目录然后上传。
> > > > > 
> > > > > 
> > > > > 谢谢， 按您的建议尝试了， 但报错： `Package fduthesis Error: Package "ctex" is too old.`
> > > > > 直接使用 0.7d 似乎是正常的。
> > > > 
> > > > 
> > > > 模板版本一定是跟发行版版本绑定的，请换到 texlive 2021。
> > > 
> > > 
> > > 谢谢帮助和回复， 但我应该已经使用了 2021， 见下图
> > > ![image](https://user-images.githubusercontent.com/34390943/146917948-755fd9eb-06f6-48a6-a91d-a4fe735516cf.png)
> > 
> > 
> > 很可惜模板最新版已经修复了这个问题
> > https://github.com/stone-zeng/fduthesis/blob/6e98af11bd8a3125da5702c40a947f59508b65f9/source/fduthesis.dtx#L3122
> > 
> > 你用的不是『最新版』，你用的是发行版的最新版吧？
> 
> 谢谢回复。 我是follow了 stone-zeng 的建议做的， 即直接从github主页下载 .zip 文件后 本地运行 install-win.bat， 然后将生成的 thesis 文件夹上传。 我确认了下， 你刚提到的这句代码在我下载的 fduthesis.dtx 中是有的， 因此我想我下载的应该是 最新版？

我用 Overleaf 上的模板，设置 texlive 2021，报的错跟你发的图是一致的。

我用 Overleaf 上的模板，设置 texlive 2021，单独上传编译好的 `thesis/fduthesis.cls`，编译没有任何问题。
请参考我的 [Overleaf 链接](https://cn.overleaf.com/9268576289sdxwbtzgpnym)，对比你哪里出了问题。

**Comment by stone-zeng** [comment]
我刚刚试了下，新建空白项目然后上传再编译是没有问题的

**Comment by TianLin0509** [comment]
> > > > > > > <img alt="Screen Shot 2021-12-21 at 18 27 50" width="856" src="https://user-images.githubusercontent.com/18233088/146914633-153b2ee3-be8e-40e9-9e98-e3fb799de02a.png">
> > > > > > > 目前 overleaf 上面的模板比较旧，建议按此方案生成 `thesis` 目录然后上传。
> > > > > > 
> > > > > > 
> > > > > > 谢谢， 按您的建议尝试了， 但报错： `Package fduthesis Error: Package "ctex" is too old.`
> > > > > > 直接使用 0.7d 似乎是正常的。
> > > > > 
> > > > > 
> > > > > 模板版本一定是跟发行版版本绑定的，请换到 texlive 2021。
> > > > 
> > > > 
> > > > 谢谢帮助和回复， 但我应该已经使用了 2021， 见下图
> > > > ![image](https://user-images.githubusercontent.com/34390943/146917948-755fd9eb-06f6-48a6-a91d-a4fe735516cf.png)
> > > 
> > > 
> > > 很可惜模板最新版已经修复了这个问题
> > > https://github.com/stone-zeng/fduthesis/blob/6e98af11bd8a3125da5702c40a947f59508b65f9/source/fduthesis.dtx#L3122
> > > 
> > > 你用的不是『最新版』，你用的是发行版的最新版吧？
> > 
> > 
> > 谢谢回复。 我是follow了 stone-zeng 的建议做的， 即直接从github主页下载 .zip 文件后 本地运行 install-win.bat， 然后将生成的 thesis 文件夹上传。 我确认了下， 你刚提到的这句代码在我下载的 fduthesis.dtx 中是有的， 因此我想我下载的应该是 最新版？
> 
> 我用 Overleaf 上的模板，设置 texlive 2021，报的错跟你发的图是一致的。
> 
> 我用 Overleaf 上的模板，设置 texlive 2021，单独上传编译好的 `thesis/fduthesis.cls`，编译没有任何问题。 请参考我的 [Overleaf 链接](https://cn.overleaf.com/9268576289sdxwbtzgpnym)，对比你哪里出了问题。

谢谢。 感谢帮助。 我尝试了你的overleaf页面， 是可行的， 然后我对比了下， 发现原来是我运行了 install-win.bat 后的 thesis 目录下并没有生成 .cls 文件， 我不知道这是否与我本地并没有安装任何 Tex 环境有关。

**Comment by sikouhjw** [comment]
> > > > > > > > <img alt="Screen Shot 2021-12-21 at 18 27 50" width="856" src="https://user-images.githubusercontent.com/18233088/146914633-153b2ee3-be8e-40e9-9e98-e3fb799de02a.png">
> > > > > > > > 目前 overleaf 上面的模板比较旧，建议按此方案生成 `thesis` 目录然后上传。
> > > > > > > 
> > > > > > > 
> > > > > > > 谢谢， 按您的建议尝试了， 但报错： `Package fduthesis Error: Package "ctex" is too old.`
> > > > > > > 直接使用 0.7d 似乎是正常的。
> > > > > > 
> > > > > > 
> > > > > > 模板版本一定是跟发行版版本绑定的，请换到 texlive 2021。
> > > > > 
> > > > > 
> > > > > 谢谢帮助和回复， 但我应该已经使用了 2021， 见下图
> > > > > ![image](https://user-images.githubusercontent.com/34390943/146917948-755fd9eb-06f6-48a6-a91d-a4fe735516cf.png)
> > > > 
> > > > 
> > > > 很可惜模板最新版已经修复了这个问题
> > > > https://github.com/stone-zeng/fduthesis/blob/6e98af11bd8a3125da5702c40a947f59508b65f9/source/fduthesis.dtx#L3122
> > > > 
> > > > 你用的不是『最新版』，你用的是发行版的最新版吧？
> > > 
> > > 
> > > 谢谢回复。 我是follow了 stone-zeng 的建议做的， 即直接从github主页下载 .zip 文件后 本地运行 install-win.bat， 然后将生成的 thesis 文件夹上传。 我确认了下， 你刚提到的这句代码在我下载的 fduthesis.dtx 中是有的， 因此我想我下载的应该是 最新版？
> > 
> > 
> > 我用 Overleaf 上的模板，设置 texlive 2021，报的错跟你发的图是一致的。
> > 我用 Overleaf 上的模板，设置 texlive 2021，单独上传编译好的 `thesis/fduthesis.cls`，编译没有任何问题。 请参考我的 [Overleaf 链接](https://cn.overleaf.com/9268576289sdxwbtzgpnym)，对比你哪里出了问题。
> 
> 谢谢。 感谢帮助。 我尝试了你的overleaf页面， 是可行的， 然后我对比了下， 发现原来是我运行了 install-win.bat 后的 thesis 目录下并没有生成 .cls 文件， 我不知道这是否与我本地并没有安装任何 Tex 环境有关。

安装方法是针对本地发行版的，没安装当然会有问题。

**Comment by TianLin0509** [comment]
> > > > > > > > > <img alt="Screen Shot 2021-12-21 at 18 27 50" width="856" src="https://user-images.githubusercontent.com/18233088/146914633-153b2ee3-be8e-40e9-9e98-e3fb799de02a.png">
> > > > > > > > > 目前 overleaf 上面的模板比较旧，建议按此方案生成 `thesis` 目录然后上传。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 谢谢， 按您的建议尝试了， 但报错： `Package fduthesis Error: Package "ctex" is too old.`
> > > > > > > > 直接使用 0.7d 似乎是正常的。
> > > > > > > 
> > > > > > > 
> > > > > > > 模板版本一定是跟发行版版本绑定的，请换到 texlive 2021。
> > > > > > 
> > > > > > 
> > > > > > 谢谢帮助和回复， 但我应该已经使用了 2021， 见下图
> > > > > > ![image](https://user-images.githubusercontent.com/34390943/146917948-755fd9eb-06f6-48a6-a91d-a4fe735516cf.png)
> > > > > 
> > > > > 
> > > > > 很可惜模板最新版已经修复了这个问题
> > > > > https://github.com/stone-zeng/fduthesis/blob/6e98af11bd8a3125da5702c40a947f59508b65f9/source/fduthesis.dtx#L3122
> > > > > 
> > > > > 你用的不是『最新版』，你用的是发行版的最新版吧？
> > > > 
> > > > 
> > > > 谢谢回复。 我是follow了 stone-zeng 的建议做的， 即直接从github主页下载 .zip 文件后 本地运行 install-win.bat， 然后将生成的 thesis 文件夹上传。 我确认了下， 你刚提到的这句代码在我下载的 fduthesis.dtx 中是有的， 因此我想我下载的应该是 最新版？
> > > 
> > > 
> > > 我用 Overleaf 上的模板，设置 texlive 2021，报的错跟你发的图是一致的。
> > > 我用 Overleaf 上的模板，设置 texlive 2021，单独上传编译好的 `thesis/fduthesis.cls`，编译没有任何问题。 请参考我的 [Overleaf 链接](https://cn.overleaf.com/9268576289sdxwbtzgpnym)，对比你哪里出了问题。
> > 
> > 
> > 谢谢。 感谢帮助。 我尝试了你的overleaf页面， 是可行的， 然后我对比了下， 发现原来是我运行了 install-win.bat 后的 thesis 目录下并没有生成 .cls 文件， 我不知道这是否与我本地并没有安装任何 Tex 环境有关。
> 
> 安装方法是针对本地发行版的，没安装当然会有问题。

好的， 感谢两位的帮助。 我就直接复制了一份你刚提供的 overleaf中的 .cls 文件到我的项目下， 这算是使用了最新版了吗？

**Comment by sikouhjw** [comment]
> > > > > > > > > > <img alt="Screen Shot 2021-12-21 at 18 27 50" width="856" src="https://user-images.githubusercontent.com/18233088/146914633-153b2ee3-be8e-40e9-9e98-e3fb799de02a.png">
> > > > > > > > > > 目前 overleaf 上面的模板比较旧，建议按此方案生成 `thesis` 目录然后上传。
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 谢谢， 按您的建议尝试了， 但报错： `Package fduthesis Error: Package "ctex" is too old.`
> > > > > > > > > 直接使用 0.7d 似乎是正常的。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 模板版本一定是跟发行版版本绑定的，请换到 texlive 2021。
> > > > > > > 
> > > > > > > 
> > > > > > > 谢谢帮助和回复， 但我应该已经使用了 2021， 见下图
> > > > > > > ![image](https://user-images.githubusercontent.com/34390943/146917948-755fd9eb-06f6-48a6-a91d-a4fe735516cf.png)
> > > > > > 
> > > > > > 
> > > > > > 很可惜模板最新版已经修复了这个问题
> > > > > > https://github.com/stone-zeng/fduthesis/blob/6e98af11bd8a3125da5702c40a947f59508b65f9/source/fduthesis.dtx#L3122
> > > > > > 
> > > > > > 你用的不是『最新版』，你用的是发行版的最新版吧？
> > > > > 
> > > > > 
> > > > > 谢谢回复。 我是follow了 stone-zeng 的建议做的， 即直接从github主页下载 .zip 文件后 本地运行 install-win.bat， 然后将生成的 thesis 文件夹上传。 我确认了下， 你刚提到的这句代码在我下载的 fduthesis.dtx 中是有的， 因此我想我下载的应该是 最新版？
> > > > 
> > > > 
> > > > 我用 Overleaf 上的模板，设置 texlive 2021，报的错跟你发的图是一致的。
> > > > 我用 Overleaf 上的模板，设置 texlive 2021，单独上传编译好的 `thesis/fduthesis.cls`，编译没有任何问题。 请参考我的 [Overleaf 链接](https://cn.overleaf.com/9268576289sdxwbtzgpnym)，对比你哪里出了问题。
> > > 
> > > 
> > > 谢谢。 感谢帮助。 我尝试了你的overleaf页面， 是可行的， 然后我对比了下， 发现原来是我运行了 install-win.bat 后的 thesis 目录下并没有生成 .cls 文件， 我不知道这是否与我本地并没有安装任何 Tex 环境有关。
> > 
> > 
> > 安装方法是针对本地发行版的，没安装当然会有问题。
> 
> 好的， 感谢两位的帮助。 我就直接复制了一份你刚提供的 overleaf中的 .cls 文件到我的项目下， 这算是使用了最新版了吗？

是的，是使用了最新版。

**Comment by TianLin0509** [comment]
> > > > > > > > > > > <img alt="Screen Shot 2021-12-21 at 18 27 50" width="856" src="https://user-images.githubusercontent.com/18233088/146914633-153b2ee3-be8e-40e9-9e98-e3fb799de02a.png">
> > > > > > > > > > > 目前 overleaf 上面的模板比较旧，建议按此方案生成 `thesis` 目录然后上传。
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 谢谢， 按您的建议尝试了， 但报错： `Package fduthesis Error: Package "ctex" is too old.`
> > > > > > > > > > 直接使用 0.7d 似乎是正常的。
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 模板版本一定是跟发行版版本绑定的，请换到 texlive 2021。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 谢谢帮助和回复， 但我应该已经使用了 2021， 见下图
> > > > > > > > ![image](https://user-images.githubusercontent.com/34390943/146917948-755fd9eb-06f6-48a6-a91d-a4fe735516cf.png)
> > > > > > > 
> > > > > > > 
> > > > > > > 很可惜模板最新版已经修复了这个问题
> > > > > > > https://github.com/stone-zeng/fduthesis/blob/6e98af11bd8a3125da5702c40a947f59508b65f9/source/fduthesis.dtx#L3122
> > > > > > > 
> > > > > > > 你用的不是『最新版』，你用的是发行版的最新版吧？
> > > > > > 
> > > > > > 
> > > > > > 谢谢回复。 我是follow了 stone-zeng 的建议做的， 即直接从github主页下载 .zip 文件后 本地运行 install-win.bat， 然后将生成的 thesis 文件夹上传。 我确认了下， 你刚提到的这句代码在我下载的 fduthesis.dtx 中是有的， 因此我想我下载的应该是 最新版？
> > > > > 
> > > > > 
> > > > > 我用 Overleaf 上的模板，设置 texlive 2021，报的错跟你发的图是一致的。
> > > > > 我用 Overleaf 上的模板，设置 texlive 2021，单独上传编译好的 `thesis/fduthesis.cls`，编译没有任何问题。 请参考我的 [Overleaf 链接](https://cn.overleaf.com/9268576289sdxwbtzgpnym)，对比你哪里出了问题。
> > > > 
> > > > 
> > > > 谢谢。 感谢帮助。 我尝试了你的overleaf页面， 是可行的， 然后我对比了下， 发现原来是我运行了 install-win.bat 后的 thesis 目录下并没有生成 .cls 文件， 我不知道这是否与我本地并没有安装任何 Tex 环境有关。
> > > 
> > > 
> > > 安装方法是针对本地发行版的，没安装当然会有问题。
> > 
> > 
> > 好的， 感谢两位的帮助。 我就直接复制了一份你刚提供的 overleaf中的 .cls 文件到我的项目下， 这算是使用了最新版了吗？
> 
> 是的，是使用了最新版。

谢谢， 但我发现 按新版的话有这样一个问题， 似乎在你刚提供的 overleaf上也有一样的情况， 就是会出现 形如 "FF1A" 这样的字符， 详见下图， 这是什么问题呢？

![image](https://user-images.githubusercontent.com/34390943/146930105-bd712fb3-e827-44e6-a493-76d01711e435.png)

**Comment by sikouhjw** [comment]
> 谢谢， 但我发现 按新版的话有这样一个问题， 似乎在你刚提供的 overleaf上也有一样的情况， 就是会出现 形如 "FF1A" 这样的字符， 详见下图， 这是什么问题呢？
> 
> ![image](https://user-images.githubusercontent.com/34390943/146930105-bd712fb3-e827-44e6-a493-76d01711e435.png)

1. `"FF1A` 是冒号的 unicode 码
2. 模板用输入 unicode 码的形式输出标点符号
3. 这些内容放在了 `fduthesis.def` 内
4. 我之前没上传 `fduthesis.def`
5. 我现在上传了 `thesis` 文件夹内的所有文件，[点击查看](https://cn.overleaf.com/1614813853hdzpgpycpngt)

**Comment by TianLin0509** [comment]
非常感谢， 我编译了一下 ， 没有任何问题了。 

我想也许可以在 readme 中分享下这个 overleaf 网址， 对像我这样一直只用overleaf 的学生而言会很方便友好。

再次感谢你的时间和帮助

**Comment by sikouhjw** [comment]
> 非常感谢， 我编译了一下 ， 没有任何问题了。
> 
> 我想也许可以在 readme 中分享下这个 overleaf 网址， 对像我这样一直只用overleaf 的学生而言会很方便友好。
> 
> 再次感谢你的时间和帮助

还是等曾老师更新吧

**Comment by stone-zeng** [comment]
打包了一个 zip，见 #225

（话说你们回复的时候要不要考虑把之前的删一下呀，这十层嵌套就很离谱😂）

**Comment by TianLin0509** [comment]
> > 非常感谢， 我编译了一下 ， 没有任何问题了。
> > 我想也许可以在 readme 中分享下这个 overleaf 网址， 对像我这样一直只用overleaf 的学生而言会很方便友好。
> > 再次感谢你的时间和帮助
> 
> 还是等曾老师更新吧

奇怪的问题出现了， 在试图删除 中图分类号时， https://github.com/stone-zeng/fduthesis/issues/133 中的方式失效了。 

下午在 0.7d版本时是奏效的。 

我在你分享的overleaf的导言区也加入了

```
\ExplSyntaxOn
\cs_set_eq:NN \__fdu_clc:nn \use_none:nn
\ExplSyntaxOff
```

但似乎无法删去中图分类号了。

似乎与版本的更新相关？

**Comment by TianLin0509** [comment]
> 打包了一个 zip，见 #225
> 
> （话说你们回复的时候要不要考虑把之前的删一下呀，这十层嵌套就很离谱😂）

谢谢了 0.0 哈哈，确实， 我滑到下面滑动了半天 这就去删除

**Comment by stone-zeng** [comment]
不同的问题请提新的 issue 🙏
