### ISSUE TITLE
无法删去中图分类号

### ISSUE THREAD

**Issue by stone-zeng** [stone-zeng/fduthesis#226]
奇怪的问题出现了， 在试图删除 中图分类号时， https://github.com/stone-zeng/fduthesis/issues/133 中的方式失效了。 

下午在 0.7d版本时是奏效的。 

我在你分享的overleaf的导言区也加入了

```
\ExplSyntaxOn
\cs_set_eq:NN \__fdu_clc:nn \use_none:nn
\ExplSyntaxOff
```

但似乎无法删去中图分类号了。

似乎与版本的更新相关？

_Originally posted by @TianLin0509 in https://github.com/stone-zeng/fduthesis/issues/224#issuecomment-998787169_

**Comment by stone-zeng** [comment]
```tex
\ExplSyntaxOn
\cs_set_eq:NN \__fdu_clc_jel:nn \use_none:nn
\ExplSyntaxOff
```

**Comment by stone-zeng** [comment]
考虑不设置 CLC 时不再显示该条目。

**Comment by TianLin0509** [comment]
直接解决 只能说曾老师牛逼！
