### ISSUE TITLE
overleaf中使用Xelatex手动连续编译两次之后证毕符号还是错位的，该如何解决？

### ISSUE THREAD

**Issue by ssssylviaaa** [stone-zeng/fduthesis#230]

**Comment by sikouhjw** [comment]
> > ![图片](https://user-images.githubusercontent.com/49770925/149486369-5031f23a-cd5d-4a77-8977-8f9b5d53632f.png) 请提供 mwe。
> 
> ![image](https://user-images.githubusercontent.com/37822963/149609894-7c238507-3ec2-4d5b-991f-1cd711ccd935.png) 我用的是"[https://www.overleaf.com/latex/templates/fduthesis-latex-thesis-template-for-fudan-university/svtdhhstkmkt"这个链接里的模板](https://www.overleaf.com/latex/templates/fduthesis-latex-thesis-template-for-fudan-university/svtdhhstkmkt%22%E8%BF%99%E4%B8%AA%E9%93%BE%E6%8E%A5%E9%87%8C%E7%9A%84%E6%A8%A1%E6%9D%BF)

哪里错位了？

**Comment by ssssylviaaa** [comment]
> > > ![图片](https://user-images.githubusercontent.com/49770925/149486369-5031f23a-cd5d-4a77-8977-8f9b5d53632f.png) 请提供 mwe。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/37822963/149609894-7c238507-3ec2-4d5b-991f-1cd711ccd935.png) 我用的是"[https://www.overleaf.com/latex/templates/fduthesis-latex-thesis-template-for-fudan-university/svtdhhstkmkt"这个链接里的模板](https://www.overleaf.com/latex/templates/fduthesis-latex-thesis-template-for-fudan-university/svtdhhstkmkt%22%E8%BF%99%E4%B8%AA%E9%93%BE%E6%8E%A5%E9%87%8C%E7%9A%84%E6%A8%A1%E6%9D%BF)
> 
> 哪里错位了？

![image](https://user-images.githubusercontent.com/37822963/149610110-dfa2be0d-4825-4f54-a0e4-29667c396f89.png)
这样看更明显

**Comment by sikouhjw** [comment]
`texdoc ntheorem`, sec 2.6 Setting End Marks
> Note that there must be no empty line in the input before the `\end{theorem}`,
since then, the end mark is ignored (cf. Theorem 3 in Section 4).

`\end{proof}` 前面不要有空行。

**Comment by ssssylviaaa** [comment]
> `texdoc ntheorem`, sec 2.6 Setting End Marks
> 
> > Note that there must be no empty line in the input before the `\end{theorem}`,
> > since then, the end mark is ignored (cf. Theorem 3 in Section 4).
> 
> `\end{proof}` 前面不要有空行。

解决了！感谢！！！
