### ISSUE TITLE
目录的问题

### ISSUE THREAD

**Issue by zhvn100** [stone-zeng/fduthesis#249]
生成的目录，在图片目录、表格目录、摘要处没有点，下面这张图画红色横线的地方。
![image](https://user-images.githubusercontent.com/56665570/159126560-97d46afd-cff5-4846-8440-375599da6f2b.png)

**Comment by sikouhjw** [comment]
LaTeX 的默认风格就是这样的，如果审查不通过，应该早改了。

**Comment by stone-zeng** [comment]
#148
