### ISSUE TITLE
准备示例文档，以及发布至 CTAN

### ISSUE THREAD

**Issue by Stone-Zeng** [Stone-Zeng/fduthesis#25]
考虑使用 `l3build`。

**Comment by nanmu42** [comment]
CTAN的人看到这样的作品一定会很开心的。

Zeng Xiangdong <notifications@github.com>于2017年12月19日周二 下午6:20写道：

**Comment by Stone-Zeng** [comment]
考虑再增加一个扁平化安装的压缩包（或者叫绿色版），包含

- 用户文档
- 文档类
- 配置文件
- 校名 logo
- 空白模板
- 编译脚本 / makefile
- LICENSE

其他东西，比如 dtx 源文件就不需要了。
