### ISSUE TITLE
宏包版本检查似乎存在问题

### ISSUE THREAD

**Issue by PrinzLast** [stone-zeng/fduthesis#252]
## 描述问题

配置好编译方式为xelatex+biblatex，用VSCode中的Texlive插件调用。

编译器报错：

Package fduthesis: Packa
ge "ctex" is too old.
(fduthesis)	The fduthesis class only supports "ctex" with a
(fduthesis)	version
(fduthesis)	higher than v2.4.10.
(fduthesis)	
(fduthesis)	Please update an up-to-date version of it using
(fduthesis)	your
(fduthesis)	TeX package manager or from CTAN.

实际已通过MikTex安装ctex v2.5.8，经测试对fontspec包和Unicode math包的版本检查亦存在问题，注释fduthesis.cls文件第239-241行：
\__fdu_check_package:nnn { ctex         } { 2017/08/07 } { 2.4.10 }
\__fdu_check_package:nnn { fontspec     } { 2017/09/22 } { 2.6e   }
\__fdu_check_package:nnn { unicode-math } { 2017/11/18 } { 0.8i   }
可正常编译出pdf文档，希望确定实际问题出在何处。

## 编译环境

- 操作系统
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
- TeX 发行版
  - [ ] TeX Live 2021
  - [x] MiKTeX 21.12
- 编译方式
  - [x] XeLaTeX
  - [ ] LuaLaTeX
- `fduthesis` 获取方式：
  - [x] 发行版自带
  - [ ] 通过 GitHub Releases 下载（最新发布版本）
  - [ ] 通过 `git clone` 下载（开发版本）
- `fduthesis` 版本：v0.7e
- 采用VSCode+Texlive

**Comment by yetiansh** [comment]
参考issue [223](https://github.com/stone-zeng/fduthesis/issues/223)

**Comment by PrinzLast** [comment]
感谢，是我看漏了
