### ISSUE TITLE
参考文献无法正常显示

### ISSUE THREAD

**Issue by nikoHu** [stone-zeng/fduthesis#258]
您好，我使用您的模板时，参考文献报错了。重装latex之后，依然报错。报错信息如下：
This is BibTeX, Version 0.99d (TeX Live 2022)
The top-level auxiliary file: niko.aux
I couldn't open style file gbt7714-unsrt.bst
---line 19 of file niko.aux
 : \bibstyle{gbt7714-unsrt
 :                        }
I'm skipping whatever remains of this command
I found no style file---while reading file niko.aux
(There were 2 error messages)
Process exited with error(s)
希望能帮忙解决一下，谢谢！

**Comment by note286** [comment]
贴一下最小工作示例，正常不会出现`gbt7714-unsrt`的，代码里都没有。

**Comment by stone-zeng** [comment]
请使用最新版的模板：

<img width="767" alt="Screen Shot 2022-06-10 at 20 36 58" src="https://user-images.githubusercontent.com/18233088/173065542-ddd209e4-02e9-40b3-a1a4-2ea4176ba5d3.png">

**Comment by nikoHu** [comment]
谢谢，按照您的方法解决了。编译之前似乎要先F8执行下Bibliography
