### ISSUE TITLE
参考文献间距调整的问题

### ISSUE THREAD

**Issue by Aphroditefang** [stone-zeng/fduthesis#268]
请问如何调整参考文献的间距吖？

**Comment by note286** [comment]
请阅读`biblatex-gb7714-2015.pdf`，搜索`文献表竖直间距控制`。

**Comment by Aphroditefang** [comment]
![image](https://user-images.githubusercontent.com/34327524/184326027-ceb0b071-b229-45f3-a8eb-30a7dec740e5.png)
不知道是我的问题还是?

**Comment by note286** [comment]
[CTAN: Package biblatex-gb7714-2015](https://www.ctan.org/pkg/biblatex-gb7714-2015)

**Comment by note286** [comment]
这是PDF，请点击右上角的`Download`。

**Comment by xkwxdyy** [comment]
安装 TeXLive 的话直接 `texdoc` 不好吗

**Comment by Aphroditefang** [comment]
看了，但是我是在overleaf上编辑的。

**Comment by sikouhjw** [comment]
参考 https://github.com/sikouhjw/gdutthesis/commit/dd2b275e53a6ffec68e26b4b767e31a789a804a0

**Comment by note286** [comment]
那我也贴个我的项目代码：

https://github.com/note286/xduts/blob/c79d8c45749033d5f325dea201a10579e2153cfe/xduts.dtx#L4953-L4973

**Comment by stone-zeng** [comment]
总结一下，办法就是用 `\setlength` 修改一下 `\bibsep` (`bibtex`) 或 `\bibitemsep` (`biblatex`) 这两个长度变量。作为模板我觉得用默认值就够了，有需要可以自行调整。
