### ISSUE TITLE
增加空白页提示

### ISSUE THREAD

**Issue by stone-zeng** [stone-zeng/fduthesis#27]
比如“This page is intentionally left blank.”

**Comment by zepinglee** [comment]
有没有办法在 PDF 阅读器中显示这句话，但是打印时并不会打出来？

**Comment by Stone-Zeng** [comment]
可以的。搜了一下，这个是 PDF 的 OCG (Op­tional Con­tent Groups) 功能，有不少包支持的，比如 `ocg-p`、`ocgx`、`ocgx2` （这货刚刚搬到 GitLab 去了……）等等。但具体怎么用要看文档了。

**Comment by stone-zeng** [comment]
Track in #87.
