### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by blackboxo** [stone-zeng/fduthesis#274]
## 描述问题

XeLatex 编译demo报错
Package hyperref Warning: Rerun to get /PageLabels entry.

! Undefined control sequence.
\template code > fdu/cover/cover-i ...du_vspace:c 
                                                  {l_@@/cover-i/top_skip}\cl...
l.241 \begin{document}

预期结果：

实际结果：

截图：

复现上述问题的代码：

```TeX
\documentclass{fduthesis}
\begin{document}
文字
\end{document}
```

## 编译环境

- 操作系统
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
- TeX 发行版
  - [x] TeX Live 2022
  - [ ] MiKTeX 22.8
- 编译方式
  - [x] XeLaTeX
  - [ ] LuaLaTeX
- `fduthesis` 获取方式：
  - [ ] 发行版自带
  - [ ] 通过 GitHub Releases 下载（最新发布版本）
  - [x] 通过 `git clone` 下载（开发版本）
  - [ ] 在 Overleaf 上使用
- `fduthesis` 版本：v0.8

**Comment by note286** [comment]
Windows 10，TeX Live 2022，`fduthesis .cls` `0.8 2022-09-04 12:00:00Z`编译无问题。
