### ISSUE TITLE
请问一下参考文献的引用是上角标，能改成和正常字体等高的普通cite的格式么

### ISSUE THREAD

**Issue by aperoe** [stone-zeng/fduthesis#275]
## 描述问题

预期结果：

实际结果：

截图：

复现上述问题的代码：

```TeX
\documentclass{fduthesis}
\begin{document}
文字
\end{document}
```

## 编译环境

- 操作系统
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
- TeX 发行版
  - [ ] TeX Live 2022
  - [ ] MiKTeX 22.8
- 编译方式
  - [ ] XeLaTeX
  - [ ] LuaLaTeX
- `fduthesis` 获取方式：
  - [ ] 发行版自带
  - [ ] 通过 GitHub Releases 下载（最新发布版本）
  - [ ] 通过 `git clone` 下载（开发版本）
  - [x] 在 Overleaf 上使用
- `fduthesis` 版本：v0.8

**Comment by syvshc** [comment]
![image](https://user-images.githubusercontent.com/38098591/208233271-0e8a3d52-8839-4a5a-a07f-7c1faee600d5.png)

**Comment by aperoe** [comment]
感谢！ 自己改了很久都没弄好！ 谢谢！！

-----原始邮件-----
发件人:syvshc ***@***.***>
发送时间:2022-12-17 16:30:36 (星期六)
收件人: stone-zeng/fduthesis ***@***.***>
抄送: aperoe ***@***.***>, Author ***@***.***>
主题: Re: [stone-zeng/fduthesis] 请问一下参考文献的引用是上角标，能改成和正常字体等高的普通cite的格式么 (Issue #275)
