### ISSUE TITLE
页眉如何分单双页显示

### ISSUE THREAD

**Issue by funnyseaman** [stone-zeng/fduthesis#290]
页眉同时显示左页眉和右页眉，请问如何分单双页显示左页眉和右页眉？

**Comment by stone-zeng** [comment]
<img width="862" alt="Screenshot 2023-02-14 at 18 48 53" src="https://user-images.githubusercontent.com/18233088/218713921-9b702397-8087-4981-9e0a-f8b5f4ca390e.png">
