### ISSUE TITLE
siunitx package problem

### ISSUE THREAD

**Issue by wenbin-liu** [stone-zeng/fduthesis#302]
## 描述问题
最新的版本v0.9和siunitx 包冲突。无法使用。

使用的环境为overleaf并使用默认模板

截图：
![image](https://user-images.githubusercontent.com/25171141/236670474-30c4b615-9910-4b3e-b35c-a680d8ed945c.png)

复现上述问题的代码：

```TeX
\documentclass{fduthesis}
\usepackage{siunitx}
\begin{document}
文字
\end{document}
```

## 编译环境

- 操作系统
  - [ ] Windows
  - [ ] macOS
  - [ ] Ubuntu
- TeX 发行版
  - [ ] TeX Live 2022
  - [ ] MiKTeX 22.10
- 编译方式
  - [ ] XeLaTeX
  - [ ] LuaLaTeX
- `fduthesis` 获取方式：
  - [ ] 发行版自带
  - [ ] 通过 GitHub Releases 下载（最新发布版本）
  - [ ] 通过 `git clone` 下载（开发版本）
  - [x] 在 Overleaf 上使用
- `fduthesis` 版本：v0.9

**Comment by ajz34** [comment]
我在最近编写论文时也遇到类似的问题，感谢修复！

在使用 dcolumn package 时遇到相同的报错；fduthesis 版本 v0.9，随 TexLive 2023 发行。
在有 v0.9a 修复后，可以通过 tlmgr 或 tlshell 更新到这个版本，就解决问题了。
