### ISSUE TITLE
参考文献 题目中的公式没有被识别

### ISSUE THREAD

**Issue by LucifierZ** [stone-zeng/fduthesis#307]
## 描述问题
${Z}_{N}$ Berry phase and symmetry-protected
topological phases of the SU($N$) antiferromagnetic Heisenberg chain[J/OL].
这种标题就直接显示美元符号了
预期结果：

实际结果：

截图：

复现上述问题的代码：

```TeX
\documentclass{fduthesis}
\begin{document}
文字
\end{document}
```

## 编译环境

- 操作系统
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
- TeX 发行版
  - [x] TeX Live 2023
  - [ ] MiKTeX 23.5
- 编译方式
  - [x] XeLaTeX
  - [ ] LuaLaTeX
- `fduthesis` 获取方式：
  - [ ] 发行版自带
  - [ ] 通过 GitHub Releases 下载（最新发布版本）
  - [x] 通过 `git clone` 下载（开发版本）
  - [ ] 在 Overleaf 上使用
- `fduthesis` 版本：v0.9a

**Comment by stone-zeng** [comment]
公式用 `{...}` 扩起来：`{$Z_N$}`
