### ISSUE TITLE
来自 arXiv 引用的显示问题

### ISSUE THREAD

**Issue by XiaosuWang** [stone-zeng/fduthesis#308]
请问如何修改，可以出现预期结果的显示，而不是实际结果中的显示？

在bib文件中该entry是：

```bib
@article{cutoff,
  title={A Simple but Tough-to-Beat Data Augmentation Approach for Natural Language Understanding and Generation},
  author={Dinghan Shen and Ming Zheng and Yelong Shen and Yanru Qu and Weizhu Chen},
  journal={arXiv preprint arXiv:2009.13818},
  year={2020}
}
```

预期结果：(加粗的地方是希望出现但是没出现的)
SHEN D, ZHENG M, SHEN Y, et al. A simple but tough-to-beat data augmentation approach for natural language understanding and generation[**J**]. **arXiv preprint arXiv:2009.13818,** 2020.

实际结果：
SHEN D, ZHENG M, SHEN Y, et al. A simple but tough-to-beat data augmentation approach for natural language understanding and generation[A]. 2020.

截图：

## 编译环境

- 操作系统
  - [ ] Windows
  - [x] macOS
  - [ ] Ubuntu
- TeX 发行版
  - [x] TeX Live 2023
  - [ ] MiKTeX 23.5
- 编译方式
  - [x] XeLaTeX
  - [ ] LuaLaTeX
- `fduthesis` 获取方式：
  - [ ] 发行版自带
  - [x] 通过 GitHub Releases 下载（最新发布版本）
  - [ ] 通过 `git clone` 下载（开发版本）
  - [ ] 在 Overleaf 上使用
- `fduthesis` 版本：v0.9a

**Comment by sikouhjw** [comment]
https://github.com/zepinglee/gbt7714-bibtex-style/issues/134

**Comment by XiaosuWang** [comment]
> [zepinglee/gbt7714-bibtex-style#134](https://github.com/zepinglee/gbt7714-bibtex-style/issues/134)

请问能给一个可以输出预期结果的解决方案吗？#134似乎没有给出解决方法，谢谢啊

**Comment by sikouhjw** [comment]
> 请问能给一个可以输出预期结果的解决方案吗？#134似乎没有给出解决方法，谢谢啊

下载更新过的宏包及配套文件，放工作目录下。

**Comment by XiaosuWang** [comment]
> > 请问能给一个可以输出预期结果的解决方案吗？#134似乎没有给出解决方法，谢谢啊
> 
> 下载更新过的宏包及配套文件，放工作目录下。

不好意思啊，还是没理解项目 https://github.com/zepinglee/gbt7714-bibtex-style/ 和 fduthesis 项目的关系，可能是因为我个人对Tex的知识缺陷，但是赶论文时间有点紧，请问有那种一步一步指导如何做的指南吗？就是我把 https://github.com/zepinglee/gbt7714-bibtex-style/ 项目的最新版本下载到本地后，我应该把什么文件放置到什么位置，然后更新什么文件中的什么内容，就可以实现更新了，类似这种教程，谢谢啊

**Comment by XiaosuWang** [comment]
关于这个问题其实有一个比较傻瓜的做法，就是如下写一个reference，目前的状态已经可以实现预期结果的输出：
@article{cutoff,
  title={A Simple but Tough-to-Beat Data Augmentation Approach for Natural Language Understanding and Generation},
  author={Dinghan Shen and Ming Zheng and Yelong Shen and Yanru Qu and Weizhu Chen},
  journal={{arXiv preprint arXiv:2009.13818}},
  year={2020}
}
就是journal 的值多加一个大括号即可。
更专业的修改见上面https://github.com/stone-zeng/fduthesis/issues/308#issuecomment-1663252921的回答！

**Comment by sikouhjw** [comment]
> 不好意思啊，还是没理解项目 https://github.com/zepinglee/gbt7714-bibtex-style/ 和 fduthesis 项目的关系

fduthesis 调用 gbt7714 宏包来输出参考文献。

> 就是我把 https://github.com/zepinglee/gbt7714-bibtex-style/ 项目的最新版本下载到本地后，我应该把什么文件放置到什么位置，然后更新什么文件中的什么内容，就可以实现更新了，类似这种教程，谢谢啊

下载最新的 [gbt7714-numerical.bst](https://github.com/zepinglee/gbt7714-bibtex-style/blob/master/gbt7714-numerical.bst)，放到与你 tex 文件同级的文件夹下面

**Comment by XiaosuWang** [comment]
> > 不好意思啊，还是没理解项目 https://github.com/zepinglee/gbt7714-bibtex-style/ 和 fduthesis 项目的关系
> 
> fduthesis 调用 gbt7714 宏包来输出参考文献。
> 
> > 就是我把 https://github.com/zepinglee/gbt7714-bibtex-style/ 项目的最新版本下载到本地后，我应该把什么文件放置到什么位置，然后更新什么文件中的什么内容，就可以实现更新了，类似这种教程，谢谢啊
> 
> 下载最新的 [gbt7714-numerical.bst](https://github.com/zepinglee/gbt7714-bibtex-style/blob/master/gbt7714-numerical.bst)，放到与你 tex 文件同级的文件夹下面

请问要设置 \fdusetup{} 中对应的参数吗？
我把 gbt7714-numerical.bst 放到 我本地论文 main.tex（该文件中包含了 \documentclass[twoside, type=doctor]{fduthesis}、\fdusetup{...}等一系列命令） 同级目录下，并没有起作用。

**Comment by sikouhjw** [comment]
> 请问要设置 \fdusetup{} 中对应的参数吗？ 我把 gbt7714-numerical.bst 放到 我本地论文 main.tex（该文件中包含了 \documentclass[twoside, type=doctor]{fduthesis}、\fdusetup{...}等一系列命令） 同级目录下，并没有起作用。

你遇到这个问题说明你用的是 bibtex + `gbt7714-numerical.bst`。

你现在的问题是你没有清除辅助文件再次编译。请你将所有辅助文件删除（`.aux`, `.bbl`, `.log` ...），再重新编译。

**Comment by XiaosuWang** [comment]
> > 请问要设置 \fdusetup{} 中对应的参数吗？ 我把 gbt7714-numerical.bst 放到 我本地论文 main.tex（该文件中包含了 \documentclass[twoside, type=doctor]{fduthesis}、\fdusetup{...}等一系列命令） 同级目录下，并没有起作用。
> 
> 你遇到这个问题说明你用的是 bibtex + `gbt7714-numerical.bst`。
> 
> 你现在的问题是你没有清除辅助文件再次编译。请你将所有辅助文件删除（`.aux`, `.bbl`, `.log` ...），再重新编译。

删除所有辅助文件后又试了一下，还是没能成功输出预期结果

**Comment by sikouhjw** [comment]
> 删除所有辅助文件后又试了一下，还是没能成功输出预期结果

注意，你的预期是输出 `arXiv preprint arXiv:2009.13818`，而我给的回答是输出 `doi`。

事实上给出的链接只要能找到参考文献即可，那么 doi 就足够了。因此你要在 bib 里补充 doi。
