### ISSUE TITLE
支持 pdfTeX 和 pTeX-ng

### ISSUE THREAD

**Issue by stone-zeng** [stone-zeng/fduthesis#31]
当前仅支持 XeTeX 和 LuaTeX，可以考虑支持其他引擎。具体见分支 [pdftex](https://github.com/Stone-Zeng/fduthesis/tree/pdftex) 和 [ptex-ng](https://github.com/Stone-Zeng/fduthesis/tree/ptex-ng)。

主要的困难自然是字体配置。

**Comment by zepinglee** [comment]
ctex 在 mac 下都不支持 pdftex，我觉得 这个可以免了
