### ISSUE TITLE
章节标题间距处理

### ISSUE THREAD

**Issue by stone-zeng** [stone-zeng/fduthesis#34]
物理系本科生毕业论文格式要求：

> **标题的层次**：标题序号一律用阿拉伯数字编排，序号与文字间空一格。
>
> - 一级：第 1 章，居中，黑体， 3 号；占 3 行
> - 二级：1.1，居中，宋体，小 4 号；占 2 行
> - 三级：1.1.2，顶格，黑体，5 号；占 2 行
> - 四级：1.，缩 2 格，楷体，5 号；占 1 行
>
> 两级及以上标题连排时，每加一级减 1 行，例如章与节连排时共占 4 行。

目前发现实现起来比较困难。主要问题有：

1.  间距很难与行距保持精确一致。
2. 页面开头的节标题没有 `beforeskip`。
3. 对于连排标题，这里采用了类似 `xpeek` 宏包的手段，只能处理字面上的 `\section` 等，如果有 `\include` 等操作将失效。同时这种处理只能改变两个标题之间的距离，貌似效果不会很好。
4. 如果一二三级连排，占据 5 行；一二三四级连排，同样占据 5 行。很奇怪。

**Comment by zepinglee** [comment]
这里说的“占 3 行”，应该是基于网格系统的方式吧？（否则字号都不一样，怎么定义行距）

**Comment by Stone-Zeng** [comment]
是的，然而 TeX 里面使用网格系统并不很方便，要用 `grid` 之类的宏包。关键是系里还要求 Word 里面关闭文档网格，这就尴尬了。(其实我猜是他们根本不知道文档网格是干什么的)

**Comment by Jeff-Tian** [comment]
请问如何缩小这个间距：

![image](https://user-images.githubusercontent.com/3367820/95674690-66330200-0be4-11eb-8a2b-346a757342d1.png)

**Comment by zepinglee** [comment]
> 请问如何缩小这个间距：
> 
> ![image](https://user-images.githubusercontent.com/3367820/95674690-66330200-0be4-11eb-8a2b-346a757342d1.png)

`chapter/beforeskip`

**Comment by Jeff-Tian** [comment]
感谢！小白求问具体设置，比如要设置每章的标题端前距离为17像素，应该怎么写？

**Comment by Jeff-Tian** [comment]
试下来可以在导言区加入：

```
\ctexset{chapter/beforeskip=0pt}
```

**Comment by aaronhd** [comment]
问下 各位，四级标题如何出现数字  比如1.1.1.1？  目前的模板四级标题没有数字了

**Comment by stone-zeng** [comment]
> 问下 各位，四级标题如何出现数字 比如1.1.1.1？ 目前的模板四级标题没有数字了

```tex
\setcounter{secnumdepth}{3}
```

（不相关的问题请新开 issue 提问，以方便搜索和管理）
