### ISSUE TITLE
更新 macOS 下的字体配置

### ISSUE THREAD

**Issue by Stone-Zeng** [Stone-Zeng/fduthesis#36]
影响 `cjk-font=mac` 选项。参考 CTeX-org/ctex-kit#351。

**Comment by Liam0205** [comment]
没用 CTeX 一套东西？

**Comment by zepinglee** [comment]
Pingfang 肯定要改成 Heiti SC 的

**Comment by Stone-Zeng** [comment]
当时的考虑是，模板把 fandol 设为了默认字体，但是 `ctex` 里面 `fontset` 作为宏包/文档类选项，会在调用时起作用，所以无论用户是不是修改了字体，fandol 总会调用的。如果用户没有装 fandol，那就没法编译了。而且额外调用字体可能还有一定开销（后来做过 benchmark，但基本可以忽略）。

另一方面，`ctex` 在不同系统下的处理略有不同，比如 Windows 里中易宋体的粗体就对应了中易黑体，而 macOS 里宋体本身就有粗体形式可以直接用。所以我就直接重定义了 `\setmainfont`、`\setCJKmainfont` 等命令，让它们只负责处理字体信息，然后在 `\begin{document}` 的地方实际调入字体。

总感觉另起炉灶有一些画蛇添足，但也没想到更好的办法。

**Comment by Liam0205** [comment]
可以预先 fontset=none

**Comment by Stone-Zeng** [comment]
就是这么做的：https://github.com/Stone-Zeng/fduthesis/blob/master/source/fduthesis.dtx#L2852

**Comment by zepinglee** [comment]
我觉得在 ctex 的基础上稍微改改更方便

https://github.com/ustctug/ustcthesis/blob/70be41a091866f52f41ef2da3ae939276c582fa9/ustcthesis.dtx#L764

**Comment by zepinglee** [comment]
https://github.com/Stone-Zeng/fduthesis/blob/5f946620780fed1e5f7e2da7673d52a6aa5c8923/source/fduthesis.dtx#L3123

STZhongsong 不是 mac 下的默认字体，所以还是用 Songti SC 比较稳妥

**Comment by Stone-Zeng** [comment]
@zepinglee 刚刚改过了（<https://github.com/Stone-Zeng/fduthesis/commit/16a13713c129a6b2dc76870ea1a6586ecc8df950>）。我手头没有 mac，要是可以的话能帮我测试一下效果吗？

**Comment by zepinglee** [comment]
看起来没什么问题；还有 xelatex 下 fontspec 只能按照文件名读取 texmf 的字体，比如像 TeX Gyre Termes 这样的字体配置就很麻烦：
```TeX
\setmainfont[
  Extension      = .otf,
  UprightFont    = *-regular,
  BoldFont       = *-bold,
  ItalicFont     = *-italic,
  BoldItalicFont = *-bolditalic,
]{texgyretermes}
```
还有整个编译的 workflow 感觉让人很费解，配置了半天才搞定

**Comment by Stone-Zeng** [comment]
TeX Gyre Termes 不是可以直接用吗？你是不是没加空格……

```tex
\setmainfont{TeX Gyre Termes}
```

另外其实我是给了安装脚本的，但 master 里面的没有更新，有几个文件忘记放进来了，大概率是跑不起来的；phys 分支里面是好的，但一直没来得及合并。

**Comment by zepinglee** [comment]
`fontspec` 宏包 1.2 节讲 loading fonts by file name：
> This technique is also necessary in XeTeX when loading OpenType fonts that are present within your TeX distribution, such as `/usr/local/texlive/2013/texmf-dist/fonts/opentype/public`. Fonts in such locations are visible to XeTeX but cannot be loaded by font name, only file name; LuaTeX does not have this restriction.

可能你是把这些字体配置到系统字体了吧？

**Comment by Stone-Zeng** [comment]
Windows 和 Linux 下都是用 fontconfig 机制调用字体的，可能有缓存之后就可以用字体名了（我并没有放到系统里面）。怀疑是 macOS 下面机制不一样，总之还是改掉更合适一些。
