### ISSUE TITLE
关于每章页眉的问题

### ISSUE THREAD

**Issue by blueskyinin** [Stone-Zeng/fduthesis#39]
如果我想在每章节开始的页面都加上页眉应该怎么办

**Comment by Stone-Zeng** [comment]
加上 `\ctexset{chapter/pagestyle=fancy}` （放在导言区前后均可）。但是不能保证 `\section` 标题在章节开始的地方正确显示，尤其是在双面模式下只剩下了一条线，会比较丑。

总之一般不建议在章节开始的页面加页眉。如果确有需要，我再看着怎么弄一下。

**Comment by blueskyinin** [comment]
我在`\chapter`之后都加上`\thispagestyle{fancy}`就可以了，建议弄一个页眉的接口，可以自定义页眉。系主任说去年有人因为格式问题被查，所以要求正文每一页都要加上页眉，但是这样是真的丑。。。。

**Comment by blueskyinin** [comment]
模板是好模板，不过建议使用教程再详细一点，latex小白的我试了很久才编译好

**Comment by Stone-Zeng** [comment]
目前很多格式设置是写死在代码里的，并没有提供用于修改的接口。之后我可能会做一些修改，不过可能需要一段时间。

另外格式审查的话，我不能保证模板完全符合您所在院系的要求，事实上各个院系的要求也千差万别，很难全部兼顾。有问题的话再问吧。
