### ISSUE TITLE
关于参考文献[S.l.]: [s.n.]的问题

### ISSUE THREAD

**Issue by blueskyinin** [Stone-Zeng/fduthesis#40]
我用gb7714-2015标准编译论文后在参考文献那里会出现很多[S.l.]: [s.n.]，我看gb7714-2015这个宏包有可以控制出版信息缺失处理增加的选项，那我在模板里该怎样操作使得参考文献里不出现[S.l.]: [s.n.]

**Comment by zepinglee** [comment]
这个是我最近新写的，你可以将 https://github.com/zepinglee/gbt7714-bibtex-style 的 bst 文件替换一下，然后把 https://github.com/zepinglee/gbt7714-bibtex-style/blob/0027531019b8cf4db3611a1a556ef15bb1b37eb3/gbt7714-plain.bst#L39 这一行改成 `#0`

**Comment by Stone-Zeng** [comment]
参考文献是分处理引擎做的。如果用 BibTeX，就按照 @zepinglee 的办法复制一下 bst 文件到当前目录，然后修改一下；如果用 biblatex/biber，可以在调用 `fduthesis` 之前加上 `\PassOptionsToPackage{gbpub=false}{biblatex}`。

**Comment by blueskyinin** [comment]
我刚才看了图书馆论文上传的信息，他们已经要求用gb7714-2015标准录入参考文献了，我先试试看效果

**Comment by blueskyinin** [comment]
可以了，谢谢作者帮助
