### ISSUE TITLE
关于致谢问题

### ISSUE THREAD

**Issue by blueskyinin** [Stone-Zeng/fduthesis#41]
你好，我想问一下用什么命令把致谢那一页插进去，谢谢

**Comment by Stone-Zeng** [comment]
致谢可以当作一个 chapter 来处理。如果不要编号的话，可以用 `\chapter*{致谢}`，但这样也不会出现在目录中；也可以把 `\ctexset{chapter/numbering=false}` 放在致谢的前面，然后用 `\chapter{致谢}`，这样不编号，但是会放进目录和 PDF 书签。注意后一种改法会影响后面所有的 chapter，不过致谢反正放最后，不是很要紧；保险起见当然也可以放到一个分组里面。
