### ISSUE TITLE
模板运行报错

### ISSUE THREAD

**Issue by rGitcy** [Stone-Zeng/fduthesis#43]
TEXlive中包已经是最新的 ，但还是报错
LaTeX error: "kernel/message-unknown" Unknown message 'l3-too-old' for module 'fduthesis'. For immediate help type H <return>. }

**Comment by rGitcy** [comment]
找到原因了，用第一种方法安装OK

**Comment by egrcc** [comment]
@rGitcy 用第一种方法安装是什么意思？我也是这个错
