### ISSUE TITLE
fduthesis-template.tex 运行问题

### ISSUE THREAD

**Issue by rGitcy** [Stone-Zeng/fduthesis#44]
fduthesis-template.tex运行成功，但生成的pdf中，没两页之间都会有一个空白页，也没页码！！！

**Comment by Stone-Zeng** [comment]
这是因为您使用了双面模式（`twoside`）：

> 在双面模式（`twoside`）下，按照通常的排版惯例，每章应只从奇数页（在右）开
始；而在单页模式（`oneside`）下，则可以从任意页面开始。

空白页是用来确保打印时每章的开始页面在右侧。可以使用 `oneside` 选项关闭这一功能：

```tex
\documentclass[oneside]{fduthesis}
```

注意：这一功能在标准文档类中由 `openright`、`openany` 选项控制。

**Comment by Stone-Zeng** [comment]
见 #27。

**Comment by rGitcy** [comment]
谢谢学长发自我的华为手机-------- 原始邮件 --------主题：Re: [Stone-Zeng/fduthesis] fduthesis-template.tex 运行问题 (#44)发件人：Xiangdong Zeng 收件人：Stone-Zeng/fduthesis 抄送：Chunyang ,Author 这是因为您使用了双面模式（twoside）：

在双面模式（twoside）下，按照通常的排版惯例，每章应只从奇数页（在右）开
始；而在单页模式（oneside）下，则可以从任意页面开始。

空白页是用来确保打印时每章的开始页面在右侧。可以使用 oneside 选项关闭这一功能：
\documentclass[oneside]{fduthesis}
注意：这一功能在标准文档类中由 openright、openany 选项控制。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Stone-Zeng/fduthesis","title":"Stone-Zeng/fduthesis","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Stone-Zeng/fduthesis"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Stone-Zeng in #44: 这是因为您使用了双面模式（`twoside`）：\r\n\r\n\u003e 在双面模式（`twoside`）下，按照通常的排版惯例，每章应只从奇数页（在右）开\r\n始；而在单页模式（`oneside`）下，则可以从任意页面开始。\r\n\r\n空白页是用来确保打印时每章的开始页面在右侧。可以使用 `oneside` 选项关闭这一功能：\r\n\r\n```tex\r\n\\documentclass[oneside]{fduthesis}\r\n```\r\n\r\n注意：这一功能在标准文档类中由 `openright`、`openany` 选项控制。"}],"action":{"name":"View Issue","url":"https://github.com/Stone-Zeng/fduthesis/issues/44#issuecomment-402364740"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Stone-Zeng/fduthesis/issues/44#issuecomment-402364740",
"url": "https://github.com/Stone-Zeng/fduthesis/issues/44#issuecomment-402364740",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Stone-Zeng/fduthesis] fduthesis-template.tex 运行问题 (#44)",
"sections": [
{
"text": "",
"activityTitle": "**Xiangdong Zeng**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Stone-Zeng",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Stone-Zeng/fduthesis\",\n\"issueId\": 44,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Stone-Zeng/fduthesis\",\n\"issueId\": 44\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Stone-Zeng/fduthesis/issues/44#issuecomment-402364740"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 352532160\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Stone-Zeng** [comment]
啊，我并不是学长 ，刚刚本科毕业而已 😂
