### ISSUE TITLE
Mac下 XeLaTeX 编译报错

### ISSUE THREAD

**Issue by jinyu121** [stone-zeng/fduthesis#46]
最小例子：

```tex
\documentclass{fduthesis} 
\begin{document}
	\chapter{ 欢 迎 }
	\section{Welcome to fduthesis!}
	你 好 ，\LaTeX{}! 
\end{document}
```
使用TexStudio编译。所有包已同步官方源最新。报错如下：

```
错误 : File ended while scanning use of \__fontspec_strip_leading_sign:Nw.
警告 : Font 'FandolSong' does not contain script 'CJK'.
```

同样代码，LuaTeX可以正常编译。

报错的Log文件：

[main.log](https://github.com/Stone-Zeng/fduthesis/files/2749627/main.log)

**Comment by zepinglee** [comment]
见 https://github.com/CTeX-org/ctex-kit/issues/397

**Comment by Stone-Zeng** [comment]
目前解决方案只有暂时回退到上一个版本。

下载 [fontspec.zip](https://github.com/Stone-Zeng/fduthesis/files/2749675/fontspec.zip) 并解压到工作目录，然后应该就可以了。
