### ISSUE TITLE
章节号样式切换

### ISSUE THREAD

**Issue by jinyu121** [stone-zeng/fduthesis#48]
希望支持“第一章”和“第1章”的切换。
计算机学院的模板好像是中文的。

---

如果已经有了的话，建议在模板手册里面增加一个 FAQ 吧。

谢谢！

新年快乐！

=====

另外最近我也会把模板使用过程中的 笔记 和 问题解决办法 都发到Issue上来，可能issue会多一点。

**Comment by stone-zeng** [comment]
可以的话，能上传一下计算机学院的模板吗（word 也行）？有参照的话，更好改一点。

**Comment by sonnyhcl** [comment]
```latex
\ctexset{chapter={name={第,章},number={\chinese{chapter}}}}
```
希望能给翻找issue的大家一个临时解决方案 : )

**Comment by yiminz** [comment]
> 照的话，更好改

大致类似于
第一章 XXXXXXXXXX  {chapter}
    第一节 XXXXXX  {section}
      一、 XXXXXXXX {subsection}
          （一）、  XXXXXXXXXX   {subsubsection}


这个是国际关系与公共事务学院毕业论文要求是这样子的
文科。。头疼，，，，

**Comment by yiminz** [comment]
> ```
> \ctexset{chapter={name={第,章},number={\chinese{chapter}}}}
> ```
> 
> 希望能给翻找issue的大家一个临时解决方案 : )

这句话加到哪里呢>? tex文件里？？

**Comment by stone-zeng** [comment]
> 这句话加到哪里呢>? tex文件里？？

导言区，`\documentclass` 以及 `\fdusetup` 之后，`\begin{document}` 之前。
