### ISSUE TITLE
指导小组成员 希望增加其他对齐方式

### ISSUE THREAD

**Issue by jinyu121** [stone-zeng/fduthesis#49]
估计这个需求会被打死的吧……
Markdown排版，见谅。知道意思即可～

1. 只有名字，居中对齐即可。
    ```
      某某
      教师B
     某某某
    ```
2. 考虑到最极端情况……可以像这样
    ```
    教师A     教师B     教师C     教师D     教师E
    教师F     教师G     教师H     教师I     教师J
                教师K     教师L
    ```
3. 教师+职称，中间空格对齐（其实可以用没有边框的表格来搞，左边一列右对齐，右边一列左对齐）——我们正在用这个样式
   ```
       某某    教授
      某某某    副教授
    某某某某    助理研究员
   ```
4. 学校+教师+职称，直接用没有边框的表格吧……——见过师兄的论文在用这个样式
    ```
    XX大学      某某        教授
    XX大学      某某某      副教授
    XXXX大学    某某某某    助理研究员
   ```

感觉最简单的办法是设置没有边框的表格。   

-----

目前行为是，即使`info/instructors`为空，也会生成 指导小组成员 这一页。希望是“如果`info/instructors`为空，那么就不插入 指导小组成员 这一页”。然后由使用者自己在适当地方加入chapter，并自定义样式，例如按照需要插入边框不可见的表格。

**Comment by stone-zeng** [comment]
默认的方式很简单，就是把一个 comma-list 里面的东西一行一行输出，然后居中对齐。手动弄的话，也就只有放空格对齐了（全角空格这里就很适合，给的空白模板就是这么做的）：

https://github.com/stone-zeng/fduthesis/blob/8be013d95b3d8357e934edd7191dabff568de0d2/docs/tex/fduthesis-template.tex#L174-L181

至于兼顾各种奇怪的方式，这个其实早就考虑过了。实际上封一、封二、封三都有很一般的抽象模板，然后只给了一个默认的实现（类似于 `beamer` 的做法，但是是用 `l3template` 做的，见 #42）。API 一直还没有开放，因为我也不是很确定要做成什么样子。但如果有需要，是可以自己更改的，虽然大概会比较麻烦……

> 如果 `info/instructors` 为空，那么就不插入「指导小组成员」这一页

这个倒是一个挺好的想法，之后想办法加上吧。

最后，感谢你们来做探路者，没人来试用实在是比较僵硬 🙆🙆

**Comment by stone-zeng** [comment]
复杂的对齐方式可以直接插入表格实现，例如：

```tex
instructors = {
  \begin{tabular}{lll}
    复旦大学 & 张三 & 教授   \\
    复旦大学 & 李四 & 研究院 \\
    南方科技大学 & 王五六 & 助理研究员
  \end{tabular}
}
```
