### ISSUE TITLE
“学位论文独创性声明”和“学位论文使用授权声明”希望支持扫描版

### ISSUE THREAD

**Issue by jinyu121** [stone-zeng/fduthesis#50]
好像没有在设置中看到哎。

记得图书馆的提交规定里面有写，这个声明页是要自己签字、老板签字，并且用扫描版的。

所以，能否在设置里加个选项？如果没有被设置，那么用自动生成的；如果有路径，那么就用路径所指定图片文件？

**Comment by stone-zeng** [comment]
我们（物理系本科毕设）去年是只要在打印下来的论文上面签字，所以这个功能就没做了。确实是应该要加的。

**Comment by stone-zeng** [comment]
目前要做的话，可以手动解决：

```latex
\usepackage{pdfpages}
\RenewDocumentCommand\makecoveriii{}{%
  \cleardoublepage\includepdf{<扫描 PDF 文件>}}
```

**Comment by yiminz** [comment]
用adobe整合一下PDF就好了。。
