### ISSUE TITLE
多文件编译，章标题页占一页

### ISSUE THREAD

**Issue by Tambura** [stone-zeng/fduthesis#54]
多文件编译，每章在一个单独的chapter.tex中，编译后章的标题占一整页，章的主体内容从下一页开始，这个可以调整为内容不从新页开始吗？ # #

**Comment by zepinglee** [comment]
`\include` 会导致新起一页，你可以把 `\chapter{xxx}` 得命令加到子文件里面

**Comment by Tambura** [comment]
已经解决，谢谢！

**Comment by jinyu121** [comment]
“`\include` 会导致新起一页“，好像其他文章模板，例如IEEE的模板，都没有这个设定吧？

**Comment by zepinglee** [comment]
有。

其实我更喜欢用 \input

**Comment by zepinglee** [comment]
@Tambura 用 `\input` 更合适

**Comment by stone-zeng** [comment]
`\include` 会做一些额外的工作（比如调用 `\clearpage`、写入单独的 aux 文件等），但 `\input` 基本就相当于把子文件里面的内容贴过来。当然，如果需要用 `\includeonly` 之类的来控制，那就只能用前者了。

**Comment by jinyu121** [comment]
哦我记错了…… 之前一直使用的都是`input`，在wiki里写的也是`input`。

给我的感觉是，`include`会把每个tex文件单独编译，然后进行合并；`input`是将子文件的内容贴过来。

谢各位
