### ISSUE TITLE
页眉设置

### ISSUE THREAD

**Issue by rGitcy** [stone-zeng/fduthesis#55]
请问怎么设置页眉呀？

**Comment by stone-zeng** [comment]
## 原问题：

摘要、章的首页如何添加标题？

示例：

![adc42fa1d9f751a626e3369b2e2e53cc](https://user-images.githubusercontent.com/18233088/54031874-eca68700-41ea-11e9-8ac8-0658a7286cf9.png)

## 解决：

导言区添加以下代码：

```tex
\makeatletter
\let\ps@plain\ps@fancy
\makeatother
```

**Comment by rGitcy** [comment]
谢谢大佬发自我的华为手机-------- 原始邮件 --------主题：Re: [stone-zeng/fduthesis] 页眉设置 (#55)发件人：Xiangdong Zeng 收件人：stone-zeng/fduthesis 抄送：Chunyang ,Author 原问题：

摘要、章的首页如何添加标题？

示例：



解决：

导言区添加以下代码：

\makeatletter

\let\ps@plain\ps@fancy

\makeatother

**Comment by ruoshs** [comment]
> ## 原问题：
> 摘要、章的首页如何添加标题？
> 
> 示例：
> 
> ![adc42fa1d9f751a626e3369b2e2e53cc](https://user-images.githubusercontent.com/18233088/54031874-eca68700-41ea-11e9-8ac8-0658a7286cf9.png)
> 
> ## 解决：
> 导言区添加以下代码：
> 
> ```
> \makeatletter
> \let\ps@plain\ps@fancy
> \makeatother
> ```
> 
> 参见：https://tex.stackexchange.com/a/15173

加上这三行之后，摘要、符号表、参考文献上面出现了含标题的页眉（就跟你的截图一样），但是章的首页只出现了一条横线，上面没有标题。其它以chapter形式存在的页面也一样，比如致谢。
![image](https://user-images.githubusercontent.com/5900664/54076476-fd3c2780-42e6-11e9-9585-0843da38dbe9.png)
不知道问题出在哪里，是否方便解决？感谢！

**Comment by ruoshs** [comment]
好吧，问题已经解决了，因为我用的是twoside模式，默认页眉是偶左(EL)、奇右(OR)，我想让页眉变成居中，在“fduthesis.cls”文件里面错误地把它们改成了“EC” “OC”，导致只有偶数页显示居中的标题，所以每章首页作为奇数页就没有显示标题。正确做法应该是把其中一个改成"C", 然后注释掉另一行就可以了。

```
\fancyhf { }
\tl_new:N \l__fdu_header_center_mark_tl
\bool_if:NTF \g__fdu_twoside_bool
  {
    \fancyhead [ C ] { \small \nouppercase { \fdu@kai \leftmark  } }
%   \fancyhead [ OR ] { \small \nouppercase { \fdu@kai \rightmark } }
  }
  {
    \fancyhead [ L ] { \small \nouppercase { \fdu@kai \leftmark  } }
    \fancyhead [ R ] { \small \nouppercase { \fdu@kai \rightmark } }
    \fancyhead [ C ]
      {
        \small \nouppercase
          { \fdu@kai \l__fdu_header_center_mark_tl }
      }
  }

```

另外，我在fancyhdr包的说明书里面发现了一个更简单的语句`\fancypagestyle{plain}{}`，作用是把它的"plain"页面风格重定义为和"fancy"一样的页面风格，所以可以添加在导言区域代替那三行代码，实现每章首页也生成页眉。

> fancyhdr包的说明书链接：
> [http://mirrors.concertpass.com/tex-archive/macros/latex/contrib/fancyhdr/fancyhdr.pdf](url)

**Comment by stone-zeng** [comment]
若需要目录、摘要等的页眉分别显示「目录」、「摘要」，并且正文部分**所有页**（包括每章的第一页）均显示章名，可以用如下方法：

```latex
\makeatletter
\let\ps@plain\ps@fancy
\makeatother
\fancyhf{}
\fancyhead[C]{\small\nouppercase{\leftmark}}
\fancyfoot[C]{\small\thepage}
\pagestyle{fancy}
```

如有需要，可参考 `fancyhdr` 宏包自行修改。

![image](https://user-images.githubusercontent.com/18233088/54339174-feff4580-466e-11e9-9ad6-8af986cd1d70.png)

![image](https://user-images.githubusercontent.com/18233088/54339157-f1e25680-466e-11e9-878b-bc2a347a0767.png)
