### ISSUE TITLE
旻 字无法显示

### ISSUE THREAD

**Issue by jinyu121** [stone-zeng/fduthesis#57]
旻 字死活出不来……

环境： MAC
编译工具： LuaLaTeX
字体设置相关：全部给注释掉了，所以应该都是默认值吧

尝试过的其他方法：

```
{\fontspec{Source Han Sans SC}旻}
```

```
\font\1="STHeiti Medium"
\1{旻}
```

```
\setmainfont{Source Han Serif SC}
```

均失败

**Comment by stone-zeng** [comment]
没测试，但看了一下，应该是因为默认的 fandol 字体里面不带这个字。

你的解决方法在调用 `xeCJK` 之后事实上都只对非 CJK 字符起作用，所以自然会失败。

就模板而言，把 `cjk-font` 设置成其他值就可以了；也可以用 `\setCJKmainfont`、`\CJKfontspec` 等命令手动修改，具体参见 `xeCJK` 宏包文档。

**Comment by jinyu121** [comment]
> 就模板而言，把 `cjk-font` 设置成其他值就可以了；也可以用 `\setCJKmainfont`、`\CJKfontspec` 等命令手动修改，具体参见 `xeCJK` 宏包文档。

`cjk-font={Source Han Serif SC}`

```
LaTeX3: Key 'fdu/style/cjk-font' accepts only a fixed set of choices.
```

`\setCJKmainfont{Source Han Serif SC}`

```
Functions of `CJKfntef' is not available in LuaLaTeX
```

我暂时选择放弃

**Comment by stone-zeng** [comment]
这个……您不能乱来的是吧……

`cjk-font` 支持的值只有 `adobe`、`fandol`、`founder`、`mac`、`windows` 和 `none`；最近还加了 `sinotype` 和 `sourcehan`。macOS 的话，选择 `cjk-font=mac` 就好了。

手动设置其他字体的话，需要用 xeCJK/CTeX 的方法，即使用 `\setCJKmainfont` 之类的命令。

注意要更新到最新的才可以（至少 5cfb64092129f66d8aa5b8841d208e27d9443a6a 之后），可能这几天发一下 release 吧。

**Comment by jinyu121** [comment]
我没有乱来…… 

本来就有个Warning（但是编译还是能通过的）

```
Functions of `CJKfntef' is not available in LuaLaTeX
```

然后加上`font=mac`之后，编译开始报错

```
LaTeX3: Key 'fdu/style/font' accepts only a fixed set of choices.
```

不管改成啥，比如adobe、{adobe}、windows，都是这个错误。等号前后加不加空格应该没影响的（对，没影响，均报错😂），然后才试的直接写字体名字的嘛……

版本是目前ctan上的最新版。

**Comment by stone-zeng** [comment]
![image](https://user-images.githubusercontent.com/18233088/54267620-85a31c80-45b4-11e9-8724-e44dfcc7d554.png)

文档里面写得很清楚：模版的字体是分中文和西文的，中文用 `cjk-font=...`，西文用 `font=...`。`mac` 只能用在 `cjk-font`，所以你写 `font=mac` 或者 `adobe`、`windows` 之类的必然会报错。

macOS 里面 **XeLaTeX** 对字体的调用方式和 Windows、Linux 不同，我之前一直没有管，所以可能会有问题。具体来说，现在 CTAN 上面的那个版本，在 macOS 上面用 XeLaTeX 是没办法直接编译的；我早两天做了修正，目前只有自己把 github 上面的 clone 下来才可以（还没发 release） 。

你这边用的是 LuaLaTeX，与上面这段话所描述的问题**没有关系**。`CJKfntef ` 这个 warning 是因为 `CTeX` 宏包加载了 `(xe)CJKfntef` 宏包的功能，但它们并不适用于 LuaLaTeX，而且模版也没有采用相关功能。所以编译不受影响。

至于缺字的问题，那是因为默认用了 Fandol，而这是一套「仅能勉强满足要求」的字体。制造一套完整、高质量的中文字体要钱要人要时间，所以开源可用、质量高的实际上只有思源黑体/宋体。但是，毕竟不是每个人的电脑上都装了思源；就算是装了，字体的问题也够喝一壶；而且思源没有楷体和仿宋；最后，开始做模版的时候思源宋体还并未发布。由于这些，当时就没有考虑把思源作为选项（现在加上了）。而之所以没用 CTeX 宏集的默认方案（按照系统决定字库），是因为有些需求和它并不完全匹配，所以重造了轮子。不过现在想来比较多余，所以最近把这部分重写了。而根据系统先做一下判断，似乎也是可以做的。

总而言之，目前对你的建议是：

1. Clone **当前的 github 仓库**（不是 release 也不是 ctan）
1. 使用「扁平化安装」，或者生成 `.cls` 之后替换原来的文档类
1. 设置 `cjk-font=mac`

如果担心开发版本的风险，可以用原来的模版（就是现在 CTAN 的那个版本），然后：

1. 设置 `cjk-font=none`（西文字体的问题在 #45 里面讲过了）
1. 然后导言区
    ```latex
    \setCJKmainfont{Source Han Serif SC}  % 思源没有楷体，暂且不管
    \setCJKsansfont{Source Han Sans SC}
    \setCJKmonofont{Source Han Sans SC}
    ```
    或者
    ```latex
    \setCJKmainfont{STSongti-SC}{ItalicFont=Kaiti SC}
    \setCJKsansfont{STHeitiSC}
    \setCJKmonofont{STFangsong}
    ```

**Comment by jinyu121** [comment]
感谢！
