### ISSUE TITLE
中图分类号 一处小小的没对齐

### ISSUE THREAD

**Issue by jinyu121** [stone-zeng/fduthesis#59]
![image](https://user-images.githubusercontent.com/7346324/54275395-724c7d00-45c5-11e9-8d33-0776e8ed9616.png)
后面的英文好像偏高了一点点

**Comment by stone-zeng** [comment]
我不知道你这边字体配置是什么，看样子是 Fandol 黑体、加上直接把西文设置为了思源宋体？如果是的话，那么请改用其他**西文字体**设置。

![image](https://user-images.githubusercontent.com/18233088/54340220-e6dcf580-4671-11e9-8b6a-ddaa7c84f927.png)

基线的问题比较麻烦，所以模版中的默认设置尽量选择了同一厂商的搭配。对字体这方面了解不够的话，很容易出各种问题。

参考：<https://github.com/clerkma/ptex-ng-dist/issues/5>
