### ISSUE TITLE
一些小建议，以及为你点赞

### ISSUE THREAD

**Issue by nanmu42** [Stone-Zeng/fduthesis#6]
Hi,
项目最近的进度看起来十分喜人，恭喜。

不过在编译用户文档和测试文档时有几个问题：

1. 缺`fduthesis-cover.pdf`文件（估计是`.gitignore`造成的，你可以使用`git add`解决）：

```
l.266 ...s[width=8cm]{../logo/fduthesis-cover.pdf}
```

2. 用户文档依赖字体太多，装起来十分费劲，特别是下面几个，版权问题很微妙：

![image](https://user-images.githubusercontent.com/8143068/27991293-5d558684-64a4-11e7-906c-aa336c90a6d6.png)

3. `/logo/`目录中的tex文件需要预先编译为pdf文件才能正常使用，这点希望在`README.md`里提一下。

4. 在编译test文件夹下的范例时，有一个依赖`zhlipsum`（很棒的作品）没有在ctan登记，建议你将这个宏包上传到ctan，方便用户，也方便你的Travis测试。

这个模板在技术上十分超前，为你点赞！:+1:
祝好。

**Comment by Stone-Zeng** [comment]
文档我是准备直接发布的（当然现在还没传到 github），可能自己编译比较麻烦。

**Comment by Stone-Zeng** [comment]
文档已上传，应该可以看到了。

另外字体方面，我和方正联系过了，他们的回复是这样的（那个网址貌似打不开）：

> 您咨询的“方正黑体、方正书宋、方正仿宋和方正楷体”在商业发布中可以免费使用（包括这四款字体对应的GB2312-80、GB12345-90、GBK和BIG5四种编码字库），关于商业发布的具体途径您可参考网页 http://www.foundertype.com/index.php/About/accessAuth.html 中商业授权中的《方正字库授权价格表（标准版）》。

我这个肯定不算商业授权，讲道理商业发布都可以免费用，开源的东西没有道理不能用啊。

**Comment by nanmu42** [comment]
嗯，看起来链接应该是换到了[这里](http://www.foundertype.com/index.php/About/bookAuth/key/my_sysq.html)。

成果喜人，祝好。:)

**Comment by Stone-Zeng** [comment]
`zhlipsum` 已上传至 CTAN，欢迎使用 :blush:！

**Comment by nanmu42** [comment]
点个赞～

Zeng Xiangdong <notifications@github.com> 於 2017年8月5日 週六 下午8:47 寫道：

**Comment by zepinglee** [comment]
厉害！已经开始用 latex3 语法啦！

我对 l3 的进展不太熟，请教一下你主要参考了哪些的用 l3 写的 package/class？

**Comment by Stone-Zeng** [comment]
主要是模仿 `ctex` 还有 `xeCJK`。语法看 `interface3.pdf` 就差不多了，讲得很详细的。
