### ISSUE TITLE
页眉问题

### ISSUE THREAD

**Issue by rGitcy** [stone-zeng/fduthesis#61]
大佬好，按照您的指导设置页眉，出现一个奇怪问题，正文部分有页眉，但摘要等部分无文字页眉，只有一个横线。求大神指导。

**Comment by stone-zeng** [comment]
代码？

**Comment by rGitcy** [comment]
\makeatletter

\let\ps@plain\ps@fancy

\makeatother

\fancyhf{}

\fancyhead[C]{\small\nouppercase{\leftmark}}

\fancyfoot[C]{\small\thepage}

\pagestyle{fancy}

**Comment by stone-zeng** [comment]
我这边编译是正常的：

```latex
\documentclass{fduthesis}
\usepackage{zhlipsum}

\makeatletter
\let\ps@plain\ps@fancy
\makeatother
\fancyhf{}
\fancyhead[C]{\small\nouppercase{\leftmark}}
\fancyfoot[C]{\small\thepage}
\pagestyle{fancy}

\begin{document}

\begin{abstract}
\zhlipsum
\end{abstract}

\chapter{测试}

\section{小节 A}
\zhlipsum[4-6]
\section{小节 B}
\zhlipsum[7-9]

\end{document}
```

![image](https://user-images.githubusercontent.com/18233088/54609450-fe5f1880-4a8d-11e9-9a98-487bf9f3721c.png)

![image](https://user-images.githubusercontent.com/18233088/54609477-0f0f8e80-4a8e-11e9-8c18-1f7441a9dbc1.png)

**Comment by rGitcy** [comment]
好的ヾ ^_^♪我再试下，xelatex编译对吧发自我的华为手机-------- 原始邮件 --------主题：Re: [stone-zeng/fduthesis] 页眉问题 (#61)发件人：Xiangdong Zeng 收件人：stone-zeng/fduthesis 抄送：Chunyang ,Author 我这边编译是正常的：

\documentclass{fduthesis}

\usepackage{zhlipsum}



\makeatletter

\let\ps@plain\ps@fancy

\makeatother

\fancyhf{}

\fancyhead[C]{\small\nouppercase{\leftmark}}

\fancyfoot[C]{\small\thepage}

\pagestyle{fancy}



\begin{document}



\begin{abstract}

\zhlipsum

\end{abstract}



\chapter{测试}



\section{小节 A}

\zhlipsum[4-6]

\section{小节 B}

\zhlipsum[7-9]



\end{document}

**Comment by stone-zeng** [comment]
因为你开了 `oneside` 的选项，而上面的 hack 是针对 `twoside` 做的。

可以这样改：

```latex
\makeatletter
\let\ps@plain\ps@fancy
\makeatother
\fancyhf{}
\fancyhead[C]{\small\nouppercase{\csname l__fdu_header_center_mark_tl\endcsname\leftmark}}
\fancyfoot[C]{\small\thepage}
\pagestyle{fancy}
```

PS：`zhlipsum` 宏包只是输入大段的文字用来撑版面，正常写文章时可以不用。

**Comment by yiminz** [comment]
> 因为你开了 `oneside` 的选项，而上面的 hack 是针对 `twoside` 做的。
> 
> 可以这样改：
> 
> ```
> \makeatletter
> \let\ps@plain\ps@fancy
> \makeatother
> \fancyhf{}
> \fancyhead[C]{\small\nouppercase{\csname l__fdu_header_center_mark_tl\endcsname\leftmark}}
> \fancyfoot[C]{\small\thepage}
> \pagestyle{fancy}
> ```
> 
> PS：`zhlipsum` 宏包只是输入大段的文字用来撑版面，正常写文章时可以不用。

我也是用的oneside 选项。
出现以下问题
1、
使用\chapter*{绪论}时
然后页眉也不显示 绪论了。。。
只显示一条线。
2、结论处也使用\chapter*{结论}
然后页眉 延续了上一章节的页眉。没有显示 结论。

曾哥，怎么处理呢、、、

**Comment by stone-zeng** [comment]
为什么要用 `\chapter*`？每章都是应该编号的吧。

**Comment by stone-zeng** [comment]
另外 @yiminz 有问题就直接提一个 issue，不用在好几个里面都 coment 一遍～

**Comment by yiminz** [comment]
> 是应该编

是因为文科里面有的章节不需要编号。
例如：绪论和结论
前面不需要加 第一章 
在目录和正文中仅显示 绪论

**Comment by stone-zeng** [comment]
@yiminz 可不可以把「文科的要求」整理一下，统一去提一个 issue？这样方便管理一点，谢谢！

**Comment by stone-zeng** [comment]
比较简单的处理：

```tex
\begingroup
  \ctexset{chapter/numbering=false}
  \chapter{不编号}
\endgroup
```

但是实现比较粗糙。比如这一章底下的小节、公式、图表怎么编号、页眉居中还是左对齐都没有管。总之希望您可以提供更多的信息。
