### ISSUE TITLE
Mac下使用cjk-font=sourcehan后目录里一处字体问题

### ISSUE THREAD

**Issue by jinyu121** [stone-zeng/fduthesis#65]
版本： CTAN v0.7c

问题：

“参考文献”默认是不在目录中显示的。如果我想让“参考文献”四个字出现在目录里，则需要

```
\addcontentsline{toc}{chapter}{参考文献}
```

但是当换了字体之后，“参考文献”四个字字体不对。

```
    font = times*,
    cjk-font=sourcehan,
```

![image](https://user-images.githubusercontent.com/7346324/54864240-834c7980-4d8f-11e9-871b-22531f3f5799.png)

这好像是默认的Fandol什么字体？

另外，CTAN 0.7b版本手动用\setCJKMainFont和\setCJKXXXFont换字体（哦……我忘了XXX是啥了），也会出现这个情况。

----

如果修复比较方便的话……求在27号之前修复一个……学校要求是27号（含）之前上传终稿。

谢谢！

----

另外说明，好像TeXLive在酝酿2019版，所以目前不能从CTAN上自动更新到v0.7c版本，只能更新到v0.7b版本。

**Comment by stone-zeng** [comment]
可以直接 clone，之后运行那个 `install-unix.sh`（取决于你的系统），再把生成的 cls 放到论文的工作目录底下，注意备份。然后那个 `\addcontentsline{toc}{chapter}{参考文献}` 可以不写了。

我现在用的是 pretest 版的 TL 2019。但正式发布肯定是等不到论文提交了，现在也只有直接从 github clone；另外请注意 release 里面不是最新的（至少刚修的 bug 肯定还在）。有问题的话再提吧。
