### ISSUE TITLE
在正文中\bfseries没有效果

### ISSUE THREAD

**Issue by ufo54153** [stone-zeng/fduthesis#66]
我在使用模板时使用了一些subsubsection，但是似乎这些subsubsection的标题不能够以粗体显示（即便我使用titlesec包设置了）
然后我发现正文中使用\bfseries也无法将一小段文字变为黑体显示，需要显式地使用
\setCJKmainfont[BoldFont=SimHei]{SimSun}
来指定粗体字体才可以显示黑体为粗体。是否还有其他方法来达到这个目的？

**Comment by zepinglee** [comment]
`\bfseries` 是粗体不是黑体

**Comment by ufo54153** [comment]
> `\bfseries` 是粗体不是黑体

是的，当然如果增加一个伪粗体的开关也是很好的

**Comment by stone-zeng** [comment]
在最近的修改中，我只按最原始的方法调用了中文字体。具体来说，如果该字体没有对应的粗体，那么就直接把粗体设置为自己；同时伪粗也不开启。所以，如果要用黑体的话，可以拿 `\sffamily` 来调。

此外，通过 `ctex` 宏包的接口可以比较方便的定义章节标题样式，可以不必再使用 `titlesec`（特殊需求除外）。至于 subsubsection，学校模版似乎没有规定，而且用的也不多，我就没有管了。

**Comment by stone-zeng** [comment]
伪粗是不可能加的，永远不可能加的 /手动斜眼

**Comment by ufo54153** [comment]
> 在最近的修改中，我只按最原始的方法调用了中文字体。具体来说，如果该字体没有对应的粗体，那么就直接把粗体设置为自己；同时伪粗也不开启。所以，如果要用黑体的话，可以拿 `\sffamily` 来调。
> 
> 此外，通过 `ctex` 宏包的接口可以比较方便的定义章节标题样式，可以不必再使用 `titlesec`（特殊需求除外）。至于 subsubsection，学校模版似乎没有规定，而且用的也不多，我就没有管了。

吼的
