### ISSUE TITLE
封面中文标题字体不对

### ISSUE THREAD

**Issue by jinyu121** [stone-zeng/fduthesis#68]
按照2017年3月修订版的 [博士、硕士学位论文规范](https://github.com/stone-zeng/fduthesis/files/3011871/doc.zip) 中给的封面样本，封面中文标题字体应该是加粗的宋体。但是现在封面的中文标题是加粗的黑体。

（虽然加粗宋体没有加粗黑体好看的说）

请核实然后修改一下？谢谢！

**Comment by stone-zeng** [comment]
主要原因是 Windows 自带的（中易）宋体没有对应的粗体，而我又不想默认开启伪粗。所以请先自己临时改一下：

```latex
% 导言区
\EditInstance{fdu/cover}{cover-i-default}{title/format=\zihao{-2}\bfseries}
```

前提是用的 CJKmainfont 有粗体，比如 `fandol` 或者 `sourcehan`。不是的话，就拿 Fandol（或者其他你想用的）代替一下：

```latex
\EditInstance{fdu/cover}{cover-i-default}{%
  title/format=\zihao{-2}\CJKfontspec{FandolSong-Bold.otf}}
```

伪粗我自己比较排斥。要用的话，反正就是那个 `AutoFakeBold` 选项，`xeCJK` 的文档都有介绍，但还要配合字体调用。如果确有需求可以再来提。

**Comment by zepinglee** [comment]
我觉对于普通用户 out-of-the-box 是最好的，所以对于 windows 用户最好开启伪粗，反正你自己用的是 mac 眼不见心不烦

**Comment by Jeff-Tian** [comment]
在 Mac 上亲测这个方案有效：

```
% 中英文标题黑体加粗
\EditInstance{fdu/cover}{cover-i-default}{%
  title/format=\zihao{-2}\CJKfontspec{FandolHei-Bold.otf}}
```

用这个 docker 镜像编译出来也是黑体：

```
docker run --rm -it -v $(pwd):/work -w /work -e LC_ALL=C.UTF-8 jefftian/texlive-full:latest latexmk -lualatex -shell-escape -synctex=1 -interaction=nonstopmode -enable-write18 基于xxxx系统设计与实现.tex
```
