### ISSUE TITLE
参考文献样式和跳转

### ISSUE THREAD

**Issue by ShichaoSun** [stone-zeng/fduthesis#69]
目录中的参考文献跳转页面错误，而且，参考文献样式没有加粗

**Comment by stone-zeng** [comment]
> 目录中的参考文献跳转页面错误

确定编译次数够了吗？推荐 latexmk 编译。

> 参考文献样式没有加粗

请给出具体描述。

**Comment by ShichaoSun** [comment]
\printbibliography
%> 打印参考文献列表
\addcontentsline{toc}{chapter}{参考文献}

这样写跳转就可以解决了，但是目录中参考文献没有加粗

**Comment by ShichaoSun** [comment]
目录中显示的参考文献，是没加粗字体

**Comment by ShichaoSun** [comment]
会不会是因为我用了Windows字体

**Comment by stone-zeng** [comment]
见 #65，已经处理掉了。

**Comment by ShichaoSun** [comment]
谢谢🙏🙏🙏
