### ISSUE TITLE
英文关键词

### ISSUE THREAD

**Issue by ShichaoSun** [stone-zeng/fduthesis#70]
1、能不能用英文分号代替空格作为分割符号。
2、关键词太多之后，需要分行时，对齐位置与中文对齐相比，中文更好看

**Comment by stone-zeng** [comment]
![image](https://user-images.githubusercontent.com/18233088/55159991-402e4400-519d-11e9-9204-3a024be6fad4.png)

![image](https://user-images.githubusercontent.com/18233088/55159960-33115500-519d-11e9-9094-58af03f4ed1d.png)

这样如何？

**Comment by ShichaoSun** [comment]
谢谢！很棒
