### ISSUE TITLE
数学公式都是默认加粗了吗？

### ISSUE THREAD

**Issue by ShichaoSun** [stone-zeng/fduthesis#71]
数学公式都是默认加粗了吗？

**Comment by ShichaoSun** [comment]
数学公式都是默认加粗了吗？

**Comment by stone-zeng** [comment]
请提供足以反映问题的示例代码（MWE, Minimal Working Example）、所用模版的版本号、TeX 发行版信息、系统信息以及所有必要的东西；以及，标题需要能够完整描述问题。

描述不清的 issue 会被直接关掉。

**Comment by ShichaoSun** [comment]
代码：
\begin{equation}
\begin{split}
\mathbf{h}_t &= z_t \odot \mathbf{h}_{t-1} + \left(1 - z_t\right) \odot \widetilde{\mathbf{h}_t}\\
\widetilde{\mathbf{h}_t} &= \tanh\left(W_h x_t + r_t \odot \left( U_h \mathbf{h}_{t-1} \right) \right) \\
z_t &= \sigma\left(W_z x_t + U_z \mathbf{h}_{t-1} \right) \\
r_t &= \sigma\left(W_r x_t + U_r \mathbf{h}_{t-1} \right) 
\end{split}
\label{eq:gru}
\end{equation}
结果：
![Screenshot from 2019-04-12 17-44-49](https://user-images.githubusercontent.com/13548568/56028858-aee9d080-5d4b-11e9-8943-3d1c85e4d8d8.png)
版本：最新版
tex: xelatex 2018
字体：times*

问题： tanh 和 x z这些字母颜色深度不一样

**Comment by ShichaoSun** [comment]
我想知道是默认加粗了吗？还是就是字体不一样导致的。
此外，我是ubuntu 16下装了windows字体

**Comment by stone-zeng** [comment]
这个是 `times*` 的情形：

![image](https://user-images.githubusercontent.com/18233088/56035444-caa9a280-5d5c-11e9-9f16-8aeb40d15189.png)

这个则是 `times`：

![image](https://user-images.githubusercontent.com/18233088/56035420-b665a580-5d5c-11e9-9e62-127a899b0e39.png)

`times*` 的话会用 Times New Roman，而 `times` 用的是很相似的 XITS，但对比来看 Times New Roman 略细一点；此外，「类 Times」字体的大写字母有些确实很粗，而 bold 字重可能又没有那么明显。这些可能使你产生了「默认加粗」的错觉，事实上当然是没有。

图里面用彩色标注的是正文字体，其他黑色的则都是数学字体 XITS Math。因为 Times New Roman 没有对应的数学字体，所以我这里更建议选择 `times` 以获得更好的搭配效果（所以也是默认选项）。一般人其实很难分出来真正的 Times New Roman 和那一堆与它长得几乎一模一样的「类 Times」字体。

**Comment by stone-zeng** [comment]
测试代码：

```latex
\documentclass{standalone}
\usepackage{amsmath,unicode-math,xcolor}
% \setmainfont{Times New Roman}[Color=teal]
\setmainfont{XITS-Regular.otf}[BoldFont=XITS-Bold.otf, Color=purple]
\setmathfont{XITSMath-Regular.otf}
\begin{document}
$
  \begin{aligned}
    \mathbf{h}_t &= z_t \odot \mathbf{h}_{t-1} + \left(1 - z_t\right) \odot \widetilde{\mathbf{h}_t}\\
    \widetilde{\mathbf{h}_t} &= \tanh\left(W_h x_t + r_t \odot \left( U_h \mathbf{h}_{t-1} \right) \right) \\
    z_t &= \sigma\left(W_z x_t + U_z \mathbf{h}_{t-1} \right) \\
    r_t &= \sigma\left(W_r x_t + U_r \mathbf{h}_{t-1} \right) 
  \end{aligned}
$
\end{document}
```

**Comment by zepinglee** [comment]
我之前看到 `sticktoo` 说 stix2 的字体比 Times New Roman 粗 15%，看来 xits 也略粗？

**Comment by zepinglee** [comment]
![Screen Shot 2019-04-12 at 8 31 27 PM](https://user-images.githubusercontent.com/12290822/56037488-f7ac8400-5d61-11e9-8e3e-6a249872a358.png)

Times New Roman + STIX2Math 看起来还可以

```
\setmainfont{Times New Roman}[Color=teal]
\setmathfont{STIX2Math.otf}
```

**Comment by ShichaoSun** [comment]
谢谢

**Comment by stone-zeng** [comment]
stix2 感觉有点诡异的圆滑，没有 xits 那么「times」，所以就不是很喜欢用。

**Comment by zepinglee** [comment]
所以你什么可以做一套 opentype math 的 newtx 数学字体啊【滑稽】

**Comment by YuanshengZhao** [comment]
可以用tg termes 字体。
