### ISSUE TITLE
请问 可以增加图列表与表列表么

### ISSUE THREAD

**Issue by Brightorange90** [stone-zeng/fduthesis#72]
请问，该模板中有图列表与表列表的命令么？

**Comment by stone-zeng** [comment]
可以使用标准的 LaTeX 命令 `\listoffigures` 和 `\listoftables` 来生成。但是模版目前没有做额外的处理，因此还不能显示在目录和 PDF 书签中，页眉等样式也可能有不一致的地方。

**Comment by Brightorange90** [comment]
那模板正常办法是没法显示在目录中？

**Comment by Brightorange90** [comment]
\usepackage[nottoc]{tocbibind}

> 可以使用标准的 LaTeX 命令 `\listoffigures` 和 `\listoftables` 来生成。但是模版目前没有做额外的处理，因此还不能显示在目录和 PDF 书签中，页眉等样式也可能有不一致的地方。

\usepackage[nottoc]{tocbibind}  可以解决该问题，参考 https://texblog.org/2013/04/29/latex-table-of-contents-list-of-figurestables-and-some-customizations/

**Comment by zepinglee** [comment]
我觉得这个最好在模板里做

**Comment by Brightorange90** [comment]
> 我觉得这个最好在模板里做

目前看效果已经达到了，就是被当做标题处理了。 后续加入模板应该也是没问题的
