### ISSUE TITLE
目录样式的章节的间隔可以设置么？使用其他命令时会出现问题。

### ISSUE THREAD

**Issue by Brightorange90** [stone-zeng/fduthesis#73]
目录样式的章节的间隔可以设置么？ 默认设置看着有些宽 使用其他命令时会出现问题。

**Comment by zepinglee** [comment]
给个截图？

**Comment by stone-zeng** [comment]
模版对目录基本没做什么修改，只改动了章节标题的样式和页眉，要修改可以使用其他宏包。你说的「其他命令」是指？

**Comment by Brightorange90** [comment]
![image](https://user-images.githubusercontent.com/17982426/57578373-6eea4a80-74bd-11e9-90cf-2ce615e040c6.png)
titletoc 这个命令会导致目录有重叠   @zepinglee @stone-zeng 

![image](https://user-images.githubusercontent.com/17982426/57578383-abb64180-74bd-11e9-900c-ca4e83810712.png)

**Comment by Brightorange90** [comment]
> 模版对目录基本没做什么修改，只改动了章节标题的样式和页眉，要修改可以使用其他宏包。你说的「其他命令」是指？

如上图所示

**Comment by Brightorange90** [comment]
> 模版对目录基本没做什么修改，只改动了章节标题的样式和页眉，要修改可以使用其他宏包。你说的「其他命令」是指？

请问，发现该模板的编写内容采用的方式不太寻常，请问内在原理在哪里可以看到详细的介绍？有参考文献么？
如果出现需要修改的内容，自行修改的余地很小。

**Comment by stone-zeng** [comment]
> 请问，发现该模板的编写内容采用的方式不太寻常，请问内在原理在哪里可以看到详细的介绍？有参考文献么？

`fduthesis` 使用 LaTeX3 编写，可以参考我正在写的教程：

  - [LaTeX3 教程（一）——背景知识](https://stone-zeng.github.io/2019-02-24-l3tutorial-background/)
  - [LaTeX3 简介（二）——语法概要](https://stone-zeng.github.io/2019-02-26-l3tutorial-syntax/)

其中也给出了更多的参考资料。

> \cs_new_protected:Npx 这样的命令是指 命令被保护起来了？

是的，实际上就是加了 `protected`。根据 Joseph Wright 的说法，在 LaTeX3/expl3 中，命令要么是完全可展的，要么就是被保护的。

**Comment by Brightorange90** [comment]
> > 请问，发现该模板的编写内容采用的方式不太寻常，请问内在原理在哪里可以看到详细的介绍？有参考文献么？
> 
> `fduthesis` 使用 LaTeX3 编写。官方文档列在了 https://ctan.org/pkg/l3kernel。也可以参考我正在写的教程：
> 
> * [LaTeX3 教程（一）——背景知识](https://stone-zeng.github.io/2019-02-24-l3tutorial-background/)
> * [LaTeX3 简介（二）——语法概要](https://stone-zeng.github.io/2019-02-26-l3tutorial-syntax/)
> 
> 其中给出了更多的参考资料。
> 
> > `\cs_new_protected:Npx` 这样的命令是指命令被保护起来了？
> 
> 是的，实际上就是加了 `\protected`。根据 Joseph Wright 的说法，在 LaTeX3/expl3 中，命令要么是完全可展的，要么就是被保护的。

这样子，大概看了下，入门的话，难度是挺大的

**Comment by stone-zeng** [comment]
这个大概是 `ctex` 那边的问题，下面这段代码就可以复现：

```latex
\documentclass{ctexbook}
\usepackage{titletoc}

\begin{document}
\tableofcontents
\chapter{测试}
\chapter{测试}
\end{document}
```

![image](https://user-images.githubusercontent.com/18233088/57582877-d1af0680-74fc-11e9-958a-1cf00b8252c1.png)

现在模版对目录的处理比较简单，暂时只用到了 `ctex` 宏包提供的接口，还没有考虑对其他宏包的兼容性。有需要的话可以再做修改。

**Comment by Brightorange90** [comment]
> 这个大概是 `ctex` 那边的问题，下面这段代码就可以复现：
> 
> ```
> \documentclass{ctexbook}
> \usepackage{titletoc}
> 
> \begin{document}
> \tableofcontents
> \chapter{测试}
> \chapter{测试}
> \end{document}
> ```
> 
> ![image](https://user-images.githubusercontent.com/18233088/57582877-d1af0680-74fc-11e9-958a-1cf00b8252c1.png)
> 
> 现在模版对目录的处理比较简单，暂时只用到了 `ctex` 宏包提供的接口，还没有考虑对其他宏包的兼容性。有需要的话可以再做修改。

十分感谢！图表目录已经加上去了。目前确实有需求，需要调制目录的一些方面，例如chapter后面也加上虚线，chapter之后的间距稍微缩短点。试着做调制，并没有能成功。

**Comment by stone-zeng** [comment]
在 `ctex`  v2.5 中这一问题已被修复。
