### ISSUE TITLE
图标题和表标题字体不一样

### ISSUE THREAD

**Issue by jinyu121** [stone-zeng/fduthesis#79]
图标题（位于图片下方）目前是宋体。
表标题（位于表格上方）目前是黑体。

这两个是否应该一致？如果需要一致，请修复一下吧。

PS：周五答辩，周四去打论文😂或者有临时fix方法也行。

谢谢

**Comment by stone-zeng** [comment]
这个就是随手那么一写，算是我个人的习惯吧。用的是 `caption` 包做的，可以在导言区直接改：

```latex
\captionsetup[table]{font={small, rm}, labelsep=quad}
```

**Comment by jinyu121** [comment]
目前是全部搞成了黑体：

```
\captionsetup[table]{font={sf}, labelsep=quad}
\captionsetup[figure]{font={sf}, labelsep=quad}
```

如果需要宋体，那么把里面的`sf`改成`rm`即可

如果想要字号小一号（why？？），就像@stone-zeng 回复中那样，再加一个 small 就好了。

**Comment by stone-zeng** [comment]
图表里面的文字，包括图注等，统一用 `\small` 是我的个人习惯……
