### ISSUE TITLE
学位论文独创性声明 和 学位论文使用授权声明 标题字体不对

### ISSUE THREAD

**Issue by jinyu121** [stone-zeng/fduthesis#82]
标题应该是宋体，目前用的是黑体。

参考： [复旦大学博士、硕士学位论文规范（2017.03修订版）](http://www.gs.fudan.edu.cn/6b/9f/c2806a27551/page.htm)

**Comment by jinyu121** [comment]
临时解决办法：`fduthesis.cls`里，去掉`originality-decl-name   / format`和`authorization-decl-name / format` 里面的` \sffamily`。

**Comment by stone-zeng** [comment]
感谢！ci 的报错是另外的问题（#74），不用担心。
