### ISSUE TITLE
中文是不是没有定义斜体字？

### ISSUE THREAD

**Issue by jinyu121** [stone-zeng/fduthesis#84]
比如……

```latex
我想\textit{倾斜}一下
```

编译出来还是普通样式，一点都没有倾斜的迹象。

PS：字体设置： setup里面改成了思源宋，其他默认。

**Comment by stone-zeng** [comment]
是的。

一般中文字体没有斜体（italic）的概念；常规是把斜体映照到楷体上面，但我没这么做。实际上要用 `\fdu@kai` 或者 `\CJKfamily{fdu@kai}` 来切换到楷体（故意弄得这么麻烦的意思，就是叫作者不要自己改样式）。
