### ISSUE TITLE
摘要的页码是否应该从1开始

### ISSUE THREAD

**Issue by jinyu121** [stone-zeng/fduthesis#88]
目前摘要页码是iii，是不是应该从i开始？感觉上来就第三页怪怪的

**Comment by stone-zeng** [comment]
目录也要占位置的呀。

**Comment by jinyu121** [comment]
I mean，目录单独算页数（如果目录长度为1页能否顺便把页码也给去掉？），然后摘要开始重新从i开始计算页数。
目前的做法似乎是“正文之前的所有东西统一从封面后的第一页开始算页数”

**Comment by sonnyhcl** [comment]
把摘要当第一页开始算，这个该怎么改呢？

**Comment by sonnyhcl** [comment]
用了个取巧的方法完成这个目的，不知道算不算best practise
```latex
\begin{document}
  \frontmatter
    \tableofcontents

    % 重新开始计算页码
  \frontmatter
    \input{chapter/摘要.tex}
```

**Comment by zepinglee** [comment]
这样不太好，因为页码有重复，不如直接把目录的页码去掉

**Comment by sonnyhcl** [comment]
手工去掉了目录的页码。模板会打算fix这个么？
```latex
\begin{document}

  \pagenumbering{gobble}
    \tableofcontents
    
  \frontmatter
    \input{chapter/摘要.tex}
    \input{chapter/ABSTRACT.tex}
````

**Comment by stone-zeng** [comment]
感觉类似这样的细节会很多，要想一个统一一点的办法来调整。不急的话，可能要等明年了（笑

**Comment by sonnyhcl** [comment]
是的啊，只能各种手动fix了。最近好多专硕新知道了这个模板，预计接下来这段时间issue数会暴涨hhh

**Comment by jinyu121** [comment]
> 不急的话，可能要等明年了（笑

亲，别忘了连住宿都要自理的专硕同学哦～9月交论文，12月答辩（逃

**Comment by stone-zeng** [comment]
反正我不建议写论文的时候更新模板，万一就搞崩了呢（你看那边 ci 到现在 build 也没通过（当然主要因为懒

**Comment by zepinglee** [comment]
> 感觉类似这样的细节会很多，要想一个统一一点的办法来调整。不急的话，可能要等明年了（笑

感觉贵校模板自由度较大反而更坑

> （当然主要因为懒

从未见过如此……之人

**Comment by zepinglee** [comment]
https://github.com/xueruini/thuthesis/wiki/FAQ#为什么我使用-ctex-292-套件无法编译

**Comment by xnuohz** [comment]
中英文摘要重新编页码，从I开始，这个需要怎么修改啊，大佬

**Comment by MusicJIA** [comment]
> 中英文摘要重新编页码，从I开始，这个需要怎么修改啊，大佬

问题解决了吗？

**Comment by sikouhjw** [comment]
> > 中英文摘要重新编页码，从I开始，这个需要怎么修改啊，大佬
> 
> 问题解决了吗？

将封面开始时的页码设置为
`\pagenumbering{Alph}`
当摘要开始时设置为
`\pagenumbering{Roman}`
即可

**Comment by MusicJIA** [comment]
> > > 中英文摘要重新编页码，从I开始，这个需要怎么修改啊，大佬
> > 
> > 
> > 问题解决了吗？
> 
> 将封面开始时的页码设置为 `\pagenumbering{Alph}` 当摘要开始时设置为 `\pagenumbering{Roman}` 即可

你好，同学。但是，目录中的页码没有对应更新。这个怎么解决？谢谢啦

**Comment by MusicJIA** [comment]
> 反正我不建议写论文的时候更新模板，万一就搞崩了呢（你看那边 ci 到现在 build 也没通过（当然主要因为懒



> 感觉类似这样的细节会很多，要想一个统一一点的办法来调整。不急的话，可能要等明年了（笑

您好。请问目录摘要从 I 开始编页码解决了吗？

**Comment by MusicJIA** [comment]
> > 你好，同学。但是，目录中的页码没有对应更新。这个怎么解决？谢谢啦
> 
> 麻烦你看一下我在 [#320 (comment)](https://github.com/stone-zeng/fduthesis/discussions/320#discussioncomment-8204044) 的回答

问题已解决。非常感谢🙏

**Comment by stone-zeng** [comment]
其实直接把目录放到摘要后面即就行了……

```tex
\begin{abstract}
...
\end{abstract}

\begin{abstract*}
...
\end{abstract*}

\tableofcontents
```

**Comment by MusicJIA** [comment]
> 其实直接把目录放到摘要后面即就行了……
> 
> ```
> \begin{abstract}
> ...
> \end{abstract}
> 
> \begin{abstract*}
> ...
> \end{abstract*}
> 
> \tableofcontents
> ```

感谢感谢！
