### ISSUE TITLE
在overleaf中，将 cjk-font =mac情况下，长时间处于编译状态，然后出现Time Out.

### ISSUE THREAD

**Issue by heyali** [stone-zeng/fduthesis#90]
在overleaf中，将    cjk-font =mac情况下，长时间处于编译状态，然后出现Time Out.

**Comment by zepinglee** [comment]
overleaf 上没有 mac 的中文字体

**Comment by heyali** [comment]
> overleaf 上没有 mac 的中文字体

那有没有解决办法。文件上要求是宋体。

**Comment by zepinglee** [comment]
overleaf 上用默认的就就可以，提交终版时在本地编译

**Comment by heyali** [comment]
> overleaf 上用默认的就就可以，提交终版时在本地编译

再问一个问题，正文要求是小四号字体。为什么    默认 font-size = 5, 应该是-4啊。还是我多事了
