### ISSUE TITLE
overleaf引用不显示问题

### ISSUE THREAD

**Issue by wlhgtc** [stone-zeng/fduthesis#92]
在style中指定bib文件，`   bib-resource = {demo},`，同时`\printbibliography`。
但是报错缺少`gbt7714-unsrt.bst`格式文件，github找到并添加。
仍然不显示引用，想问一下如何解决呢？
![屏幕快照 2019-07-22 08 49 57](https://user-images.githubusercontent.com/16603773/61599667-b891a700-ac5d-11e9-8294-d25b787a4fdf.png)

**Comment by wlhgtc** [comment]
补充：vscode我在配置中指定bib文件，也无法显示引用。
是否还需要别的操作呢？

**Comment by zepinglee** [comment]
bst 是 bibtex 的，\printbibliography 是 biblatex 的，所以你用的是哪个？

**Comment by stone-zeng** [comment]
`\printbibliography` 是重定义过的，所以不论是 bibtex 还是 biblatex 都用这个命令。

问题感觉是没把 bst 传上去，当时传 overleaf 的时候根本没管参考文献。他们那边还是 TL 2017，所以应该要更新一下模版。

**Comment by wlhgtc** [comment]
@stone-zeng  我换用mac-tex的编译好像也有问题，按照我的理解，添加参考文献需要：
1. 在style内指定`bib-resource = {demo}`，demo为同一文件夹下的bib文件。
2. `\printbibliography`去掉注释
但是仍然没有显示参考文献？
然后我换了一个很丑的写法：
`
 \begin{thebibliography}{99}  
 \bibitem{ref1}Zheng L, Wang S, Tian L, et al., Query-adaptive late fusion for image search and person re-identification, Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition, 2015: 1741-1750.  
 \end{thebibliography}
`
这样就work了。
能否给一个正确的demo示范呢，thx！

**Comment by stone-zeng** [comment]
经过尝试，更新相关文件后使用 BibTeX 编译可以使参考文献正常显示，并且没有报错。`biblatex` 试了几次仍然失败，所以暂时就不要在 Overleaf 用了（大多数情况两者功能没什么差别）。

更新过的示例代码（`fduthesis-template`，调整了一些选项，并增加了公式、插图、参考文献、脚注等）已经上传了 Overleaf，等他们审核后应该很快就可以用了。
