### ISSUE TITLE
mathrm

### ISSUE THREAD

**Issue by prlWanted** [stone-zeng/fduthesis#95]

**Comment by prlWanted** [comment]
你好！我在使用你提供的这个包的时候碰到了\mathrm{}无法显示正常的问题。代码是很简单的$1~\mathrm{\mu m}$。显示为：
![image](https://user-images.githubusercontent.com/22358113/63028647-84518500-beaf-11e9-93a0-dc10159fc39a.png)
请问，有什么好的解决办法吗？谢谢！

**Comment by prlWanted** [comment]
另外，$1\mu m$都是能很好编译的，显示为：
![image](https://user-images.githubusercontent.com/22358113/63028821-cd093e00-beaf-11e9-90c8-485e834ffca7.png)
似乎\mathrm{}内的内容都无法正常显示

**Comment by zepinglee** [comment]
单位用 `siunitx` 宏包更方便

**Comment by stone-zeng** [comment]
模板使用了 `unicode-math` 宏包，所以建议改用 `\symrm` 命令代替 `\mathrm`。

但如果是使用单位的话，我也推荐使用 `siunitx` 宏包。
