### ISSUE TITLE
请教：如何引用 graphviz 包

### ISSUE THREAD

**Issue by Jeff-Tian** [stone-zeng/fduthesis#97]
LaTeX 新手，参照文档可以基于 fduthesis 成功编译如下的文档：

```tex
\documentclass{fduthesis}
\begin{document}
    \chapter{欢迎}
    \section{你好！}
    你好，!
\end{document}
```

现在想内联插入 GraphViz 图形，类似这样：

```tex
\documentclass{fduthesis}
\usepackage[pdf]{graphviz}

\begin{document}
\digraph[scale=1]{abc}{rankdir=TB; 
a->b->c
a [label=<foo<SUP>bar</SUP>>];
}
\end{document}
```

编译时出现 ``! LaTeX Error: File `graphviz.sty' not found.`` 这样的错误，我从网上能找到 [`graphviz.sty` 这个文件](https://github.com/mprentice/GraphViz-sty/blob/master/graphviz.sty) ，我应该放在哪儿呢？

那个链接有如何安装的说明，但是是针对另外的 `latex` 工具写的，不清楚用我们 `fduthesis` 文档中的 `xelatex` 应该如何处理。

求指导，谢谢！

**Comment by YuanshengZhao** [comment]
在命令行中执行 `tlmgr install graphviz`。可能需要管理员权限，取决你的安装位置等。

**Comment by stone-zeng** [comment]
本质上这个包是调用 `dot` 来生成 PDF 再把 PDF 插进来，所以 XeLaTeX 下也可以使用：

1. 首先你得装了 graphviz 这个程序（不是 LaTeX 包！），我这边就直接用 homebrew 解决了（mac）。这时候应该开终端检查一下，确保 `dot` 命令是可以使用的。
1. 作为 LaTeX 包的 `graphviz` 是 TeX Live 和 MiKTeX 都自带的，如果没有，应该用**包管理器**（`tlmgr` 或者 `mpm`）来安装，而不是试图直接从 github 拖下来。你用 js/python 的话，肯定是优先使用 npm/pip 对吧？
1. 文档中说了要开 `-shell-escape`，就是允许调用 shell。所以可以这样编译：

```sh
latexmk -xelatex -shell-escape <文件名>
```

或者也可以手动：

```sh
xelatex -shell-escape <文件名>
bibtex <文件名>
xelatex <文件名>
xelatex <文件名>
```

注意手动搞编译变化余地比较大，具体写哪些命令请自己判断。

**Comment by Jeff-Tian** [comment]
@stone-zeng @YuanshengZhao 非常感谢！很详细了，我照着做一下。

**Comment by Jeff-Tian** [comment]
再次感谢两位的帮助，成功了！

```
tlmgr install graphviz
xelatex -shell-escape <文件名>
```

**Comment by Jeff-Tian** [comment]
> 2\. 作为 LaTeX 包的 `graphviz` 是 TeX Live 和 MiKTeX 都自带的，

这个在 mac 上没问题了。不过今天在 Windows 上试了一下，生成图形失败了。`graphviz` 的确已经安装了：

```
tlmgr install graphviz
tlmgr.pl: package repository http://mirrors.cqu.edu.cn/CTAN/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr.pl install: package already present: graphviz
```

但是生成 pdf 时，说 `dot` 不存在。请问有人对 Windows 上的环境熟悉吗？我应该怎么修好这个问题？

```
tlmgr install graphviz
tlmgr.pl: package repository http://mirrors.cqu.edu.cn/CTAN/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr.pl install: package already present: graphviz
```

**Comment by stone-zeng** [comment]
> 1. 首先你得装了 graphviz 这个程序（不是 LaTeX 包！），我这边就直接用 homebrew 解决了（mac）。这时候应该开终端检查一下，确保 `dot` 命令是可以使用的。

这个你装了吗？

如果有 `dot.exe` 但是系统说找不到，那么请把所在路径添加到 `PATH` 环境变量。具体做法参照：

- <https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10>
- <https://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them>

**Comment by Jeff-Tian** [comment]
@stone-zeng 谢谢，安装了 GraphViz 包后，从其安装目录找到 dot 程序了。
