### ISSUE TITLE
请问可以在 authorea.com 中使用吗？

### ISSUE THREAD

**Issue by Jeff-Tian** [stone-zeng/fduthesis#98]
因为 https://authorea.com 可以免费同步 github 仓库，如果在安装了 XeLatex 环境的机器上修改了 论文，传到了 github。那么有时候机器不在身边，想通过 https://authorea.com 来打开和修改论文，可以吗？

https://authorea.com 默认用的是 LaTexXML，不清楚有没有大佬用过 authorea + fduthesis 的经验，有没有相关的指导？

**Comment by stone-zeng** [comment]
这个我不太清楚，可能得要你自己探索了……

**Comment by sonnyhcl** [comment]
Overleaf也支持使用git管理的其实 @Jeff-Tian

**Comment by Jeff-Tian** [comment]
@sonnyhcl 收费太贵了……

谢谢大家的解答，准备直接 github，然后用 action 生成 pdf，不需要用 overleaf 了。

**Comment by sonnyhcl** [comment]
Overleaf免费版就可以啊

**Comment by Jeff-Tian** [comment]
> Overleaf免费版就可以啊

你是 v1 版用户吧，现在 v2 不开放免费使用 git 管理了……
